### ISSUE TITLE
Module not found: Error: Can't resolve './countries'

### ISSUE THREAD

**Issue by imsam67** [catamphetamine/react-phone-number-input#103]
I'm trying to set this up in my React app and I think I'm making a mistake somewhere but not sure where.

The error I'm getting is 

> Module not found: Error: Can't resolve './countries'

Admittedly, I'm not familiar with postcss-loader so I may be making a mistake there. Here's what I've done so far:

1. npm install'ed react-phone-number-input
2. I'm using Webpack so I added the following two lines in my component where I'll be using the phone input:
```
import 'react-phone-number-input/rrui.css';
import 'react-phone-number-input/style.css';
```
3. npm install'ed `postcss-loader` and added `postcss.config.js` file in the root of my app with the following in it:
```
module.exports = {
  parser: 'sugarss',
  plugins: {
    'postcss-import': {},
    'postcss-cssnext': {},
    'cssnano': {}
  }
}
```
4. I then added the following rule in my `webpack.config.js` file. Prior to this, I didn't see any references to css in my webpack.config.js file.
```
{
   test: /\.css$/,
   use: ['style-loader', 'postcss-loader']
 }
```
What am I doing wrong?

**Comment by imsam67** [comment]
Just noticed the section in your notes where you addressed this issue. Somehow I missed it. Thank you!

**Comment by catamphetamine** [comment]
A lot of people miss it.
I was tempted to change it to `countries.json` even.
Seems that somewhere on the internets there's a source of error everyone copy-pastes from.
Who would need to override default extensions.
You tell me.

**Comment by JPlumridge** [comment]
For anyone running into this problem, the issue is if you have a "Resolve" section in your webpack.config file that does NOT include .json.
I ran into this because I was trying to resolve an issue with a separate package that npm couldn't resolve, so added the following resolve section:

`resolve: {
        //     extensions: ['.jsx', '.js']
        // }`

Before you try this make sure you completely delete your node_modules folder and npm install.

**Comment by catamphetamine** [comment]
@JPlumridge Yeah, that's the case.
FYI: I added the explicit `.json` extensions since then because people kept reporting the issue. You might want to update the package if you have an older version.
