### ISSUE TITLE
"export 'as_you_type' was not found in 'libphonenumber-js'

### ISSUE THREAD

**Issue by davityavryan** [catamphetamine/react-phone-number-input#108]
Hi,

I see that you have updated `as_you_type` import from `libphonenumber-js` to `AsYouType` [here](https://github.com/catamphetamine/react-phone-number-input/blame/b02457a33afc28219966320203c45867629c1d52/source/Input.js#L4) on Jan 20. But also last time when you updated package.json version (package itself) was at Oct 23 [see here](https://github.com/catamphetamine/react-phone-number-input/blame/b02457a33afc28219966320203c45867629c1d52/package.json#L3)

Can you please do new npm release?

p.s. Found issue via webpack's warning
```
WARNING in ./node_modules/react-phone-number-input/modules/Input.js
1086:21-32 "export 'as_you_type' was not found in 'libphonenumber-js'
 @ ./node_modules/react-phone-number-input/modules/Input.js
 @ ./node_modules/react-phone-number-input/index.js
```

**Comment by catamphetamine** [comment]
Indeed, missed that one.
Was too busy working on `0.16.0` (big refactoring).
Thanks, released the fixed `react-phone-number-input@0.15.3`.
https://github.com/catamphetamine/react-phone-number-input/commit/1679c24859668ec62d7464d12fdf9937ab434d7d

**Comment by davityavryan** [comment]
Thanks a lot. :)

**Comment by catamphetamine** [comment]
By the way, I don't know why didn't it find `as_you_type` in a `0.4.x` version of `libphonenumber-js` because I only removed those deprecations somewhere in `1.0.x`.
Whatever, as long as it works now it's fine with me.

**Comment by davityavryan** [comment]
Hey.
Just adding this here.

```
yarn install v1.1.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/react-phone-number-input/-/react-phone-number-input-0.15.3.tgz: Request failed \"404 Not Found\""
```

:/

p.s. instalation of react-phone-number-input@0.16.0 works fine

I just wanted to understand what happened with that version?

**Comment by catamphetamine** [comment]
Yeah,  that's the reason
https://github.com/catamphetamine/react-phone-number-input/issues/109#issuecomment-367473748
So turned out that updating `libphonenumber-js` in a minor version update was not that great of an idea (perhaps touching it at all).
A series of hasty steps without me taking the time to test it all properly lead to a confusion and two packages which I unpublished later when I fully understood the implications.
