### ISSUE TITLE
update to reflect change on libphonenumber-js

### ISSUE THREAD

**Issue by jimmythigpen** [catamphetamine/react-phone-number-input#109]
I'm seeing the following error:

![image](https://user-images.githubusercontent.com/9611366/36501803-1bd9551c-1716-11e8-95b3-f9b944fa25ec.png)

After digging a bit I think it has to do with `libphonenumber-js` updating `country_phone_code_to_countries` to `country_calling_codes`

ref to their update: https://github.com/catamphetamine/libphonenumber-js/blob/af14ca96e5ef9228af2bab6c779014cf060ed00f/source/metadata.js

**Comment by catamphetamine** [comment]
Thanks.
That's true, I didn't test it at all today when I released the version update for `libphonenumber-js` dependency.
Perhaps I wasn't thinking too straight.
Released the new version `react-phone-number-input@0.15.4` which seems to be working.

**Comment by catamphetamine** [comment]
Actually I've just thought that I should bump the major version as well.
Released `react-phone-number-input@0.16.0`.
Unpublished `react-phone-number-input@0.15.4` and `react-phone-number-input@0.15.3`.
