### ISSUE TITLE
bootstrap support?

### ISSUE THREAD

**Issue by cbschuld** [catamphetamine/react-phone-number-input#112]
All,

First, great work on this!  Before I dive into adding the styles to make this work with bootstrap I thought I would ask if anyone has worked on this in the past?  If not I'll continue down the road I am on and backfill a PR to cover it.  However, I didn't want to re-invent/create something that exists.

Thanks!

**Comment by catamphetamine** [comment]
Hello.
Not sure what you mean by "bootstrap support".
And it's a wise decision to ask before making a PR because I'm not sure if it needs to be a part of this library.

**Comment by cbschuld** [comment]
@catamphetamine - absolutely, that's why I wanted to start the dialog for sure.

Right now there are two CSS files included for styling.  I am attempting to find out if there is one already pre-baked to match the look & feel of Bootstrap4 (https://getbootstrap.com/) . Thanks!

**Comment by cbschuld** [comment]
extending on info above ^^^ getting that custom class into that button/select(or) looks like it may fall into this repo as well - specifically: https://github.com/catamphetamine/react-responsive-ui/blob/master/source/Select.js#L633

**Comment by catamphetamine** [comment]
Yeah, looks like.
So, the only thing you need is adding a CSS class option for the select button?
Nothing else?

**Comment by cbschuld** [comment]
@catamphetamine - yes, additionally I have two adjusted CSS files which I am happy to contribute in as *-bootstrap.css ... but I think so (as of right now).  I just started to explore re-styling it so I might bump into another case but I think so sir!

**Comment by catamphetamine** [comment]
Released `publish:react-phone-number-input@0.17.2` which has `countrySelectToggleClassName`.
See if it works for you.
You can paste the adjusted bootstrap styles here so that other people using bootstrap could copy-paste them.

**Comment by cbschuld** [comment]
@catamphetamine - wonderful; thanks!  I tried it w/ this:

![image](https://user-images.githubusercontent.com/231867/37044141-f26d4fa8-211f-11e8-89f8-b598174b2a11.png)

but didn't see it (I did validate I have .17.2 as well) and I do see the option in the updated source but it did not apply the class to the button

![image](https://user-images.githubusercontent.com/231867/37044148-f8e7bcb0-211f-11e8-9469-6d4c569f88ed.png)

**Comment by catamphetamine** [comment]
hmm, maybe `react-responsive-ui` didn't update.
check that `react-responsive-ui` version is the latest one: 0.10.31.

**Comment by cbschuld** [comment]
├─ react-phone-number-input@0.17.2
.
.
├─ react-responsive-ui@0.10.31
.
.

@catamphetamine - confirmed on both

**Comment by cbschuld** [comment]
@catamphetamine - I flushed everything and now it is there; cache must have bit me; sorry

**Comment by cbschuld** [comment]
![image](https://user-images.githubusercontent.com/231867/37044548-fbec1fea-2120-11e8-9618-2d203f36b30d.png)
looks great @catamphetamine - thanks, I'll bundle up the CSS changes and present them back in this issue!
