### ISSUE TITLE
Dictionary not updating on componentWillReceiveProps

### ISSUE THREAD

**Issue by proko** [catamphetamine/react-phone-number-input#115]
Hi,

I'm trying to translate the countries list updating the `dictionary` prop like this
```
<Phone
  onCountryChange={this.onPhoneCountrychange}
  value={this.state.phone}
  onChange={this.onPhoneChange}
  dictionary={this.state.countriesTranslation}
/>
```
but the list is not updating when state changes. 
I noticed in https://github.com/catamphetamine/react-phone-number-input/blob/75852e62931c460a18f08ac7468ebc5e19a098e8/source/Input.js#L835-L838 
that when component receives new props, the new country still uses the old dictionary:

Am I right thinking that `new_props.dictionary` would take care of it? Or am I just missing something?

Thanks.

**Comment by catamphetamine** [comment]
Hello.
The current version finalizes the dictionary upon component creation hence it's not dynamic.
I'm currently rewriting the library and version 1.0 will be released in the course of the following days.
I could implement support for dynamically changing `dictionary` there.

**Comment by proko** [comment]
Would be awesome. Looking forward to 1.0 then!

**Comment by catamphetamine** [comment]
@proko I released the rewrite today.
`dictionary` was renamed to `labels` and changes country labels.
Migration to `1.0.0` is mostly renaming properties:
https://github.com/catamphetamine/react-phone-number-input/blob/master/CHANGELOG.md

**Comment by proko** [comment]
Thanks @catamphetamine . Just updated and translations work. 

Regarding the update however we were one of the few using `onCountryChange ` and it was for displaying the call prefix automatically when country was changing. Maybe this is a common use case?

Also another use case (unrelated to `onCountryChange`) is having to update flag and/or phone from outside the component. Specifically we have a country field and would like to set flag and prefix in phone input when country changes. I have managed to pass the prefix but can't update the flag. It looks like the only way to trigger a flag change is by manually dispatching a `onChange` event but for that I need access to the underlying input element. 
Do you have any suggestions?

**Comment by catamphetamine** [comment]
Hello.
I still don't understand.
Can you provide an example of what you're trying to do?

**Comment by proko** [comment]
Sure, 
I have a form with a country of residence select field and the phone input.
What I want is when user selects country of residence, to also fill the phone input with the country flag and country prefix and let user only add the actual phone number.

I can use the `value` prop to pass the prefix code but have no way to trigger a flag change.

Hope I explained it better now!

**Comment by catamphetamine** [comment]
So you're using `react-phone-number-input` but you also have a separate country select?

**Comment by proko** [comment]
Correct. Users can live in one place and give a phone number form another country.

**Comment by catamphetamine** [comment]
So you're using `react-phone-number-input` but you also have a separate country select, and when a user selects a country of residence you want this country to also be selected inside `react-phone-number-input` component?

**Comment by proko** [comment]
Exactly

**Comment by catamphetamine** [comment]
You can do that by passing `country` property to `react-phone-number-input` component.
It works until a user enters something in the phone number input field.

**Comment by proko** [comment]
Cool, I'll try it thanks!

**Comment by catamphetamine** [comment]
If there are any other issues left then you can re-ask them there.

**Comment by proko** [comment]
Well actually the country alpha2Code now is being passed to to `react-phone-number-input` but flag is not changing 
I have just this
```
<Phone
      value={this.state.phone}
      onChange={this.onPhoneChange}
      country={this.state.phoneCountry}
      labels={this.state.countriesTranslation}
/>
```

and updating the props with this
```
componentWillReceiveProps(nextProps) {
        this.setState({
            phone: nextProps.initialPhone,
            phoneCountry: nextProps.country,
            countriesTranslation: nextProps.translations,
      });
 }
```

**Comment by catamphetamine** [comment]
[bundle.zip](https://github.com/catamphetamine/react-phone-number-input/files/1907721/bundle.zip)

Open `index.html`, scroll down to the bottom and push "Set country to FR" button - it changes the flag to `FR`.

**Comment by proko** [comment]
Not sure what's going on here.  We have the same code but my flag is not changing. I'll try to debug further and come back with updates

**Comment by catamphetamine** [comment]
If you have the latest version then it's strange.
You may be on React >= 16.3 and it might have some different behaviour.
The demo uses React 15.
I recently refactored the component to use the new `getDerivedStateFromProps()` instead of `componentWillReceiveProps()` (that's where the `country` property is compared) so it may be a bug too.
You can always edit `node_modules/react-phone-number-input/modules/Input.js` to add some `console.log()`s inside `getDerivedStateFromProps()` and see if it behaves.

**Comment by proko** [comment]
I'm on 16.2. Thanks for the hint I'll have a look that direction!

**Comment by proko** [comment]
OK, I took your advice and debugged `getDerivedStateFromProps`. Problem ends up to be that when this method fires up I also have a `new_value` here https://github.com/catamphetamine/react-phone-number-input/blob/70fea8ca75a7c70ab922fc7f2ffc5c499d211ce5/source/Input.js#L521 because I want to also show the prefix when country of residence is selected. So the condition is false. 

I think `onCountryChange` would be useful here.

**Comment by catamphetamine** [comment]
Why do you want to show the prefix if there is already country flag indicating the country.

**Comment by catamphetamine** [comment]
If you're hiding the flag then you can substitute it with your own React element before the input field.

**Comment by proko** [comment]
It's just how it's designed. Not my decision. But in my opinion it's useful because let's users know they only need to add their phone number. This is how it works when creating a google account by the way :)

**Comment by catamphetamine** [comment]
I mean, you could place a `<span/>` before the `<input/>` and change the value of the `<span/>` to `+1` if a user selects `USA` not touching the `<input/>` value at all.

**Comment by catamphetamine** [comment]
Or actually you can set the `value` to `+1` and it will show `+1` so I don't see how could it not be working.

**Comment by catamphetamine** [comment]
Ah, I see, so if you set `value` to `+1` then you'll be unable to change the country.

**Comment by catamphetamine** [comment]
Well, you could be doing it like:

* Set `value` to `undefined`
* Change the `country`
* Set `value` to `+...`
