### ISSUE TITLE
React 16.3.1 Warning

### ISSUE THREAD

**Issue by sersart** [catamphetamine/react-phone-number-input#116]
I moved from react 16.2 to 16.3.1 and get warning 
index.js:2178 Warning: PhoneNumberInput.getDerivedStateFromProps(): A valid state object (or null) must be returned. You have returned undefined.

**Comment by catamphetamine** [comment]
I created an issue in React repo.
We'll see what they decide.
https://github.com/facebook/react/issues/12562

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@1.0.5` with the fix.

**Comment by sersart** [comment]
Tested, no problems. Thanks, good job.
