### ISSUE TITLE
Some redux-form properties doesn't change

### ISSUE THREAD

**Issue by RakhmatovR** [catamphetamine/react-phone-number-input#117]
Well, I wrapped your component into `Field` by `redux-form` and trying to get some meta information, like that:
```js
class wrappedPhone extends React.Component {
	/* ... */

	render() {
		console.log(this.props.meta); <------- this one
		const { input } = this.props;
		
		return (
			<Phone
				value={input.value}
				onChange={this.handleOnChange}
			/>
		);
	}
}
```

```js
<Field
	name="phone"
	component={wrappedPhone}
/>

```
and while trying to focus/blur/change field there are at least `visited` and `touched` meta props doesn't change.

For simple `input` it works ok.

**Comment by catamphetamine** [comment]
Try it like

```js
<Field
	name="phone"
	component={Phone}
/>
```

Without any wrapping.
And see if it works.

**Comment by RakhmatovR** [comment]
I need this wrapping anyway, it should be a bug.

**Comment by catamphetamine** [comment]
If it works without any wrapping then it's not a bug.

**Comment by RakhmatovR** [comment]
@catamphetamine how can I get access to redux-form props from not-wrapped component? It's weird.

**Comment by catamphetamine** [comment]
Provide an example

**Comment by RakhmatovR** [comment]
At the head already.

**Comment by catamphetamine** [comment]
So what's the exact issue you're having?

**Comment by RakhmatovR** [comment]
Found the problem.
It was needed to provide `input.onBlur` and `input.onFocus` to your component. Then redux-form props will be changed.

**Comment by catamphetamine** [comment]
You don't need to provide `input.onBlur` if the component is not wrapped.
You do need to do that if the component is wrapped because it handles it automatically.
https://github.com/catamphetamine/react-phone-number-input/blob/master/source/Input.js#L47-L48
When wrapping components pass `{...this.props}` to it.

Don't know about `onFocus`, I'm not handling it in any way in the library.

**Comment by RakhmatovR** [comment]
Yep. Maybe it should be written in docs to not doing mistakes. But not sure.

**Comment by catamphetamine** [comment]
> Maybe it should be written in docs to not doing mistakes. But not sure.

No, it's purely a `redux-form` thing.
The only way is to pass `{...this.props}` to the component being wrapped.
