### ISSUE TITLE
Dependency on react-responsive-ui

### ISSUE THREAD

**Issue by goodmind** [catamphetamine/react-phone-number-input#118]
Can't this library be UI agnostic? 
How to use custom selects from other react ui kits or native one?

**Comment by catamphetamine** [comment]
Clarify your question.
One question at a time.

**Comment by goodmind** [comment]
@catamphetamine it's one question. If you support custom selects you don't need to depend on UI library

**Comment by catamphetamine** [comment]
No, it's two questions.
Are you gonna ask one question or not?

**Comment by catamphetamine** [comment]
The native select is showcased on the demo page.
A custom React Select Component can be passed, see the source code.
https://github.com/catamphetamine/react-phone-number-input/blob/548dea571306e71b5b840d65e53246c4e9ead46f/source/Input.js#L157-L158

**Comment by goodmind** [comment]
@catamphetamine what props exactly I need to implement?

**Comment by catamphetamine** [comment]
The one that's mentioned in my comment

**Comment by catamphetamine** [comment]
And there's also `inputComponent` property if you want to customize phone number input

**Comment by catamphetamine** [comment]
FYI: Added `react-phone-number-input/native` which doesn't depend on `react-responsive-ui`.
