### ISSUE TITLE
Possibility to show international prefix always?

### ISSUE THREAD

**Issue by RakhmatovR** [catamphetamine/react-phone-number-input#120]
Is it possible to show international prefixes always and type international numbers only?
Because now it's not clear how a prefix is added to the phone number.

### Example
I write international number `+7 800 555 35 35`. Country is set to `RU`. If i want to clear input field and type another phone number than it's possible to write it as a national one `8 800 555 35 35` and without any prefix `800 555 35 35`. Input value will be `+7 800 555 35 35` but user will see only typed number (without +7, etc).

I guess it would be not bad if it will be possible to not format input by a component and validate by self (e.g. `redux-form`).

**Comment by catamphetamine** [comment]
It is unclear what you want to achieve.

There's no "forced" international mode because if the user wants to enter a phone as a local one then he can do so and he's not restricted in doing that.

The last sentence is also unclear.

**Comment by RakhmatovR** [comment]
Will rephrase. Is it possible to restrict writing number in national format?

**Comment by catamphetamine** [comment]
> not user-friendly, isn't it?

It isn't.
The issues are in your architecture.

> saving phone number in local format 

1. Save phone numbers in international format
2. Convert phone numbers to local format with `libphonenumber-js` manually
