### ISSUE TITLE
Error when importing the module

### ISSUE THREAD

**Issue by Guillaumebwavy** [catamphetamine/react-phone-number-input#121]
"TypeError: Super expression must either be null or a function, not undefined"
I haven't changed anything in my code since it worked, just "yarn install" and all the app broke. It works again when I remove the import line.

**Comment by catamphetamine** [comment]
https://stackoverflow.com/questions/30116430/reactjs-giving-error-uncaught-typeerror-super-expression-must-either-be-null-or
Which React version are you on.
