### ISSUE TITLE
smartCaret doesn't seem to be working

### ISSUE THREAD

**Issue by since78pl** [catamphetamine/react-phone-number-input#123]
Hi,

I am using this library in version 1.0.10:
```javascript
"react-phone-number-input": {
      "version": "1.0.10",
      "resolved": "https://registry.npmjs.org/react-phone-number-input/-/react-phone-number-input-1.0.10.tgz",
      "integrity": "sha512-XxLkj1brNOxAebFDO/GT5GyMqrwqTONvu5XbxKf+DRLGOfaU29i0/4n4uuOVyjAdwJJNyma5c8weaD9XKeOifg==",
      "requires": {
        "classnames": "2.2.5",
        "input-format": "0.2.2",
        "libphonenumber-js": "1.1.7",
        "prop-types": "15.5.10",
        "react-lifecycles-compat": "3.0.2",
        "react-responsive-ui": "0.10.35"
      }
    },
```

Unfortunately when I am using `smartCaret={ false }`, SmartInput is still rendered. Also tried to pass  input component by `inputComponent={BasicInput}`, but it's doesn't work either. Any suggestions?

Here's my implementation:
```javascript
import Phone from 'react-phone-number-input';

<Phone
                placeholder={phonePlaceholder}
                country="PL"
                countries={['PL', 'DE']}
                smartCaret={ false }
                onChange={this.handlePhoneChange}
                value={this.state.phone}
                autoComplete="off"
                labels={{ PL: '+48', DE: '+49' }}
              />
```

**Comment by catamphetamine** [comment]
Why do you think "SmartInput is still rendered"?

**Comment by since78pl** [comment]
I mean, Smart Caret is working and Android bug from this issue (https://github.com/catamphetamine/react-phone-number-input/issues/75) still occurs.

**Comment by catamphetamine** [comment]
So is "SmartInput is still rendered" or not?

**Comment by since78pl** [comment]
I am not sure if I understand your question.
I have SmartInput instead of BasicInput even if I pass `smartCaret={ false }` and Android bug still occurs.

**Comment by catamphetamine** [comment]
> I have SmartInput instead of BasicInput

What do you mean exactly by saying that?

**Comment by since78pl** [comment]
I mean that I still have an issue with Samsung Android phone and cursor doesn't keep up with typing.
Phone: Samsung Galaxy Note4
Android: v. 6.0.1
Browser: Samsung Internet v. 6.4.10.5

**Comment by catamphetamine** [comment]
That's a whole another then.
I don't have a "Samsung Galaxy Note4" so I won't be able to verify or refute that.
So I'm closing this issue being a duplicate.

**Comment by catamphetamine** [comment]
Also check the demo page - if `smartCaret={false}` example there doesn't work on your Samsung phone then leave a comment in the Android caret bug issue.
