### ISSUE TITLE
Disable underline 

### ISSUE THREAD

**Issue by adamszeptycki** [catamphetamine/react-phone-number-input#124]
Hey,
I can't find an option to disable underline. How can I do it?

**Comment by catamphetamine** [comment]
What do you mean exactly.
Provide a screenshot.

**Comment by adamszeptycki** [comment]
<img width="290" alt="screen shot 2018-04-27 at 22 27 35" src="https://user-images.githubusercontent.com/759248/39383620-358ebc04-4a6a-11e8-91d4-e30a76358840.png">
This blue underline. I would like to be able to remove that line.

**Comment by catamphetamine** [comment]
Simply disable the border on the input.

```css
.react-phone-number-input__phone { border: 0 }
```
