### ISSUE TITLE
Change country code on selecting countries.

### ISSUE THREAD

**Issue by Triyugi** [catamphetamine/react-phone-number-input#125]
Is it possible to change country codes when changing the country from select?

**Comment by catamphetamine** [comment]
Clarify yourself.

**Comment by Triyugi** [comment]
@catamphetamine  I have created a [sandbox code](https://codesandbox.io/s/pnv5480q0) please check. When I am changing country from select box, I want to get the country code in input box. Let's say if I select India as country I want to get +91 in input box.

**Comment by catamphetamine** [comment]
I see.
There's no such feature.
And I guess it won't be implemented.
