### ISSUE TITLE
When clicking on the flag list on firefox, it scroll to the top of the page

### ISSUE THREAD

**Issue by Senshii** [catamphetamine/react-phone-number-input#126]
Hello,
I use firefox 60, when I click on the flag to expand the select of country it scrolls to the top of the page. There is no problem with Chrome.

**Comment by catamphetamine** [comment]
I've updated to Firefox 60.0 and don't observe any bugs.
The bug you're describing was present in IE:
https://github.com/catamphetamine/react-responsive-ui/blob/a21daec3640944e81fb47012a64ceec918378e39/source/Select.js#L1525-L1527

**Comment by Senshii** [comment]
Ok i'm looking further in my app to find the origin.

**Comment by catamphetamine** [comment]
Try the demo page and see if you experience the bug.

**Comment by Senshii** [comment]
No bug on the demo page. You can close this issue.
