### ISSUE TITLE
React 16.3.1 deprecated lifecycle methods

### ISSUE THREAD

**Issue by ronaldruzicka** [catamphetamine/react-phone-number-input#127]
Hi, firstly, thanks for you plugin, it's awesome!

I'm using React `16.3.1` on a project and just got this warning about deprecated lifecycle methods.

Are you planning to rewrite them to be React `16.3` ready?

![screen shot 2018-05-16 at 11 20 54](https://user-images.githubusercontent.com/20684387/40108583-a3de00ee-58fb-11e8-850e-175f78bf5bc7.png)

**Comment by catamphetamine** [comment]
I had a similar warning in my other project and updating `react-hot-loader` to the latest version fixed that.
https://github.com/reactjs/react-modal/issues/649#issuecomment-387263811
Because older version of `react-hot-loader` depended on an old version of `react-lifecycles-compat`.
