### ISSUE TITLE
Question: validation on country onChange

### ISSUE THREAD

**Issue by Subha** [catamphetamine/react-phone-number-input#128]
Our client have reported this issue:

1. Select Anguilla country and save phone number 2647723456 where 264 is the only one area code 
   of Anguilla. 
2. Now edit and select country as Antigua and Barbuda, it’s not throwing any error (isValid to false) 
    as 264 is not the area code of Antigua and Barbuda and able to save successfully. w
3. Also when we reopen the card country is changing to Anguilla which is because of the area code 264.

My question is from the application can we remove the phone number onChange of the country which would be easier rather than checking for validity? 

I am able to reproduce the same issue in - http://catamphetamine.github.io/react-phone-number-input/

Any other Suggestion?

Thank you.

**Comment by catamphetamine** [comment]
> Also when we reopen the card country is changing to Anguilla which is because of the area code 264.

It's not changing for me.

It's not clear which exact error are you experiencing.

**Comment by Subha** [comment]
Thank you for the response. I see it is coming from the libPhonenumber and seems like 264 is not a valid area code for antigua.

https://www.howtocallabroad.com/antigua/

This is how I am updating the country.

  ```
import { formatNumber, isValidNumberCustom, parseNumber } from 'libphonenumber-js/index.es6.js';
   formattedPhone = formatNumber(parseNumber(this.state.phone), 'International');
      phoneInfo = parseNumber(this.state.phone);
      country = phoneInfo.country;
```

Valid area code for Antigua and Barbuda is 268. 
But if we provide 2647723456 for Antigua and Barbuda it returns the **country as AI**. But for the number having area code as 264 it returns the country as AG.

Do you suggest any way to get the country on the onChange?

**Comment by catamphetamine** [comment]
I still don't undestand what you're doing exactly.
I can see you described it in detail but I just don't understand it.

**Comment by Subha** [comment]
I also checked the google library and seems like this number(2647723456) is a valid number for Antigua and Barbuda, United States and India too.
https://libphonenumber.appspot.com/phonenumberparser?number=2647723456&country=AG

Even though the 264 is not the area code for Antigua and Barbuda it shows it is valid.
The problem that we are facing is even when I change the Country from Anguila to United States I get the country code back as AI.

Any suggestions that we could fix the country code?

I was able to reproduce the same issue in libPhoneNumber from google. 
![screen shot 2018-05-24 at 10 26 45 am](https://user-images.githubusercontent.com/12513265/40492365-52a7bfc8-5f3e-11e8-9352-ec629594daa7.png)

**Comment by catamphetamine** [comment]
> 1. Select Anguilla country and save phone number 2647723456 where 264 is the only one area code
of Anguilla.

I go to the demo page to the "Validation" section and select "Anguilla" and paste "2647723456". It is showing valid.

> Now edit and select country as Antigua and Barbuda, it’s not throwing any error (isValid to false)
as 264 is not the area code of Antigua and Barbuda and able to save successfully. w

I select "Antigua and Barbuda" and it is showing valid. It is correct.

> Also when we reopen the card country is changing to Anguilla which is because of the area code 264.

It doesn't change to Anguilla when I reopen the country select.

> I also checked the google library and seems like this number(2647723456) is a valid number for Antigua and Barbuda, United States and India too.
https://libphonenumber.appspot.com/phonenumberparser?number=2647723456&country=AG

And it also valid for many other countries if using the "default" metadata. (Google's demo uses "full" metadata).

> Any suggestions that we could fix the country code?

I don't see any bugs.

**Comment by catamphetamine** [comment]
@Subha I can only look at bugs happening on the demo page.
If you're having bugs in your own app and not on the demo page then you're on your own.

**Comment by catamphetamine** [comment]
> Unfortunately in your demo page you are not showing(display) the country code when we change the Country from the dropdown.

I am showing the country code: the flag icon is the country code.

**Comment by catamphetamine** [comment]
> i would like to know how to get the Country code when the country flag is changed?

What do you need it for?

**Comment by Subha** [comment]
To update the Database with the country 
From the component we send back the phone object to the application .

**country: AI, isValid: true, phone: +12647723456, ext: , formattedPhone: +1 264 772 3456**
 Below is my code to update country from the phone number entered.

import {**parseNumber** } from 'libphonenumber-js/index.es6.js';
phoneInfo = **parseNumber**(this.state.phone);
country = phoneInfo.country;

**Comment by catamphetamine** [comment]
Still it's unclear what for do you need to get the country code on country change.

**Comment by Subha** [comment]
I need to get the country code to update the database. 

I already have the logic to get the country code from libphonenumber library but for this scenario of entering Anguila number(2647723456) even though the country selected is United States I get a result back from the parseNumber that the number entered is for country **AI**

phoneInfo = parseNumber('2647723456');
country = phoneInfo.country; => "AI"

Since this is coming from the metaData I was wondering if i can change my logic based on the country change from the dropdown.

**Comment by catamphetamine** [comment]
> I need to get the country code to update the database.

Why do you update a database every time a user changes a country

**Comment by Subha** [comment]
I need to update it only on the onBlur of the component

**Comment by catamphetamine** [comment]
Why do you need the currently selected country in your database?

**Comment by Subha** [comment]
How else can I get the country Code?

**Comment by catamphetamine** [comment]
Which country code do you want to get?

**Comment by Subha** [comment]
When a country is selected and a phone number is entered. The user assumes the country selected and phone number input are tied together. From the component we will have to send the phone object with country code in the onBlur.

**Comment by catamphetamine** [comment]
> The user assumes the country selected and phone number input are tied together.

Yes, they are: the country calling code is prepended to the number digits (basically).

> From the component we will have to send the phone object with country code in the onBlur.

You don't have to send the country.
The `value` phone number doesn't need any country code, it's sufficient by itself.
You don't need the country code to dial the `value` on a phone.

**Comment by Subha** [comment]
I agree to your point. But their requirement is to save the phone number with the country code. ('US')

**Comment by catamphetamine** [comment]
Well, if there's a requirement someone imposed on you then they can explain it.
Otherwise I don't think it's possible in this library.

**Comment by catamphetamine** [comment]
@Subha If you want you can always copy-and-paste the source code and modify it as you want in your project.
E.g. copy the sources to `src/react-phone-number-input` folder of your project and then replace `import Phone from 'react-phone-number-input'` with `import Phone from './src/react-phone-number-input/InputWithDefaultMetadata'`

**Comment by Subha** [comment]
oh well, they just want to support for backward compatibility.
 
I was able to get the country code with the **parseNumber** from libPhonenumber libarary until we found this issue on our end.. 

phoneInfo = parseNumber('2647723456');
country = phoneInfo.country; => "AI"

**Comment by catamphetamine** [comment]
So, it's about legacy code then.
Ok.
Maybe I'll add such a feature.
I'll see.

**Comment by Subha** [comment]
Truly appreciate it. Thank you for your taking time on this.

I agree that we can take your code and modify it but sometimes were not able to keep up with any other changes in the core library.
