### ISSUE TITLE
Problem when removing phone number

### ISSUE THREAD

**Issue by sersart** [catamphetamine/react-phone-number-input#129]
Hi,
please check. When removing phone number, it is not removing all chars.
contact_phone1 +9
contact_phone1 +99
contact_phone1 +998
contact_phone1 +9987
contact_phone1 +99871
contact_phone1 +998712
contact_phone1 +9987123
contact_phone1 +99871233
contact_phone1 +998712333
contact_phone1 +9987123333
contact_phone1 +99871233333
contact_phone1 +998712333333
contact_phone1 +99871233333
contact_phone1 +9987123333
contact_phone1 +998712333
contact_phone1 +99871233
contact_phone1 +9987123
contact_phone1 +998712
contact_phone1 +99871
contact_phone1 +9987
contact_phone1 +998
contact_phone1 +99
contact_phone1 +9

living +9
Thanks

**Comment by catamphetamine** [comment]
Works for me

**Comment by soldat27** [comment]
I have the same problem(

**Comment by catamphetamine** [comment]
Then make a GIF demo

**Comment by soldat27** [comment]
![1](https://user-images.githubusercontent.com/4384731/40486752-d9a7d6b2-5f6a-11e8-8a69-abd224a658fb.gif)
reproduce on demo page([http://catamphetamine.github.io/react-phone-number-input/](url))
if I remove "+" it's happened

**Comment by catamphetamine** [comment]
I see no "bug" here.

**Comment by soldat27** [comment]
I enter 222 and in value +33222? It is not a bug?
![1527167192333](https://user-images.githubusercontent.com/4384731/40487344-8e708ad4-5f6c-11e8-9810-78411db01738.jpg)

**Comment by catamphetamine** [comment]
What `value` did you expect?

**Comment by sersart** [comment]
When phone number removed, country code has to be reseted.

**Comment by soldat27** [comment]
without 33

**Comment by catamphetamine** [comment]
Why?

**Comment by soldat27** [comment]
смотри, я ввожу телефон к примеру
37533 а потом передумал - удаляю все полностью и начинаю вводить сначала 
и уже 375 не удаляется. а если я хотел бы добавить телефон другой страны? неявное поведение как по мне

**Comment by catamphetamine** [comment]
Select another country if you want another country
