### ISSUE TITLE
I use phone mask without showContrySelect and country code can't clean

### ISSUE THREAD

**Issue by soldat27** [catamphetamine/react-phone-number-input#130]
https://github.com/catamphetamine/react-phone-number-input/issues/129
i can't select another country

**Comment by soldat27** [comment]
I use phone mask for this field
![dffd2126ca](https://user-images.githubusercontent.com/4384731/40489105-0cf38d58-5f71-11e8-8cad-db400365d6bb.jpg)
My code: 
`<Phone
										type="text"
										placeholder="Номер телефона"
										value={phone.value}
										style={{}}
										name="phone"
										showCountrySelect={false}
										onChange={((value) => this.onChange(value, 'phone'))}
									/>`

showCountrySelect I set in false. And I can't see select country dropdown, but country code doesn't clear after I clear input

**Comment by catamphetamine** [comment]
If you're not using country select then pass `countries={[]} international` properties to make only "International" country available.
First test without `showCountrySelect={false}`.
