### ISSUE TITLE
Disable country selection after mask inited

### ISSUE THREAD

**Issue by soldat27** [catamphetamine/react-phone-number-input#135]
I don't use showCountrySelect and contries set to []. But after init phone mask it set by default country

**Comment by catamphetamine** [comment]
Not understand.
Describe again.

**Comment by soldat27** [comment]
`<PhoneInput
						type="text"
						placeholder="Номер телефона"
						value={value}
						style={{}}
						name="phone"
						showCountrySelect={false}
						countries={[]}
						onChange={(value) => this.onChange(value, 'phone')}
					/>`
When value is empty - it works good.
When value = +375 29 123 45 67 it set default country Belarus. But I don't use showCountrySelect and I don't see it. Main problem that I clear my input, but value in it  + 375. I need to disable set default country when page load

**Comment by catamphetamine** [comment]
> When value = +375 29 123 45 67 it set default country Belarus.

Not understand.

**Comment by soldat27** [comment]
Value from server

**Comment by catamphetamine** [comment]
Not understand

**Comment by soldat27** [comment]
Если я ввожу руками +375292014001 а затем очищаю - все работает хорошо
Если эти данные приходят от сервера или берутся из стора, т.е при загрузке компонента value не пустое, то маска подстваляет Беларусь автоматически. Как можно это выключить? Потому что при полной очистке инпута остается +375

**Comment by catamphetamine** [comment]
Отправляйте поэтапно скриншоты с пояснениями, ничего не понятно.

**Comment by soldat27** [comment]
Вот два инпута
https://codesandbox.io/s/k0rw2n9qq5
попробуй в первом написать +375 29 123 45 67, потом все удали а потом заново напечатай телефон - все работает
А теперь во втором удали номер полностью и попробуй начать печатать. Телефон печатается но код 375 уже стоит автоматически и его нельзя убрать никак. Так как у меня нет выбора страны

**Comment by catamphetamine** [comment]
Не работает.

**Comment by soldat27** [comment]
Попробуй тут
https://k0rw2n9qq5.codesandbox.io/

**Comment by catamphetamine** [comment]
Released `1.1.6` with the fix.

**Comment by maxkudla** [comment]
The problem is still actual

http://catamphetamine.github.io/react-phone-number-input/

Reproduce step

1. Find **Native country <select/>** section
2. Type correct phone number so country was selected
3. Remove phone number - **country is still selected**
4. Type other phone number - value is started from **selected country code**

**Comment by maxkudla** [comment]
It seems like next changes should works

```
onChange = (_input) =>
	{
		const {...} = this.props

		const {...} = parseInput(...)

		this.setState
		({
			parsed_input: input,
			value,
			country: input === "" ? undefined : country
		},
		...
	}
```

**Comment by maxkudla** [comment]
And currently, with this error, value and input is out of sync
![image](https://user-images.githubusercontent.com/9202221/54991636-0a833280-4fc6-11e9-9d3e-955fe1aa7ca2.png)

**Comment by catamphetamine** [comment]
@maxkudla Works for me.

**Comment by maxkudla** [comment]
Before remove
![image](https://user-images.githubusercontent.com/9202221/54994424-e5de8900-4fcc-11e9-9783-d936585782df.png)

After remove
![image](https://user-images.githubusercontent.com/9202221/54994439-f0008780-4fcc-11e9-9ef5-1346120fe2c1.png)

@catamphetamine Is it correct behavior?

**Comment by catamphetamine** [comment]
@maxkudla It's not clear from the screenshots what issue are you experiencing. You can create an animated GIF maybe.

**Comment by maxkudla** [comment]
![image](https://im5.ezgif.com/tmp/ezgif-5-df1f211197bd.gif)

**Comment by maxkudla** [comment]
Lets imaging we use showCountrySelect = false... 

![image](https://im5.ezgif.com/tmp/ezgif-5-ad60003f3ad0.gif)

**Comment by catamphetamine** [comment]
@maxkudla Oh, now I see what you mean.
Well, yeah, it's how it's designed to be.
Maybe we could check `if (!showCountrySelect) { always formatAsInternational() }`.
But why don't you use `basic-input` instead?
https://github.com/catamphetamine/react-phone-number-input#without-country-select

**Comment by maxkudla** [comment]
There are no features like limitMaxLength, formatAsInternational and so on...  and it works just when country is provided

> Maybe we could check `if (!showCountrySelect) { always formatAsInternational() }`.
or when `international` prop is true

**Comment by catamphetamine** [comment]
> There are no features like limitMaxLength, formatAsInternational and so on... and it works just when country is provided

I can add support for `country={undefined}` to it and `limitMaxLength` maybe.
Maybe sometime this week.

**Comment by catamphetamine** [comment]
Actually, I won't add `limitMaxLength` there to keep it simple.
Well, I can add a property to `PhoneInput` then.
Maybe something like `formatInternational={true}`.

**Comment by maxkudla** [comment]
Maybe it will be reasonable to clear country when `showCountrySelect === true && parsed_input .value === ""` ? I think it could solve the problem

**Comment by catamphetamine** [comment]
@maxkudla The new version (released in past months) exports a "without country select" component that is customizable, so I guess `showCountrySelect={false}` is no longer relevant.
