### ISSUE TITLE
Pass country as props so it defaults on componentDidMount()

### ISSUE THREAD

**Issue by MichaelA59** [catamphetamine/react-phone-number-input#138]
I have a need to save both a user's inputted phone number along with their country. I snag the country and store it in the state of the component rendering `PhoneInput` by using 

```javascript
onCountryChange={new_country => this.setState({ employee_country: new_country })}
```

This works, and I then persist this to the DB and am able to retrieve it when loading again. I thought that by including, `country={this.state.employee_country}` would allow for `PhoneInut` to load up with the `flag` and `country-code` of the country passed as props here, but it simply defaults, _always_, to `International`.

Any idea how to fix this? Below is an exact copy of how I am rendering the component
```javascript
<PhoneInput
  name="employee_phone"
  placeholder="Phone Number"
  value={this.state.employee_phone}
  onChange={value => this.setState({ employee_phone: value })}
  displayInitialValueAsLocalNumber={true}
  country={this.state.employee_country}
  onCountryChange={new_country => this.setState({ employee_country: new_country })}
/>

**Comment by catamphetamine** [comment]
If there already is any non-null `value` set for `PhoneInput` then it won't change its country.
Try this:

```js
<PhoneInput
  country="RU"
  ...
/>
```

It will pre-select Russian flag.

If you're setting country after the component has been created with some non-null `value` then it won't work.

One workaround would be using `key={`employee_phone_${default_country}`}` for re-creating `PhoneInput` when `default_country` has been loaded from database.

**Comment by MichaelA59** [comment]
Yes! It was the `null` value which was causing the issue. Thank you!

**Comment by catamphetamine** [comment]
Can you explain it in more detail?
Perhaps you found a bug which should be fixed?

`null` should be working same as `undefined` and the library should not differentiate between them.
There is some special logic for handling `null`s specifically inside, but perhaps you found an edge-case where it breaks?

**Comment by catamphetamine** [comment]
For your code:

```js
country={this.state.employee_country ? this.state.employee_country : 'US'}
```

It means "set country to US by default, and then if `employee_country` is set later with no `value` having been set yet then change the selected country to `employee_country`".
