### ISSUE TITLE
displayInitialValueAsLocalNumber only working on willMount()

### ISSUE THREAD

**Issue by MichaelA59** [catamphetamine/react-phone-number-input#144]
Best Case:

I would like the actual country code and `+` sign visible in the input field even after selecting a country from the dropdown. Would look like `[Flag] +1(413)334-1212` 

Settle For:

After successfully submitting a valid phone number, the component should re-render in internation standard like above, displaying the country code in the input field.

Using `displayInitialValueAsLocalNumber={false}` works, but only if I refresh the page. I would like this to occur if the component re-renders. I was able to force a re-render of the component which renders `PhoneInput` but it does nothing. Any ideas?

**Comment by catamphetamine** [comment]
Not understand.
Provide screenshots along with explanation.

**Comment by MichaelA59** [comment]
Sure, so here is the sequence of events

<img width="610" alt="p1" src="https://user-images.githubusercontent.com/21009897/41490691-38defae8-70c3-11e8-874c-832af3ea4912.png">

^^ The user has chosen a country from the drop down and then inputed the phone number (local version without country code of course) and this is exactly what is displayed

<img width="636" alt="p2" src="https://user-images.githubusercontent.com/21009897/41490723-50cf8bfe-70c3-11e8-82e3-5ad6bef7f812.png">

Now, the new number has been saved and persisted to the DB and a re-render of the component which renders this input field has now occured. Despite the fact that the component has re-rendered AND the value of the field is in the international format of `+1 ...number...` it still only displayed it in a local format

<img width="597" alt="p3" src="https://user-images.githubusercontent.com/21009897/41490759-7f1b344a-70c3-11e8-9a46-5f9b892abe70.png">

Now, a hard refresh of the page has taken place and when it loads, it now displayed the phone number in the international format. 

What I want is, at least, for it to be displayed in the international format when saved (caused probably by some kind of props or state change) or even better yet, always display the international format at all times

**Comment by catamphetamine** [comment]
>  Despite the fact that the component has re-rendered AND the value of the field is in the international format of `+1 ...number...` it still only displayed it in a local format

Because the `PhoneInput` component didn't re-render.
Change the `value` if you want it to rerender, but in this case you can't.
So instead one could generate a new `key` for `PhoneInput` to force React to re-create the component.
Make sure though that you're only re-creating a new `key` on form submission and that it stays constant otherwise (to avoid performance hits, like `key={Math.random()}`).

> Now, a hard refresh of the page has taken place and when it loads, it now displayed the phone number in the international format.

Yes, because the `displayWhateverLocal` is `false`.

> What I want is, at least, for it to be displayed in the international format when saved (caused probably by some kind of props or state change)

Then generate a new `key` on save.

>  or even better yet, always display the international format at all times

That could be achieved.
E.g. here:

https://github.com/catamphetamine/react-phone-number-input/blob/4fe7039d3c715b118d77b84a510baaa7f7f679f6/source/PhoneInput.js#L410-L436

I could add another `else` which would do 

```js
else if (forceInternational)
{
  parsed_input = '+' + getCountryCallingCode(country) + parsed_input
}
```

Which one do you choose.

**Comment by MichaelA59** [comment]
I'm not sure if for the last option (it always displaying input in international format) you are asking me my preference on a new addition/feature addon you can do to the repo or if you're just asking which one I plan on using.

If it's the latter, I'm not sure how to use it. You're linking to the source code. Is it possible to get this effect by setting some kind of prop to be passed to the component?

**Comment by catamphetamine** [comment]
> I'm not sure if for the last option (it always displaying input in international format) you are asking me my preference on a new addition/feature addon you can do to the repo

I was asking whether you'd use a "forced international phone number format" feature.

But on second thought, a user might start inputting a phone number with a national prefix, and so it can't be forced to always be in international format.
It could be force-converted to international midways, after a user finishes inputting the first meaningful digit (after national prefixes), but that would result in bad user experience so I guess I won't be implementing such feature.

Then go for manually changing `key` if you want the component to re-render.

**Comment by asafigan** [comment]
I would use the force internatinal phone number feature. That is exactly what I would want!

**Comment by catamphetamine** [comment]
@asafigan 
> That is exactly what I would want!

Why?

**Comment by asafigan** [comment]
What I want is a component that allows force international format. The + is allows there (you can't delete it). When you select a country, it auto fills the country code. It start with a default country. This way the user know that they needs to input the international format. This is for an enterprise application focused on multi-national companies.

**Comment by catamphetamine** [comment]
@asafigan Well, I don't see any point in restricting the input format to just international because local numbers also work and are automatically converted to international `value`.

**Comment by asafigan** [comment]
With this you would just type the local number because the country code is pre filled. I think I should just build it myself rather than adding more complexity to this package.
