### ISSUE TITLE
understand +code and switch code automatically

### ISSUE THREAD

**Issue by a-x-** [catamphetamine/react-phone-number-input#149]
e.g. when I type +1 select country US automatically

**Comment by catamphetamine** [comment]
+1 is for the whole NANPA countries region

**Comment by a-x-** [comment]
When I type, for instance, `+7` selector does not respond me

**Comment by catamphetamine** [comment]
> When I type, for instance, +7 selector does not respond me

Clarify yourself

**Comment by a-x-** [comment]
I got my mistake right now.
+7 is not enough to detect country
I should input phone full number
