### ISSUE TITLE
w/o country selector option

### ISSUE THREAD

**Issue by a-x-** [catamphetamine/react-phone-number-input#150]

**Comment by catamphetamine** [comment]
`showCountrySelect={false}`

**Comment by a-x-** [comment]
Can you add documentation and/or live example for that use case?

**Comment by catamphetamine** [comment]
No, it's in the source code.
If I added it to docs then it would be too big.
The README needs to stay small.

**Comment by catamphetamine** [comment]
@a-x- I added a "without country select" component.
See the readme.
https://github.com/catamphetamine/react-phone-number-input/#without-country-select
