### ISSUE TITLE
Why do you deleting the pull requests?

### ISSUE THREAD

**Issue by altinukshini** [catamphetamine/react-phone-number-input#153]
I just made a pull request here to add Kosovo in the list of countries: https://github.com/cata.../react-phone-number-input/pull/152

Since the project is under MIT license, I assume everyone should be able and is welcome to contribute, right? Would you be kind enough to let me know why was my pull request deleted?

Thanks! :)

**Comment by catamphetamine** [comment]
Hello.
Yes, the reason your PR was declined is that we don't support Kosovo as an independent country in this library and it won't be.

**Comment by catamphetamine** [comment]
"XK" territory flag has been added to the flags repo:
https://github.com/lipis/flag-icon-css/pull/501
"XK" territory is also supported by Google's `libphonenumber`:
https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml
Therefore I added "XK" territory to the list of selectable territories in the phone number input component in `react-phone-number-input@2.3.7`.
