### ISSUE TITLE
Uncaught Error: Unknown country: International

### ISSUE THREAD

**Issue by rostero1** [catamphetamine/react-phone-number-input#161]
With `International` selected, type `+1234`, select another country, select `International`.

```
react-dom.js:144 Uncaught Error: Unknown country: International
    at t.default (getCountryCallingCode.js:11) 
```

This can be verified at http://catamphetamine.github.io/react-phone-number-input/

**Comment by catamphetamine** [comment]
Thx, released `react-phone-number-input@2.1.3`
