### ISSUE TITLE
Initial value won't load in redux-form.

### ISSUE THREAD

**Issue by kristijanhusak** [catamphetamine/react-phone-number-input#162]
Hi,

I'm using this together with redux-form v6, and i cannot make it load initial values:

I first tried this, as suggested in docs:
```jsx
import Phone from 'react-phone-number-input'
import React from 'react';
import { Field } from 'redux-form';
import 'react-phone-number-input/style.css';

export default class MyPhoneInput extends React.Component {
	render() {
    	return (<Field name={props.name} component={Phone} />)
	}
}
```

But once i select a country from dropdown, i get error in console:
![error](https://i.imgur.com/GB4VzqS.png)

So i tried wrapping it myself for redux-form like this:
```jsx
import Phone from 'react-phone-number-input'
import React from 'react';
import { Field } from 'redux-form';
import 'react-phone-number-input/style.css';

export default class MyPhoneInput extends React.Component {
  constructor(props) {
    super(props);
    this.fieldInput = this.setupInput();
  }

  setupInput() {
    return (field) => {
      return (
        <Phone {...field.input} />
      );
    };
  }

  render() {
	return (<Field name={props.name} component={this.fieldInput} />)
  }
}

```

This made it work on inputing. I could properly select a country,enter the phone number, and pass it down to API in proper format. So far so good.

Once i load the same redux-form, with initialValues passed in, Nothing is prepopulated in the input, no country and no number. I console logged `field.input` and it properly contains all the events (onChange, onBlur, etc), and has a `value` property that is a valid number (+441632960293). All other inputs that i have are properly populated.

React version: 15.6.1
Redux version: 5.0.5
Redux-form version: 6.8.0

Edit: Looks like the country is properly preselected, but the number input is empty.

**Comment by catamphetamine** [comment]
The error means that the phone input wasn't supplied the `onChange` function which is what `<Field/>` was supposed to do.

I didn't ever use this component with `redux-form`.
If you make up a simple repo then I might have a look.

**Comment by kristijanhusak** [comment]
@catamphetamine here it is https://github.com/kristijanhusak/react-phone-input-test-repo

Clone it, run `npm run fast-start`. I used some shitty react redux app cli, but it does the trick. So i passed same phone number on two different fields, one is this phone number input, and another is just default input.

**Comment by catamphetamine** [comment]
Thanks.
Had a lot of [refactoring and fixing for `libphonenumber-js`](https://github.com/catamphetamine/libphonenumber-js/issues/232) today, so maybe tomorrow.

**Comment by catamphetamine** [comment]
Status update: had to do some work today on my job.
Now I'm going to the city.
Will come back today's late evening and will look at your sample project.

**Comment by catamphetamine** [comment]
So, the reason `onChange` wasn't passed to the component is that `<Field/>` doesn't pass it and instead it passes only `input: { value, onChange }` and `meta: { ... }` object properties.
https://redux-form.com/6.0.0-rc.4/docs/api/field.md/
Therefore, you'll have to wrap this component in a special `ReduxFormPhoneInput` wrapper like this:

```js
function ReduxFormPhoneInput({ input: { value, onChange }, meta }) {
  return (
    <Phone value={value} onChange={onChange}/>
  )
}
```

**Comment by kristijanhusak** [comment]
@catamphetamine I tried that this way:
```js
function ReduxFormPhoneInput({ input }) {
  return (
    <Phone {...input }/>
  )
}
```

Basically the same thing, just spread whole input content to Phone component. That didn't work out also. Did it work for you?

**Comment by catamphetamine** [comment]
It does:

![image](https://user-images.githubusercontent.com/477167/43229981-47bae1e6-906f-11e8-9894-523928b67588.png)

**Comment by kristijanhusak** [comment]
Can you give it a try with spreading the input? Maybe some other on event messes uo things.

**Comment by catamphetamine** [comment]
![image](https://user-images.githubusercontent.com/477167/43230052-91d79346-906f-11e8-850d-71c59e025ec9.png)

**Comment by kristijanhusak** [comment]
Does it properly populate?

**Comment by catamphetamine** [comment]
Check yourself

**Comment by kristijanhusak** [comment]
I'll look into it in the morning. Thanks for checking it out so fast.

**Comment by catamphetamine** [comment]
Well, the reason is `"react": "^16.2.0",` and this component requires `react >= 16.3.0` in order for `getDerivedStateFromProps` to even get called.
The requirement is in `package.json` but I guess people don't look there anyway.

I removed support for older React recently, for `react-responsive-ui`, but I guess there's no reason to do so since it's not the default flavour of the component (native is).
I think I'll add support for older React back.
And I also rewrote `react-responsive-ui` so now it all works even on React 15.

Released `react-phone-number-input@2.1.5`, works with older React (>= 15.3.0 for `PureComponent`).
Test it tomorrow in your project.

**Comment by kristijanhusak** [comment]
Thanks, it does work. But i noticed that using `displayInitialValueAsLocalNumber` does not work, it always populates international number.

**Comment by kristijanhusak** [comment]
@catamphetamine sorry, it works, number is not valid so that's why it didn't format it. Thank you very much!

**Comment by nguyenhuykma96** [comment]
@catamphetamine thanks U very much!
