### ISSUE TITLE
How to Basic input keeps caret whenever edit at the middle.

### ISSUE THREAD

**Issue by OscarBengtsson** [catamphetamine/react-phone-number-input#164]
You know, the caret jumps to the end of input when you edit at the middle of the input.
I saw the comment it's because of avoiding Android caret issues.

Is there any way to keep caret with Basic Input?

http://dimafeldman.com/js/maintain-cursor-position-after-changing-an-input-value-programatically/

**Comment by catamphetamine** [comment]
There's no way because it's meant to be the simplest input.
Use "Smart Input" for smart caret positioning (previously had some issues with Android).

```js
import SmartInput from 'react-phone-number-input/smart-input'

<PhoneInput
	inputComponent={ SmartInput }
	placeholder="Enter phone number"
	value={ this.state.value }
	onChange={ value => this.setState({ value }) }/>
```
