### ISSUE TITLE
Country Props not getting updated properly.

### ISSUE THREAD

**Issue by Subha** [catamphetamine/react-phone-number-input#165]
Hi,

Thank you for your time looking into this issue. 
https://github.com/catamphetamine/react-phone-number-input/issues/163.

Let me explain the issue that we are facing locally. 
Country Code **AI is for Anguilla**

```
import Phone from 'react-phone-number-input';
**const countryVal = "AI";**
**phoneVal = "+1 2464310179"**

<Phone
            {...customProps}
            type={this.useDevicePicker ? 'tel' : 'text'}
            placeholder={this.props.placeholder ? this.props.placeholder : `${FormatHelper.formatMessage('@@PhoneNumber')}`}
            country={countryVal}
            onCountryChange={this.countryChange}
            value={phoneVal}
            nativeExpanded={this.useDevicePicker}
            disabled={disabled}
            international={false}
            onChange={(phoneComponent) => this.setState({ phone: phoneComponent })}
            onBlur={this.handleBlur}
          />
```

What should I expect when I pass the country and Value property to the component?
**Country Flag set to AI with the phone number as "+1 2464310179"?**

But from the below snapshot you would see I am getting the country flag set to Barbados. I agree the country code for both Anguilla and Barbados are same. 
But can we some home overrwrite the country flag if the country props is already set?

![screen shot 2018-07-26 at 12 05 56 pm](https://user-images.githubusercontent.com/12513265/43274193-783f9944-90cc-11e8-84f0-746bf74ca697.png)

Thank you, really appreciate your time.

**Comment by catamphetamine** [comment]
> What should I expect when I pass the country and Value property to the component?

The `value` is set, and the `country` is set if there is no `value`.

So, the behaviour is as intended.
