### ISSUE TITLE
Documentation addition request: onCountryChange

### ISSUE THREAD

**Issue by lovebes** [catamphetamine/react-phone-number-input#166]
Awesome package!

Can you write something about props.onCountryChange function?
I read into the code and realized I could use that one as callback hook.

**Comment by catamphetamine** [comment]
Well, there was a man who asked for the hook and his use case was that they stored both `value` and `country` in the database and he wanted the `country` the user selected and not what `libphonenumber-js` `parseNumber()` gave him.
I'd say that's a pretty rare and extreme use case no one's likely ever gonna have.

**Comment by catamphetamine** [comment]
Basically, it's what it's called: `onCountryChange`, i.e. it's called on "country flag change".
