### ISSUE TITLE
Custom countries sorting

### ISSUE THREAD

**Issue by kristijanhusak** [catamphetamine/react-phone-number-input#167]
Is there a way to use custom sort function for countries in dropdown without doing everything custom? 
If not, can we add a prop to the phone input that would accept a sorting function?

**Comment by catamphetamine** [comment]
Why would you want that?

**Comment by kristijanhusak** [comment]
Client from US requests to have certain countries first in list (US, CA, UK).

**Comment by catamphetamine** [comment]
And how would you like those be sorted?

**Comment by kristijanhusak** [comment]
I'd move data around in that function as i want it, and return it to be used. Basically just a function that wraps the options.

**Comment by catamphetamine** [comment]
How exactly do you want those countries be sorted?

**Comment by kristijanhusak** [comment]
1. US
2. CA
3. UK
rest: Doesn't matter, can be alphabetically.

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@2.1.10`.


```js
transformCountrySelectOptions={(options) => {
	// Find the position of the "United States" option.
	const indexOfUSA = options.indexOf(options.filter(option => option.value === 'US')[0])
	// Get "United States" option.
	const USA = options[indexOfUSA]
	// Remove "United States" option from its default position.
	options.splice(indexOfUSA, 1)
	// Add a divider (separator) line under "United States" option.
	options.unshift({
		disabled: true,
		style: { fontSize: '1px', background: 'black' }
		label: ' '
	})
	// Add "United States" option on top.
	options.unshift(USA)
	// Return the transformed options.
	return options
}}
```

![image](https://user-images.githubusercontent.com/477167/43349210-0523a37e-9207-11e8-93f1-a3245deb8715.png)

**Comment by kristijanhusak** [comment]
Thanks a lot!

**Comment by catamphetamine** [comment]
(breaking change)

I changed it in the latest version.
`` property was removed, and `countryOptions` property was added.


```js
<PhoneInput
	placeholder="Enter phone number"
	countryOptions={["US", "CA", "AU", "|", "..."]}
	value={this.state.value_native}
	onChange={value => this.setState({ value_native: value })}/>
```

![image](https://user-images.githubusercontent.com/477167/43354103-6aef0774-924e-11e8-954f-4e4e80a31af4.png)

![image](https://user-images.githubusercontent.com/477167/43354248-403ac006-9251-11e8-84d5-322f7b451bbf.png)
