### ISSUE TITLE
Switching from country to international and back doesn't format a number

### ISSUE THREAD

**Issue by kristijanhusak** [catamphetamine/react-phone-number-input#168]
I'm using `displayInitialValueAsLocalNumber` option, and when i enter a number for certain country, it formats it properly. Now i switch the country to International, and then back to the same country it was before, it leaves the country code in the input. Is there a way to always strip the country code from input in this case?

Edit: Or is there a way maybe to remove the International option from dropdown completely?

**Comment by catamphetamine** [comment]
Fixed in `react-phone-number-input@2.1.12`.

**Comment by kristijanhusak** [comment]
That was fast, thanks a lot!
