### ISSUE TITLE
Unsafe Legacy Lifecycles

### ISSUE THREAD

**Issue by cstaber** [catamphetamine/react-phone-number-input#171]
I just installed and tried using and am getting this warning in the browser:

`main.js:5129 Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

PhoneNumberInput uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillMount
  componentWillReceiveProps

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
printWarning @ main.js:5129
main.js:5129 Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

InputBasic uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillMount
  componentWillReceiveProps

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks`

**Comment by catamphetamine** [comment]
https://github.com/catamphetamine/react-phone-number-input/issues/158
