### ISSUE TITLE
formatting is not working as specified in libphonenumber

### ISSUE THREAD

**Issue by msita143** [catamphetamine/react-phone-number-input#172]
Hi,
 I am using react-phone-number-input/basic-input as below :
``
Using app created via create-react-app with no webpack.
Now if I enter 20 the number formatted as (20 ) and caret goes after parenthesis. But as per below link 
https://libphonenumber.appspot.com/phonenumberparser?number=2071234567&country=US
the number should only if I type (207) 123-45.
Is there a way I can get the number formatted only after I type more then three char atleast.

Also when I try to use SmartInput as below:

`import PhoneInput from "react-phone-number-input/basic-input";

 import SmartInput from 'react-phone-number-input/smart-input'

        <PhoneInput

          inputComponent={SmartInput}

          className="react-phone-number-input__input"
          country={region}
          smartCaret={ true }
          value={this.state.mobileNumber}
          placeholder={this.props.intl.formatMessage(messages.phonePlaceholder)}
          onChange={this.onUpdatePhone}
          onBlur={event => this.onBlurValidate(event)}
        />
 `

I get warning and it doesn't work:

Warning: React does not recognize the `inputComponent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputcomponent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input (created by InputBasic)
    in InputBasic (created by InputBasicDefaultMetadata)
    in InputBasicDefaultMetadata (at PhoneNumber.js:54)
    in div (created by styled.div)
    in styled.div (at PhoneNumber.js:53)
    in PhoneNumber (created by InjectIntl(PhoneNumber))

Thanks
Manish

**Comment by msita143** [comment]
Here is how it looksl ike after I enter only two char
![image](https://user-images.githubusercontent.com/17054088/43564362-48552c6c-95db-11e8-829d-a02aa6a2e3f2.png)
which we don't want.

**Comment by catamphetamine** [comment]
Format the code appropriately.

**Comment by msita143** [comment]
What does it mean?

**Comment by msita143** [comment]
Check it now.
Though as I am saying it is not the code it is the way you guys use "As You Type" formatter.
Just asking if you have any work around for my request
Thanks
Manish

**Comment by msita143** [comment]
@catamphetamine : Any help on my above comment?
Thanks

**Comment by msita143** [comment]
See in demo parenthesis appears as I type two digits:
![image](https://user-images.githubusercontent.com/17054088/43607919-98f2d588-9654-11e8-9705-4bcffe26e0ec.png)

Please help me with this as we don't want to format until user enter 6 digits and if possible to add smart caret

**Comment by catamphetamine** [comment]
> Is there a way I can get the number formatted only after I type more then three char atleast.

I see what you mean.
Indeed, it looks confusing with `smartCaret={false}` option.
It looked right when `smartCaret={true}` was present in previous releases.
I guess it should be changed somehow.
Not simply ignoring until 3 digits but something more intelligent.
Maybe not inserting the closing parenthesis or something.
It's not a fast decision.

**Comment by msita143** [comment]
@catamphetamine : Now I am a bit confused. 
Is there a way I can change the behaviour  of parenthesis (should not appear after typing two digits) as I need submit my code or it will take time.

**Comment by catamphetamine** [comment]
It will take time.

**Comment by msita143** [comment]
oh ok. How long will it take.
else I need to look into  use other lib for fix yrs locally.

Thanks

**Comment by catamphetamine** [comment]
Look at other lib

**Comment by msita143** [comment]
gr8 response.
thanks
