### ISSUE TITLE
How to add custom countries

### ISSUE THREAD

**Issue by ifeanyidavid** [catamphetamine/react-phone-number-input#173]
Is there a way to render custom countries?

**Comment by catamphetamine** [comment]
Provide more details

**Comment by ifeanyidavid** [comment]
I want to render an array of specific countries instead of all of them.

**Comment by catamphetamine** [comment]
It's in the docs.

**Comment by ifeanyidavid** [comment]
Can we post a link to where it was documented. Thanks.

**Comment by catamphetamine** [comment]
https://github.com/catamphetamine/react-phone-number-input/

**Comment by catamphetamine** [comment]
See the "API" section.

**Comment by ifeanyidavid** [comment]
Oh great. thanks.
