### ISSUE TITLE
Can't focus custom input element when country is selected

### ISSUE THREAD

**Issue by kasparsuvi1** [catamphetamine/react-phone-number-input#174]
Hello.

Firstly nice job on the library!

I have problem to use my custom input element with inputComponent property. Everything works as expected until country is selected. I will get the next error: 
![image](https://user-images.githubusercontent.com/23498484/44854807-3af23080-ac72-11e8-9d05-242d74d1e7ab.png)

How i used input component: 
`
    InputComponent = (props: any) => {
        return <CustomInput {...props} />;
    };
`
`
    public render() {
        return <PhoneInput inputComponent={this.InputComponent} {...this.props} />;
    }
`

And in my CustomInput i store reference to the input like that: 
`
    input: HTMLInputElement;
`
` focus = () => this.input.focus();`
`
    storeInput(ref: any) {
   return (this.input = ref);
    }
`
`  <input
       ref={(ref: any) => this.storeInput(ref)}
   />
`

Am i missing something?

**Comment by catamphetamine** [comment]
It says that there's no function `.focus` on the `inputComponent` class you're providing.
Make sure it's a class extending `React.Component` and that it has `focus()` instance method.

**Comment by kasparsuvi1** [comment]
CustomInput class:
`class CustomInput extends React.Component<ITextFieldProps, ITextFieldState> {`

Also it has focus function:
`focus = () => this.input.focus();`

But im not sure that other component can reach the focus function when it's just inside the CustomInput class.

**Comment by catamphetamine** [comment]
If you want you can debug it via console.log - see if focus method is
called.
