### ISSUE TITLE
Autocomplete does not pass validation

### ISSUE THREAD

**Issue by henrythe9th** [catamphetamine/react-phone-number-input#177]
Hi,

I noticed that when using Chrome mobile, if I use browser autocomplete to fill in the phone number, then the number formatting and validation is not applied to the value, and the field is invalid.

![image](https://user-images.githubusercontent.com/644176/44953008-0beae300-ae5b-11e8-90a8-3175405b1ff5.png)

Can you help advise?

Thanks,
Henry

**Comment by catamphetamine** [comment]
Post the code
