### ISSUE TITLE
Cannot modify the default country into select

### ISSUE THREAD

**Issue by meazou75** [catamphetamine/react-phone-number-input#178]
Hello !

When i try to modify the default value of the PhoneInput Select it's stay showing me first the International Flag and phone type

<img width="627" alt="capture d ecran 2018-09-03 a 22 57 02" src="https://user-images.githubusercontent.com/9728122/44995323-c1897380-afcc-11e8-8f82-8f7c5f070dae.png">

`<div className="form-group">
                 <PhoneInput
                            placeholder="Enter phone number"
                            value={this.state.phone}
                            country="FR"
                            countries={['FR']}
                            onChange={phone => this.setState({ phone })}
                        />
                    </div>`

Thanks for your help :)

**Comment by catamphetamine** [comment]
Not understand

**Comment by meazou75** [comment]
The doc say that if i want to display as defaultFlag for example the French Flag, i have to set in the props country="FR"

but when i do this it still show as default the Internationale Flag and when i set internationale=false nothing appears

**Comment by catamphetamine** [comment]
> The doc say that if i want to display as defaultFlag for example the French Flag, i have to set in the props country="FR"

See the demo.
http://catamphetamine.github.io/react-phone-number-input/
The demo works.
