### ISSUE TITLE
If you enter a value greater than mask length, the mask is corrupted!

### ISSUE THREAD

**Issue by ahmetkuslular** [catamphetamine/react-phone-number-input#182]
<img width="330" alt="screen shot 2018-09-11 at 10 53 48" src="https://user-images.githubusercontent.com/17436691/45346074-d22f8000-b5b0-11e8-9b88-3e9ff8542476.png">

The mask is not working properly. can not detect the length. If you enter a long value, the mask is corrupted. I need to prevent a larger value entry than the mask length.

**Comment by catamphetamine** [comment]
The mask is working as intended.
This component won't restrict a user from inputting a number that's considered too long.
The purpose of this component is not restricting the phone number being input.
It just formats the input when appropriate.
One can add their own validation on top of that if required.

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@2.2.4` with `limitMaxLength` boolean property.
