### ISSUE TITLE
Unable to custom sort the international option to the top anymore

### ISSUE THREAD

**Issue by tomfin46** [catamphetamine/react-phone-number-input#183]
With the changes to introduce the validation as part of solving https://github.com/catamphetamine/react-phone-number-input/issues/179 (https://github.com/catamphetamine/react-phone-number-input/commit/e2a534461a81a530d8c82b2de7ca607240c53625) it seems I'm unable to custom sort the international option to the top with the `coutryOptions` prop anymore.

Previously (when using version 2.2.1) I could specify `undefined` in the prop to place the international option where I wanted e.g. `countryOptions={[undefined, 'GB', 'US', '...']}` and this would give me International, United Kingdom, United States and then everything else in my list.

With version 2.2.3 onwards having `undefined` in the `countryOptions` prop obviously fails the validation as that is not going to exist in google's metadata and thus throws the error.

Was what I was doing unsupported behaviour and just happened to work out for me or should I have been accomplishing the custom sorting of the international option differently? or should the new validation be updated to allow the case of `undefined` and thus skip checking the metadata for that option?

Happy to help out with a PR to adjust/fix this!

**Comment by catamphetamine** [comment]
Oh, didn't even think about that one.
Ok, thx, I'll fix it.

**Comment by tomfin46** [comment]
Okay sweet, thanks for such a quick reply 👍

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@2.2.5`.
