### ISSUE TITLE
Export all components from the index file.

### ISSUE THREAD

**Issue by Huulivoide** [catamphetamine/react-phone-number-input#185]
Right now only `PhoneInputNativeDefaultMetadata` and `PhoneInput` are exported from the index file. If one wishes, for example, to use the react-responsive-ui version one has to import that from another file.

This can lead to same sort of double imports as with bug report #184 if one is not careful.

If one is using ES6 import and blindly follows the documentation one might end up with both ES6 and commonjs versions of the component included in the bundle.

I for example am using the native input versions on mobile and the responsive versions on desktop. So initially I had the following imports:
```js
import NativePhone from 'react-phone-number-input';
import ReactivePhone from 'react-phone-number-input/react-responsive-ui';
```

Which lead to 2 versions of react-phone-number-input getting included in my bundle.
To prevent that one actually has to do:
```js
import NativePhone from 'react-phone-number-input';
import ReactivePhone from 'react-phone-number-input/modules/PhoneInputReactResponsiveUIDefaultMetadata';
```

If all, or at least the ones meant for public usage, react components were exported from the index file, there would be no chance of accidentally importing the wrong version of the files.

**Comment by catamphetamine** [comment]
> If one is using ES6 import and blindly follows the documentation one might end up with both ES6 and commonjs versions of the component included in the bundle.

Indeed.
In this case it's more messy than with `libphonenumber-js`: it's not just `index` and `/custom` but there are many secondary exports like `/react-responsive-ui` and such.

> If all, or at least the ones meant for public usage, react components were exported from the index file, there would be no chance of accidentally importing the wrong version of the files.

True.
I tried placing everything in a single file first, but then I found out that Webpack didn't actually "tree shake" unused dependencies.

E.g. 

```js
import PhoneInputNative from 'react-phone-number-input`
```

would still bundle `react-responsive-ui` and would not "tree shake" it even if it's not imported.

Maybe something changed, I didn't check.
You could try adding `react-responsive-ui` export to `index.js` without `import`ing it in the app and see if your application bundle includes `react-responsive-ui`.
If it does then Webpack "tree shaking" is still broken.
If it doesn't then maybe Webpack "tree shaking" is fixed and we could export everything from ES6 `index.js` file (including `react-responsive-ui` component).
Not everyone uses Webpack: there are also Rollup and Parcel and maybe some others.
Relying on "tree shaking" would mean enforcing some extra requirement on users of this library.
But, maybe it would be better than having to hack around with ES5 exports.

**Comment by catamphetamine** [comment]
I used the `package.json` approach in sub-directories which seems to kinda work.
There are now various sub-packages like `react-phone-number-input/react-responsive-ui` and such which export both ES6 and CommonJS.
Closing.

**Comment by SunilPadikarManjunatha** [comment]
jk
