### ISSUE TITLE
Module not found..

### ISSUE THREAD

**Issue by dwojcik96** [catamphetamine/react-phone-number-input#188]
Hi,
I forked your repo, add one, very important condition and tried implemented it to my project.
Unfortunately, I have a problem when I'm using ```yarn && yarn setup```.
It looks like modules catalog is not creating automatically. If I manually update submodule and install this one dependency, the error disappears.

<img width="948" alt="zrzut ekranu 2018-09-24 o 15 04 47" src="https://user-images.githubusercontent.com/22615841/45954056-3f5cff80-c00c-11e8-9321-bf63371f4c4e.png">

**Comment by catamphetamine** [comment]
Did you run `npm run build`
It creates `modules` and `commonjs`.

**Comment by dwojcik96** [comment]
@catamphetamine what you think about it? https://github.com/catamphetamine/react-phone-number-input/pull/187

**Comment by catamphetamine** [comment]
I'm closing this.
If you still have issues with your setup then post comments here.
