### ISSUE TITLE
Provide focus style customization

### ISSUE THREAD

**Issue by chris-verclytte** [catamphetamine/react-phone-number-input#189]
Hello,

What would you think about adding some way to customize the focus state of the component ? 
I have not found any hook that would allow to do this currently. 
What I am willing to do is applying a common border for both country selector and phone input but currently when you focus phone input, only this one is focused and there is no way to hook on a CSS className or other mechanism to customize this.
Here is a preview of what I get: 
<img width="221" alt="capture d ecran 2018-09-30 a 12 45 00" src="https://user-images.githubusercontent.com/1611574/46256715-c992e100-c4ae-11e8-9247-45324946d54e.png">

I think the easier way would be to put a 'react-phone-number-input--focused' className on the root component ([here](https://github.com/catamphetamine/react-phone-number-input/blob/master/source/PhoneInput.js#L697)), this would allow to apply focus state on both country selector and phone input. 
Another solution would be to provide ref hooks for input and select but I think this is trickier. 

What do you think ? I can do a PR if this seems legit.

**Comment by catamphetamine** [comment]
Try setting `position: absolute` for country select and then move it above the `<input/>` on its left side and then add `padding-left` to the `<input/>`.

**Comment by chris-verclytte** [comment]
Yeah sure, it would be possible to do it CSS-way, but I think this could belong to the library as it is pretty common case. Here the country selector is like an adornment on an input field, then I think it makes sense to say that the whole component is focused (with the className) when the phone input is focused, isn't it ?

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@2.2.9`
