### ISSUE TITLE
[libphonenumber-js] `metadata` argument not passed

### ISSUE THREAD

**Issue by nguyenman999** [catamphetamine/react-phone-number-input#193]
I'm trying to use custom version of phone-input but got the error 

> [libphonenumber-js] `metadata` argument not passed 

when 
`import PhoneInput from 'react-phone-number-input/custom'`

My code is:
```
import React from 'react'
import PropTypes from 'prop-types'
import 'react-phone-number-input/style.css'
import PhoneInput from 'react-phone-number-input/custom'
import styles from './profile.scss'

const Profile = props => (
  <div className={styles.profile}>
    <PhoneInput
      placeholder="Enter phone number"
      countrySelectComponent={<div />}
      onChange={(value) => {
        // console.log(value)
      }}
    />
  </div>
)
```
BTW: Could you pls add a sample how to custom phone input?

**Comment by catamphetamine** [comment]
Yes, because you didn't pass `metadata` property, as it says.

> Could you pls add a sample how to custom phone input?

https://github.com/catamphetamine/react-phone-number-input/blob/master/source/PhoneInputNativeDefaultMetadata.js
