### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ifeanyidavid** [catamphetamine/react-phone-number-input#199]
I get this error when I try to load my application when using the library.

`import PhoneInput from 'react-phone-number-input';`
`require('react-phone-number-input/style.css');`

`<PhoneInput placeholder="Enter phone number" value={this.state.phone} onChange={phone => this.setState({ phone })} />`

**Comment by catamphetamine** [comment]
There's no `window` in this library.
You can provide a minimal simple project illustrating the issue which would throw an error when `react-phone-number-input` is used on a page and which would not throw the error when `react-phone-number-input` is commented out.

**Comment by ifeanyidavid** [comment]
Here is the [codesandbox url](https://codesandbox.io/s/2v1vw58k3n). Oddly it works!
Perhaps it's my dev environment. I'll create a project a project from scratch without any extraneous dependencies and test it again.

**Comment by catamphetamine** [comment]
Well, `window` is `undefined` on server side because it's always defined on client side by definition so you can't get the error in any in-browser sandbox.

**Comment by ifeanyidavid** [comment]
Well that might explain it. I am using NextJS for development which is server side React.
Got any idea of how I can resolve this with NextJS.
