### ISSUE TITLE
onCountryChange doesn't fire when country prop is changed

### ISSUE THREAD

**Issue by klase** [catamphetamine/react-phone-number-input#200]
onCountryChanged only fires when the country select dropdown is manually changed or when typing, not when the country is changed as a result of updating the country prop on the PhoneInput itself.

**Comment by catamphetamine** [comment]
Provide a demo illustrating the issue

**Comment by klase** [comment]
https://codesandbox.io/s/x9v0x5jj0w

If you click the button the default country changes as expected but the onCountryChanged event is not dispatched unless you manually type into the textbox or change the select. 

My use case is reflecting the correct phone number format in the text input placeholder when users change locale on my site.

**Comment by catamphetamine** [comment]
@klase 
So I finally had some time during this busy week to look at the bug and rewrote how `onCountryChange` is called.
Released `react-phone-number-input@2.2.15` with the fix.

**Comment by klase** [comment]
Thanks @catamphetamine
