### ISSUE TITLE
Add country code in phone number input on country select

### ISSUE THREAD

**Issue by Jauny** [catamphetamine/react-phone-number-input#201]
Hi!

First, thanks for the library, it's very useful! 

We've notice that users still get confused after choosing a country flag, so we'd like to automatically add the country code in the phone number input as a user selects a country from the country drop down.

It would go as follow;
- load the page. Default country is 'US', so the US flag is selected and the phone input has "+1" in.
- Select a different country, say France, the phone input changes to "+33".
- Ideally, if use has started entered their numbers (say the input is "+33 6 11") and update the country, the country code updates keeping the correct number (change from FR to NL and have "+31 6 11").

Do you know if there is a way to do this already? I've looked at the source code, and seen that there is a `onCountryChange` callback we can pass, but only the country string ('US', 'FR') is passed to the callback.

- Since the country code appears already as the user starts typing, might not be a huge option to add to have the country code added directly?
- If not possible, is there a package available to map a country string to a country code? ('US' => +1, 'FR' => +33, etc) With this, we could use the onCountryChange callback and populate the input manually.

Thanks a lot!

**Comment by catamphetamine** [comment]
@Jauny 

Hi.

> Do you know if there is a way to do this already? 

There isn't.

> Since the country code appears already as the user starts typing, might not be a huge option to add to have the country code added directly?

I don't see why would anyone need the feature you're describing.

> is there a package available to map a country string to a country code? 

See `libphonenumber-js` `getCountryCallingCode()`.

**Comment by catamphetamine** [comment]
Perhaps like this:

```js
import { getCountryCallingCode } from 'react-phone-number-input/libphonenumber'

getCountryCallingCode('RU') === '7'
getCountryCallingCode('IL') === '972'
```

**Comment by Jauny** [comment]
Hey @catamphetamine thanks a lot for the quick response. The solution seems to be what I was looking for, will play with that thanks :)

As for wondering why anyone would want that, this is a client request. They've said that according to what they've seen on their app, people get confused and the experience seems better with the code added in advance.

Cheers!
