### ISSUE TITLE
If you select a country and then enter a valid phone number (without the country code) the input does not format as that country

### ISSUE THREAD

**Issue by jackmarketon** [catamphetamine/react-phone-number-input#202]
Select Austria, and enter a valid phone number, it looks like `2342342342234` (and return value is `+432342342342234`)

If I enter the entire phone number: `+432342342342234` it formats it as `+43 2342 342342234`

**Comment by catamphetamine** [comment]
Follow the procedure: https://github.com/catamphetamine/react-phone-number-input#bug-reporting
