### ISSUE TITLE
Optionally allow to use CSS Modules for custom styling

### ISSUE THREAD

**Issue by dacevedo12** [catamphetamine/react-phone-number-input#203]
Thanks for this component, I'm currently taking a look at it for using it in our project and i gotta say that i've found it really useful.

I'd be great if you allow to pass custom styles as props instead of having the css file import as the only option

**Comment by catamphetamine** [comment]
> I'd be great if you allow to pass custom styles as props instead of having the css file import as the only option

Explain with examples.
Which styles exactly would you want?

**Comment by dacevedo12** [comment]
I'm closing this as I clearly didn't read the documentation with enough detail. Sorry, and again, great work with this component!
