### ISSUE TITLE
show country code in input box by default 

### ISSUE THREAD

**Issue by felixsungit** [catamphetamine/react-phone-number-input#204]
Is there a way to show the country code in the input by default. For example, if the country is selected as UK, there will be +44 defaultly populated in the input and when the user switch to USA the country code would get switched to +1 etc. we want to have it in a way where the user can see exactly what number they are typing (dont hide country code)

**Comment by catamphetamine** [comment]
No.

**Comment by felixsungit** [comment]
Can I request this feature to be added

**Comment by catamphetamine** [comment]
You can consult others who requested that type of feature.
https://github.com/catamphetamine/react-phone-number-input/issues/201
You can ask them whether they got that working.
I guess the idea was to define `onCountryChange(country)` property and then inside that function set `value` to do `if (!value) { onChange('+' + getCountryCallingCode(country)) }`

**Comment by felixsungit** [comment]
Thanks for the relpy thats what I was looking for
