### ISSUE TITLE
Failed prop type: Invalid prop `inputComponent`

### ISSUE THREAD

**Issue by gus3inov** [catamphetamine/react-phone-number-input#207]
```Warning: Failed prop type: Invalid prop `inputComponent` of type `function` supplied to `ReactInput`, expected `string`.```
By using 
```javascript
  <SmartInput
       label={label}
       type={type}
       info={isError ? errorText : info}
       autoFocus={autofocus}
       placeholder={placeholder}
       disabled={disabled}
       required={required}
       status={status}
       errorText={errorText}
       onChange={(e) => {
             input.onChange(e);
             onChange(e);
       }}
       value={input.value}
       {...input}
       inputComponent={Input}
    />
```
How can i customize component with string type?

**Comment by catamphetamine** [comment]
Non-string `inputComponent` had a bug so only string is allowed.
You can't customize it with a string though.
It was just left as-is, so don't pay attention to that property.
https://github.com/catamphetamine/input-format/blob/bc9c633deb3b3c128ec153ebcf459a9c5f4c8e71/source/ReactInput.js#L79-L84
