### ISSUE TITLE
Change Format

### ISSUE THREAD

**Issue by eugenio-caicedo** [catamphetamine/react-phone-number-input#210]
I need to update the format, for example, Spain or Italy. How I do it?

**Comment by catamphetamine** [comment]
Not clear what you want.

**Comment by eugenio-caicedo** [comment]
Ok, I explain better. When I select the Spain flag and enter the phone number of this country in the textbox, the format is this: 604 22 43 07. But I need to update the format for display in this way: 604 22 4307 (for example).

**Comment by catamphetamine** [comment]
The format selection is based on Google's libphonenumber code.
If Google's demo formats a number in a certain way then this library will format it accordingly, with no alternatives.

**Comment by eugenio-caicedo** [comment]
I get it. Thanks.
