### ISSUE TITLE
Update (or remove?) react-dnd-* dependencies

### ISSUE THREAD

**Issue by rhys-vdw** [catamphetamine/react-phone-number-input#211]
Not strictly your problem, but the out of date dependencies caused some conflicts in our build. Info [here](https://github.com/yarnpkg/yarn/issues/6706#issuecomment-441485743). react-dnd is now up to version 6. (These dependencies are coming from your other package https://github.com/catamphetamine/react-responsive-ui)

Although... Does this package even use react-dnd? Is it necessary to bundle it in with a phone number input?

**Comment by catamphetamine** [comment]
Oh, already version 6.
They're changing major versions rapidly, like four in a half-year.

> Although... Does this package even use react-dnd? Is it necessary to bundle it in with a phone number input?

This project only imports the required parts of `react-responsive-ui`.
Installing doesn't mean importing.

I'll update `react-dnd` in `react-responsive-ui`.

**Comment by catamphetamine** [comment]
First, `react-responsive-ui` was using v5, not v4.
Second, released `react-responsive-ui@0.14.65` which uses v6 now.
So re-install your dependencies.

**Comment by rhys-vdw** [comment]
Thanks. :) You might consider setting up greenskeeper on these repos.

**Comment by rhys-vdw** [comment]
Yeah, I know. We were laughing about that at the office. :) Thanks for the help, library's working a treat.
