### ISSUE TITLE
Can't disable text component only

### ISSUE THREAD

**Issue by chrismpalmer** [catamphetamine/react-phone-number-input#215]
Hello!

I use a keyboard that I build for a better look and feel. I need to disable the keyboard input but not the country selector.

The disable gets applied to both.

Thank you..

**Comment by chrismpalmer** [comment]
That is a fair question. The reason is I use a keyboard that I build dynamically. So I don't want the keyboard to come alive at all if the user taps the field.

**Comment by catamphetamine** [comment]
> So I don't want the keyboard to come alive at all if the user taps the field.

Is this some kind of a custom mobile keyboard somewhere on a phone or what?
It's still not clear what you're doing and why do you need to disable the keyboard input but not the country selector.

**Comment by chrismpalmer** [comment]
Yes its a custom keyboard on the form. As the user taps the custom keyboard the state appears in the PhoneInput. So I don't need traditional mobile keyboard input. If the user taps it mobile keyboard will come alive. However the user may want to change country... is this more clear?

**Comment by catamphetamine** [comment]
And how are you expanding your custom keyboard on focus?
If a field is `disabled` it can't be focused (in this case it's the phone input field).

**Comment by chrismpalmer** [comment]
I don't its permanent on the form.

**Comment by catamphetamine** [comment]
I don't understand how exactly do you show the custom keyboard when a user focuses on the phone input field.

**Comment by chrismpalmer** [comment]
![simulator screen shot - iphone x - 2018-11-29 at 10 06 56](https://user-images.githubusercontent.com/7710236/49242067-88d81b00-f3be-11e8-9caa-03c48f06a870.png)

**Comment by catamphetamine** [comment]
I see now.
So initially there's no focus.
If a user taps on the country select then it will show the country select.
The digital keyboard is always shown and it always updates the phone input value.

**Comment by catamphetamine** [comment]
I could introduce a new property called `disablePhoneInput`.
There's also another bug report: https://github.com/catamphetamine/react-phone-number-input/issues/216
After fixing that bug report today I would release a new version.

**Comment by chrismpalmer** [comment]
That would be very kind of you. It would help me a lot. Look forward to it.

**Comment by catamphetamine** [comment]
Published `react-phone-number-input@2.2.19`.
