### ISSUE TITLE
Country flag disappears when loading number not in list

### ISSUE THREAD

**Issue by danolsson** [catamphetamine/react-phone-number-input#216]
Hi, thanks for the great package!

I have an issue when loading a phone number which belongs to a country not listed in the `countries` prop.

Expected result:
When specifying which countries to display in the select dropdown, loading a phone number from a country not in the list should display the 'International' flag.

Actual result:
Loading a phone number from a country not in the select list still changes the country, and makes the flag disappear.

How I use the package:
```
 <PhoneInput
            value={props.value}
            country="SE"
            onChange={props.onChange}
            countries={["SE", "FI", "FR", "ES"]}
            displayInitialValueAsLocalNumber={true}
        />
```
If the value is set to, for example, a Russian phone number when the component loads, no flag will show up.

**Comment by catamphetamine** [comment]
Not clear what exactly are you experiencing.
You can create an example illustrating the issue (there are services like "jsfiddle" and alike).

**Comment by danolsson** [comment]
I'll try to explain it with images, might make it a bit more clear.

These are the countries I have enabled in the select:
![countrylist](https://user-images.githubusercontent.com/24700218/49275111-8fc46380-f47a-11e8-96a5-ace6ce56a2df.png)

When loading a page with a phone number from a country which is in the select the flag shows up properly:
![working](https://user-images.githubusercontent.com/24700218/49275148-a5d22400-f47a-11e8-835a-c6990bc9b5a8.png)

However, if I load a page with a phone number from a country not in the select (Thailand in this example) the flag disappears:
![not_working](https://user-images.githubusercontent.com/24700218/49275172-b97d8a80-f47a-11e8-9507-6d3707390553.png)

What I would like to happen is that instead of the flag disappearing because it's not an option in the select, the international option should be selected instead.

Please let me know if anything is still unclear!

**Comment by catamphetamine** [comment]
> When loading a page with a phone number from a country which is in the select the flag shows up properly:

Simplify your reproduction instructions.
Paste the code sample that illustrates an issue.
It's not clear what you mean by "when loading a page".
Set the initial `value` to something if you want it to be initialized.

**Comment by danolsson** [comment]
With loading a page I mean navigating to a component on my site where the PhoneInput is located.

`value` is initialized to a phone number and is what's causing the issue I'm experiencing. If the initialized phone number is from a country which I haven't specified in my `countries` prop then the flag disappears.

Here's the code of how I use the component:
```
<PhoneInput
    value={props.value}
    country="SE"
    onChange={props.onChange}
    inputClassName="form-control"
    countries={['SE', 'FI', 'ES', 'FR']}
 />
```

**Comment by catamphetamine** [comment]
Provide a code sample that would illustrate the issue without any other actions like navigating or selecting something.

**Comment by danolsson** [comment]
Here's a jsfiddle with the problem: https://jsfiddle.net/80zLmyg1/1/

It seems like there's a problem when the change happens from another component. This fiddle simulates my scenario where I get the value with redux which then updates the state.

**Comment by catamphetamine** [comment]
@danolsson 
That's why the fiddle was required.
Without it, everything works:

```js
<PhoneInput 
       value="+66812345678"
       onChange={() => {}}
       countries={['SE', 'FI', 'ES', 'FR']}
     />
```

But, if you set `value` in a timeout it stops working.
I'll fix it this week.

**Comment by danolsson** [comment]
@catamphetamine That's awesome, thank you!

**Comment by catamphetamine** [comment]
These were a couple of busy weeks.
Fixed in `react-phone-number-input@2.2.20`.
Fixed in 10 minutes.

**Comment by danolsson** [comment]
Awesome, thanks for the amazing work! Much appreciated.

**Comment by emcorder** [comment]
I'm using this library with Tailwindcss but country flags are not appeared at all.

**Comment by catamphetamine** [comment]
@emcorder Perhaps you're using version < 3.x
Otherwise, could be something else in your setup or in your app.
