### ISSUE TITLE
sourcemap warning in developer tools

### ISSUE THREAD

**Issue by dahvinchee** [catamphetamine/react-phone-number-input#217]
I am seeing a warning in chrome developer tools console. Everything works fine, but is there some way to use this library without this warning appearing? 
<img width="860" alt="capture" src="https://user-images.githubusercontent.com/37880917/49759434-b317bb80-fc8f-11e8-9a82-20825f3ffb13.PNG">

**Comment by catamphetamine** [comment]
Hello.
I don't know what is this about.
And I'm not an expert in source maps.
