### ISSUE TITLE
Custom country <select/> - Filtering select

### ISSUE THREAD

**Issue by Subha** [catamphetamine/react-phone-number-input#218]
Appreciate all your effort in updating the packages and documenting everything.
I just updated my application to use the major version 2.2.X. 

As per the document I am using the custom country <select/> 

` import PhoneInput from 'react-phone-number-input/react-responsive-ui' `

When I open the country dropdown I could not type or search the country that I need to select and i have to scroll all the way to choose the country from the country list. 

       **For example if the default country is United Kingdom and I want to change it to India I would like to type "I" so it takes me to the countries that starts with I.** 

Is there any property or a way to have this feature?

**Comment by catamphetamine** [comment]
Hello.
Originally I did have an autocomplete for the custom select (version 1.x).
Now it's just select.
I was thinking whether I should add typing to that select or not.
Autocomplete doesn't seem like a good solution.
It's bulky and other components use simple selects too.
Example: https://intl-tel-input.com/
Perhaps I'll just add the typing feature to the select then.

**Comment by Subha** [comment]
I agree. Yes you had the autocomplete earlier. Adding the typing feature will work too I guess. Thank you for looking at it.

**Comment by Subha** [comment]
Did you get a chance to look at this? Any idea when I would get the fix? Thank you

**Comment by catamphetamine** [comment]
@Subha 
I probably will be implementing the feature but there are no time estimates.

**Comment by catamphetamine** [comment]
Added the typing feature to the `react-responsive-ui` country select.
The demo has been updated.
The package version got updated from `2.2.x` to `2.3.0`.
There was a big internal refactoring so if you'll be updating to `2.3.0` then check that it still works and doesn't malfunction.

**Comment by Subha** [comment]
Thanks for being on top of it and providing the fix. Is this updated in the demo for react-responsive-ui?

http://catamphetamine.github.io/react-phone-number-input/
