### ISSUE TITLE
Country code deleting

### ISSUE THREAD

**Issue by ihaveaproblem** [catamphetamine/react-phone-number-input#219]
Hello, thanks for this great component.
How do I prevent the country code from being deleted with the backspace? 
Is it possible?

**Comment by catamphetamine** [comment]
Provide an exact example.

**Comment by ihaveaproblem** [comment]
I'm sorry I didn't mention that I had set the country code to input before.
i solve my problem with onKeyDown event.

lockBackSpace(event){
    (event.target.value === '+'+getCountryCallingCode(this.props.country) && event.keyCode === 8) && event.preventDefault();
  }

**Comment by catamphetamine** [comment]
You still haven't provided the exact example of what you're experiencing and what's the desired result.

**Comment by ihaveaproblem** [comment]
Sorry. this case not an issue. (:
