### ISSUE TITLE
I can't distinguish between a blank field and for example two numbers

### ISSUE THREAD

**Issue by GrzegorzZajac000** [catamphetamine/react-phone-number-input#220]
When I enter 2 digits into the field I get the value `undefined` in the same way as in the case of an empty field. I would like to distinguish between these two situations in the code.

Is there a possibility for that?

**Comment by catamphetamine** [comment]
2 digits is not a valid number.

**Comment by GrzegorzZajac000** [comment]
Yes, I know. But i can't check in code if it is empty field or invalid value.

**Comment by catamphetamine** [comment]
```js
import { parseIncompletePhoneNumber } from 'libphonenumber-js/custom'
parseIncompletePhoneNumber(input.value)
```

**Comment by GrzegorzZajac000** [comment]
It doesn't work.

![screenshot 2018-12-12 08 06 11](https://user-images.githubusercontent.com/12233796/49852580-d738e100-fde4-11e8-90ec-25e184d1365a.png)

![screenshot 2018-12-12 08 06 56](https://user-images.githubusercontent.com/12233796/49852608-e7e95700-fde4-11e8-9d55-e0d79b5b7d57.png)

**Comment by catamphetamine** [comment]
Test phone for `undefined` first.
