### ISSUE TITLE
Package causes "illegal access" error in chinese version of Whatsapp

### ISSUE THREAD

**Issue by martinratinaud** [catamphetamine/react-phone-number-input#221]
Hi folks,

first, sorry to raise such an error as if, like me, you do not live in China, and it will be difficult to test.
This package and the demo page itself causes error when you open it from the internal wechat browser first installed with a chinese number.
But it works well with international version of Whatsapp.

Steps to reproduce
---------
- open wechat with chinese phone number
- open http://catamphetamine.github.io/react-phone-number-input/ from the internal wechat browser 
- See the title and then a blank page

It seems to be a problem with the latest version of wechat though as it was correctly working in september and i've tested with the react-phone-number-input version from that time (2.2.1) and it is not working anymore

Thanks again for 

https://medium.com/@martinratinaud/illegal-access-wechat-weixin-and-react-phone-number-input-dc851b184015

**Comment by catamphetamine** [comment]
Hi.
There haven't been any upvotes on your comment.
If someone did experience something like that, I guess they'd upvote it.
I guess I should close the issue.
