### ISSUE TITLE
When editing (except for the last 4 digits), the cursor automatically moves to the end of the phone number

### ISSUE THREAD

**Issue by sherpadougs** [catamphetamine/react-phone-number-input#223]
For example, in the number (123) 456-7890, if I backspace the 4, it disappears as expected but my cursor moves to the end of the input box. This could possibly be something in my codebase (I've been wrong once or twice :D) but I tried creating a new component without the event handlers and it still does it.

**Comment by catamphetamine** [comment]
See the "Smart Caret" section of the demo.
http://catamphetamine.github.io/react-phone-number-input/

**Comment by sherpadougs** [comment]
Sweet. Thank you!
