### ISSUE TITLE
Styling react-phone-number-input__icon

### ISSUE THREAD

**Issue by zachfeldman** [catamphetamine/react-phone-number-input#228]
I saw that in the past there was a selectStyle and inputStyle attribute that seem to have been removed in new versions. I was wondering if it's possible to target react-phone-number-input__icon class with modular styles at all. 

Flags are rendering like this for me:
![image](https://user-images.githubusercontent.com/1437644/51416576-1d056980-1b48-11e9-86a9-c4833a379f05.png)

But If I remove the border or play with the width/height properties I can fix it in the inspector. I'm just not sure how to modify these styles in the correct way.

Thanks for any assistance!

**Comment by catamphetamine** [comment]
I see, so you're using inline styles.
But this component requires including `style.css` which means that you can include your custom css along with it.
Would it be enough or do you still need `inputStyle` and `selectStyle`?
If yes then provide an example of what do you need the style property for.

**Comment by catamphetamine** [comment]
Also, if you found a solution for the incorrect flag position then you can post your answer here: https://github.com/catamphetamine/react-phone-number-input/issues/222

**Comment by zachfeldman** [comment]
Thanks @catamphetamine that helped a lot to think about the problem that way!

I used this CSS, which made the flags look good to me:
```
.react-phone-number-input__icon{
  height: initial;
  border: 0;
}
```

basically overrides.

Closing this one up for now!
