### ISSUE TITLE
Padding 

### ISSUE THREAD

**Issue by howieandersen** [catamphetamine/react-phone-number-input#230]
![capture](https://user-images.githubusercontent.com/36008713/51529573-415b9180-1e39-11e9-8d08-b688ffe7a2ed.PNG)

I am struggling to figure out why the flag image doesn't line up with with the border around it. I am trying to find a padding setting or something, but no answer as of yet.

Any thoughts or comments?

**Comment by catamphetamine** [comment]
Maybe something like https://github.com/catamphetamine/react-phone-number-input/issues/228 or https://github.com/catamphetamine/react-phone-number-input/issues/222

**Comment by howieandersen** [comment]
As reported in #228, this made it work:

.react-phone-number-input__icon{
  height: initial;
  border: 0;
}

Thank you so much for fast reply :)

**Comment by catamphetamine** [comment]
It's weird why `height: initial` and `border` would fix the issue.
Ok, whatever.

**Comment by howieandersen** [comment]
I don't know if it matters or not, but I am running this component in a React + TypeScript project.
