### ISSUE TITLE
OnChange is called with an undefined value

### ISSUE THREAD

**Issue by eugenio-caicedo** [catamphetamine/react-phone-number-input#232]
I am testing my component with jest and enzyme but when try to change the value in this component the onChange event is called with the undefined method. But when run the app using the `npm start` the component works very well.

This is my code:

```
const onChange = sinon.spy()
const wrapper = mount(<InputField dispatch={dispatch} onChange={onChange} label="Phone" name="phonenumber"/>)

  describe('with valid form data', () => {
    it('dispatches an action', () => {
      dispatch.resetHistory()
      wrapper
        .find('input[name="telephone"]')
        .simulate('change', { target: { name: 'telephone', value: '5555555555' } })  //Undefined Value
      expect(onChange.calledOnce).toEqual(true)
     ........
```

InputField:

```
const InputField = props => {
  return (
    <div>
      <label className="input-label">{props.label}</label>
      <PhoneInput
        country="US"
        onChange={props.onChange}
        name={props.name}
      />
    </div>
  )
}
```

**Comment by catamphetamine** [comment]
> I am testing my component with jest and enzyme but when try to change the value in this component the onChange event is called with the undefined method.

You mean "with the `undefined` value"?
`onChange` is supposed to be called with the `undefined` value when the input is empty.

**Comment by eugenio1590** [comment]
@catamphetamine Yes, I want to say "with the `undefined` value".
Yes, but when simulating the event 'onChange' with enzyme it should throw the value `5555555555 `not `undefined`

`.simulate ('change', {target: {name: 'telephone', value: '5555555555'}})`

**Comment by eugenio-caicedo** [comment]
@catamphetamine Yes, I want to say "with the `undefined` value".
Yes, but when simulating the event 'onChange' with enzyme it should throw the value `5555555555 `not `undefined`

`.simulate ('change', {target: {name: 'telephone', value: '5555555555'}})`

**Comment by catamphetamine** [comment]
@eugenio-caicedo Oh, I see what you mean. Ok. Don't know then.

**Comment by eugenio-caicedo** [comment]
@catamphetamine  Ok, I understand. I was reviewing the code and the problem is with the simulated event. It should be this way:

`.simulate ('change', '+18888888888')`

Thanks for the support.

**Comment by catamphetamine** [comment]
@eugenio-caicedo Ok. I had similar thoughts, but then saw that you have `country="US"` set up.
Don't know why didn't it like the pre-defined country from `<Phone country="US"/>`.
I guess pre-setting `country` property doesn't work in Enzyme.
But ok, for application testing just international numbers will be enough.

**Comment by akhilkandibanda** [comment]
> @catamphetamine Ok, I understand. I was reviewing the code and the problem is with the simulated event. It should be this way:
> 
> `.simulate ('change', '+18888888888')`

Hi, I tried this but this solution is still not working. I am using the <Input withCountryCode, ..... /> but still when I fire this it only takes +1 and not the value I pass. 

Any suggestions.
> 
> Thanks for the support.
