### ISSUE TITLE
Input Box Not Clickable [Focus issue]

### ISSUE THREAD

**Issue by saikatharryc** [catamphetamine/react-phone-number-input#236]
My code looks like this:
using Version: 2.3.0 
```
this.state.phone = ''
<PhoneInput
                                inputComponent={SmartInput}
                                placeholder="Enter phone number"
                                value={this.state.phone}
                                onChange={phone => this.setState({ phone })}
                            />
```

The issue i'm facing is, when DOM is loading with this compnent its working, but once i move the cursor to somewhere else and agaiin try to click on that.
its not allowing to Edit the field. on click instantly the Editor cursor disappers [i.e i guess foucus goes away ?]

although if i select the country from the dropdown, then the focus is coming. without selecting the country this is happening.

![ezgif com-optimize](https://user-images.githubusercontent.com/15653282/52894434-2d544700-31cf-11e9-848f-a27bfdb02f06.gif)

**Comment by catamphetamine** [comment]
I don't see such behavior on demo.
If you want you can create a minimal repo illustrating the issue.

**Comment by saikatharryc** [comment]
@catamphetamine  i have hosted the application [here](https://hustle.blockcluster.io/login), you can have a look,:

**Comment by catamphetamine** [comment]
@saikatharryc I see, it resets the focus.
I guess what you could do is strip down your code until it works and then you'll know what caused the bug.
Perhaps there's some script that focuses the first input of the form.
The first input is `<select/>`.
Or something like that.

**Comment by saikatharryc** [comment]
@catamphetamine  thanks, i'm currently using ionic v1 csss components. 
and seems its somehow doing this manipulation you mentioned above.
i have checked with without ionic v1 css component , and it worked!
thanks.
