### ISSUE TITLE
Doesn't work properly with Redux-Form Field

### ISSUE THREAD

**Issue by Metrior** [catamphetamine/react-phone-number-input#237]
All this is wrapped in Field, but unfortunately onChange doesn't work. On "delete" it deletes all input and can't enter more than one number
```
render() {
    const { props } = this;
    const { input } = this.props;

<PhoneInput
                  {...input}
                  onChange={input.onChange}
```

**Comment by catamphetamine** [comment]
> On "delete" it deletes all input and can't enter more than one number

You can create a simple "jsfiddle" to illustrate the issue.
If you "can't enter more than one number" then perhaps it outputs something in the console.

**Comment by catamphetamine** [comment]
Closing until further details are provided.

**Comment by bibaldo** [comment]
@Metrior did you find a solution?
