### ISSUE TITLE
Catch error: unknown country: HM

### ISSUE THREAD

**Issue by zeroism** [catamphetamine/react-phone-number-input#238]
v2.3.4 and v2.3.5's country list is different from the previous version.
Among them, selecting "Heard Island and McDonald Islands" and entering a phone number will result in an error.

`Catch error: unknown country: HM`

If I downgrade to v2.3.3, it works fine.

**Comment by catamphetamine** [comment]
Indeed.
Released `react-phone-number-input@2.3.6` with the fix.
