### ISSUE TITLE
Wrong Flag for Indonesia

### ISSUE THREAD

**Issue by ianeinser** [catamphetamine/react-phone-number-input#239]
Hi there,

this is a great library. I want to inform you that the Indonesian flag is wrong. It should be red (top) and white (bottom) not the other way. I really appreciate if you would change our national flag.

Best regards,

Ian

**Comment by catamphetamine** [comment]
Hi.
You can report any flag issues in the flags repo: https://github.com/lipis/flag-icon-css
All flags are from that package.

**Comment by ianeinser** [comment]
> Hi.
> You can report any flag issues in the flags repo: https://github.com/lipis/flag-icon-css
> All flags are from that package.

Hi,
Thanks for the reply. Unfortunately, I checked but it seems you are wrong. This is correct

https://github.com/lipis/flag-icon-css/blob/master/flags/1x1/id.svg

and 

https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/id.svg

Would you please check it out?

Best regards,

Ian

**Comment by catamphetamine** [comment]
> It should be red (top) and white (bottom)

The flag is correct. See the demo.

![image](https://user-images.githubusercontent.com/477167/53327294-91c28500-38f8-11e9-9502-7d9fa232d93d.png)
