### ISSUE TITLE
Unknown country: AB

### ISSUE THREAD

**Issue by raquelmv** [catamphetamine/react-phone-number-input#240]
abkhazia return an error:

```
Uncaught Error: Unknown country: AB
    at getCountryCallingCode (metadata.js?07f3:405)
    at e164 (input-control.js?c0ef:214)
    at migrateParsedInputForNewCountry (input-control.js?c0ef:163)
    at onCountryChange (PhoneInput.js?3865:829)
    at CountrySelectNative._this.onChange (CountrySelectNative.js?fa59:50)
```

"AB": "Abkhazia"

**Comment by catamphetamine** [comment]
Hello.
Yes, I had to remove "Abkhazia" from the list because `libphonenumber-js` doesn't support "AB" country code.
See: https://libphonenumber.appspot.com/phonenumberparser?number=1234&country=AB

**Comment by catamphetamine** [comment]
Now the code checks for each country whether it's supported by Google's `libphonenumber`:
https://github.com/catamphetamine/react-phone-number-input/blob/622468446db6bad5483762dee6f52b985e2e9b4e/source/PhoneInput.js#L1026-L1038

**Comment by catamphetamine** [comment]
@raquelmv So I finally figured what you meant: if a developer uses a geolocation service that returns "AB" (Abkhazia) for a user's country code and then this country code is passed to the `<PhoneInput/>` component — the component would break.
That's a legitimate issue.
I fixed that in the latest release `react-phone-number-input@2.3.9`.
Now it doesn't throw when it encounters an unknown country code: it just logs an error to the console and keeps working (it assumes no `country` has been changed in such cases).

**Comment by tabrizh** [comment]
The problem has not gone away. I currently use 3.2.23 and if I do not pass a defaultCountry it throws me an error message "Unknown country: undefined at getCountryCallingCode". In the beginning it works fine and when a user types a number it first identifies the country as it is supposed to do, but whenever a user presses backspace it throws an error.

**Comment by catamphetamine** [comment]
@tabrizh No bug reports are considered without a corresponding "code sandbox" demo and clear steps for reproducing the issue.
