### ISSUE TITLE
modules/formatPhoneNumberDefaultMetadata.js has wrong import

### ISSUE THREAD

**Issue by Huulivoide** [catamphetamine/react-phone-number-input#241]
modules/formatPhoneNumberDefaultMetadata.js import libphonenumber-js/custom instead of libphonenumber-js/core, which again results in double import of libphonenumber-js.

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@2.3.7` with the fix.
Note that importing directly from `react-phone-number-input` is currently deprecated and instead consider importing from one of the sub-packages (for example, `/min`).
