### ISSUE TITLE
Control from external elements

### ISSUE THREAD

**Issue by subvertallchris** [catamphetamine/react-phone-number-input#246]
I'm building a simple touchscreen interface that uses some divs arranged as a number pad (like a telephone) to change the value of the phone input field in addition to the hardware keyboard. Since this library cleans up numbers before they hit my `onChange` function, I'd love a way to hook into that same parsing function that exists in the instance of `PhoneInput` that is already in my component. Does something like this exist? If not, what's my best option for making my external phone number input controls behave like `onChange` events natively originating inside of the input inside `PhoneInput`?

Sorry if this is unclear, let me know if you need more explanation.

**Comment by subvertallchris** [comment]
Maybe it's more simply stated this way: I want to manually feed a value into PhoneInput's [onChange](https://github.com/catamphetamine/react-phone-number-input/blob/master/source/PhoneInput.js#L630), have it parsed by the library, and fed back up into my component's `onChange` event.

**Comment by catamphetamine** [comment]
It's not clear to me what your issue is and what're you trying to achieve.
If you have a custom number pad then I guess there shouldn't be an issue with that because you can change the value of the `<input/>` directly.
For example, `node.querySelector('input').value = node.querySelector('input').value + '123'`.

**Comment by catamphetamine** [comment]
Or maybe you'd like to have some method on the `ref`?
Like `phoneInput.input('3') // Appends digits to the current input.` and `phoneInput.reset()`?

**Comment by catamphetamine** [comment]
Or maybe you'd prefer to use `libphonenumber-js` `AsYouType` directly if you're not providing the actual `<input/>` functionality.
https://github.com/catamphetamine/libphonenumber-js#class-asyoutypedefaultcountry

**Comment by subvertallchris** [comment]
Your second idea, `phoneInput.input('3')` and `phoneInput.reset()` is what I'm hoping to achieve. The user is still able to input numbers through a keyboard, so I do not want to lose the controlled input provided by the `PhoneInput` component, but I want to share the behavior.

For now, I'm doing this. My numberpad calls a function that uses `parseInput` the way `PhoneInput` seems to do and then it calls the `phoneNumberChanged` function. If the user types directly into `PhoneInput`, it calls `phoneNumberChanged` directly. This seems to work 100%.

Is there a better way to do this or is it ok?

```typescript
  @autobind
  phoneNumberChanged(phone?: string) {
    const phoneState = phone || '';
    this.setState({ phone: phoneState }, () => {
      this.props.phoneNumberChanged(phoneState);
    });
  }

  @autobind
  phoneNumberKeypadPressed(value: number) {
    const newVal = `${this.state.phone}${value}`;
    const parsed = parseInput(newVal, 'US', [{ US: metadata.countries.US }], false, true, metadata);
    this.phoneNumberChanged(parsed.value || newVal);
  }

  @autobind
  phoneNumberDeletePressed() {
    jsKeyboardTextHandler('{bksp}', this.state.phone, this.phoneNumberChanged);
  }

  render() {
    return (<>
        <PhoneInput
            country='US'
            countries={['US']}
            displayInitialValueAsLocalNumber={true}
            error='Invalid Phone number'
            flagsPath={'/static/media/'}
            indicateInvalid={!this.validPhoneNumber()}
            international={false}
            getInputClassName={() => 'form-input phone-input'}
            placeholder='Enter phone number'
            value={this.state.phone}
            onFocus={this.onFocus}
            onChange={this.phoneNumberChanged}
        />
      <NumberPad keyPressed={this.phoneNumberKeypadPressed} deletePressed={this.phoneNumberDeletePressed} />
    </>)
  }
```

**Comment by catamphetamine** [comment]
@subvertallchris I guess anything other that using the currently-non-existing `.input()` and `.reset()` methods would be a hack.
I was thinking about whether I should add those to the component.
And I still haven't decided on that.
Maybe in some future I'll settle on something, but for now it's as is.

**Comment by subvertallchris** [comment]
Got it, thank you. I'll stick with what I have but it might be worth adding this behavior. It would be very helpful for myself and others.

**Comment by catamphetamine** [comment]
A sidenote: version `3.x` has been released, that forwards `ref` to the `<input/>`.
Perhaps hypothetically theoretically something like emulating `change` event could be used in such situations:
https://stackoverflow.com/questions/2856513/how-can-i-trigger-an-onchange-event-manually
