### ISSUE TITLE
weird behavior on Safari 9.3

### ISSUE THREAD

**Issue by YoannDelpierre** [catamphetamine/react-phone-number-input#250]
:wave:

I got a strange behavior on Safari 9.3

I fill my phone field with a correct phone number (french number) and when I switch from the phone number field to another field, last digit is removed.

Seems related to this https://github.com/catamphetamine/react-phone-number-input/blob/001946e911d31d1b0dbdc7886a32beae7c074a03/source/InputBasic.js#L81

But not not sure why it happens only on Safari 9.3 :(

**Comment by catamphetamine** [comment]
> Seems related to this

You can check that by editing the file in `node_modules/react-phone-number-input/modules` folder (or `commonjs`) and adding `console.log()` there.
I'm on Windows so I won't be able to check your bug report and you're on your own.

**Comment by YoannDelpierre** [comment]
Hi, thanks for you answer.

Strange thing is that demo is working fine on my simulator :(

Do you know which version is deployed on your demo page ?

**Comment by YoannDelpierre** [comment]
So after logging, I confirm that slicing is applied... Looks like iOS 9 trigger one last `onChange` when we onBlur :(

**Comment by catamphetamine** [comment]
> Do you know which version is deployed on your demo page ?

It's the latest version.

> Looks like iOS 9 trigger one last onChange when we onBlur :(

Hmmm, that would be strange.
Maybe some "react form" software is doing that?
I didn't use the component with things like `redux-form` or `final-form` or something like that: they may trigger `onChange` when `onBlur` is triggered to update the value in state.

**Comment by YoannDelpierre** [comment]
Yes I saw some issues with "react form" software, but we don't use one of them.

**Comment by YoannDelpierre** [comment]
Hi again, still looking on my problem

I notice you use React 14.9 on your demo page, i'm wondering if it not related 🤔

**Comment by catamphetamine** [comment]
> I notice you use React 14.9 on your demo page, i'm wondering if it not related 

You can try some later React version on it if you want.

**Comment by YoannDelpierre** [comment]
Any way to start react phone number input locally ? I don't see any commands for local dev

**Comment by catamphetamine** [comment]
> Any way to start react phone number input locally ? I don't see any commands for local dev

There's a `npm run build` command for building a local build (if you want to do that).
It builds `modules`, `commonjs` and `bundle`.
Here's the `bundle` directory contents:
[bundle.zip](https://github.com/catamphetamine/react-phone-number-input/files/3107872/bundle.zip)
Unzip it into the project folder and then run `index.html` for testing.

**Comment by YoannDelpierre** [comment]
Finally I used SmartInput and seems working on iOS 9.3

Thanks

**Comment by reintroducing** [comment]
I'm also seeing this issue on an iPad and was wondering how you fixed this. What is `SmartInput`?

**Comment by catamphetamine** [comment]
@reintroducing Are you using the latest version? It's `SmartInput` by default.

**Comment by reintroducing** [comment]
@catamphetamine yes, just updated to it a few days ago. to be fair, it is an older iPad on an older version of iOS (Seems like 9.3.5 is the version QA is using), but it is exhibiting this deleting the last character onBlur behavior.

**Comment by reintroducing** [comment]
@catamphetamine also worth noting im still using the following import in my code:
```js
import ReactPhoneInput, {
    getCountryCallingCode,
    isValidPhoneNumber,
} from 'react-phone-number-input/max';
```
Is that using SmartInput?

**Comment by catamphetamine** [comment]
> Is that using SmartInput?

Yes, `smartCaret` is `true` by default.

> but it is exhibiting this deleting the last character onBlur behavior.

So, you only have the bug on iOS and don't have it on a desktop computer?

**Comment by reintroducing** [comment]
That’s correct, it’s only on this older version of iOS on iPad. Version 12+ of iOS on iPhone works fine. I know this doesn’t help much, and I’ve already told QA this is too old of an iPad to support, but just preparing for them to push back :)

**Comment by catamphetamine** [comment]
Ok, I'm reopening the issue then.
It won't be fixed, but people could find it.

**Comment by reintroducing** [comment]
@catamphetamine I stand corrected, QA was viewing an older version before I updated to 3.x of this library, it is now confirmed fixed. I think you can close this again, my apologies.

**Comment by catamphetamine** [comment]
Ok
