### ISSUE TITLE
Require Country Code next to Flag

### ISSUE THREAD

**Issue by gotyet9** [catamphetamine/react-phone-number-input#251]
How can i get Country code just next to the country flag? I want it to be immediate next to flag instead of it being inside the input ?

**Comment by catamphetamine** [comment]
Use `AsYouType` from `libphonenumber-js`.

**Comment by gotyet9** [comment]
Will that get me a +1 for eg for USA by default too ?

**Comment by gotyet9** [comment]
And how will other library help me out to have that country code in design on other library ?

**Comment by catamphetamine** [comment]
> Will that get me a +1 for eg for USA by default too ?

It's not clear what you're saying.

> And how will other library help me out to have that country code in design on other library ?

Don't understand you.
