### ISSUE TITLE
Formatting is not working Australian Phone Number

### ISSUE THREAD

**Issue by vaishali-bluepineapple** [catamphetamine/react-phone-number-input#254]
Set default country="AU". 
If we start typing with +61 and enter phone number as +61 416 123 456. Then formatting works.

But if we do not type +61 and select country from country selection drop down and enter same phone number, formatting does not work.

**Comment by catamphetamine** [comment]
Not understand.
You can provide a GIF or a step-by-step instruction.

**Comment by vaishali-bluepineapple** [comment]
1. Navigate to first Native country <select/> component here - http://catamphetamine.github.io/react-phone-number-input/.
2. Select country as "Australia" and enter number +61 416 123 456, formatting works.
![image](https://user-images.githubusercontent.com/45169813/57772273-a0b81700-7732-11e9-8615-f171e3a620d7.png)
3. Now refresh page -  http://catamphetamine.github.io/react-phone-number-input/ and navigate to same component.
4. Select country as "Australia" and enter number  416 123 456, formatting does not work.
![image](https://user-images.githubusercontent.com/45169813/57772179-6a7a9780-7732-11e9-9a5a-651c566a8f73.png)

**Comment by catamphetamine** [comment]
@vaishali-bluepineapple 
See Google's demo — the national format is different:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B61+416+123+456

**Comment by vaishali-bluepineapple** [comment]
Is there any workaround to have formatted Australian phone number without entering +61? As it works as expected when we enter +61.

**Comment by catamphetamine** [comment]
`416 123 456` is not a correct phone number.
See the link I posted.
