### ISSUE TITLE
onChange should be called with "" instead of undefined

### ISSUE THREAD

**Issue by oleg-mtr** [catamphetamine/react-phone-number-input#256]
Because of undefined redux-form is not updating the value in store and you always have country prefix in store form value despite input being empty.

My workaround is:

```js
<PhoneInput
  {...reduxFormProps}
  onChange={value => reduxFormProps.onChange(value || "")}
/>
```

**Comment by catamphetamine** [comment]
Ok

**Comment by oleg-mtr** [comment]
Thanks

**Comment by catamphetamine** [comment]
For reference, `redux-form` has been deprecated for a long time and there are many non-Redux solutions now, like `final-form` and such.
