### ISSUE TITLE
Is it possible to customize the country text displayed in each `<option>` of the dropdown?

### ISSUE THREAD

**Issue by Kyle-Ski** [catamphetamine/react-phone-number-input#259]
Hi!
We'd like to be able to display the country code next to the country name in the dropdown like so:
<img width="327" alt="new" src="https://user-images.githubusercontent.com/38336076/58708551-5d39eb80-8375-11e9-8ea0-0cf48d48b0a9.png">
(Every code would obviously not be +444)
I see someone else wanted to display the country code later in issue [#7](https://github.com/catamphetamine/react-phone-number-input/issues/7) and you suggested `onCountryChange`. Is this still a viable option? Or would there be another way for us to accomplish this?
Thanks!

**Comment by catamphetamine** [comment]
`onCountryChange` is not for dropdown.
Displaying country codes is not supported in the current version.
One can supply their own country `labels`, see the README for more info.
Those labels can be constructed from the default labels by appending country codes via `getCountryCallingCode()` function from `libphonenumber-js`.

**Comment by Kyle-Ski** [comment]
Thanks for the quick response!

I am now having an issue trying to import any of the labels from `react-phone-number-input/locale/` and was wondering if you could shed some light on the issue for me.

### Steps I've already taken:
- Uninstall and reinstall the package
- importing the labels directly from the `node_modules` directory 
### My code: 
```js
import PhoneInput from 'react-phone-number-input'
import ru from 'react-phone-number-input/locale/ru'

<PhoneInput
                    placeholder="Enter phone number"
                    value={this.state.form.call_forwarding_number}
                    onChange={value => this.submitForm('call_forwarding_number', value)}
                    labels={ru}
/>
```
### Version:
2.3.13

**Comment by catamphetamine** [comment]
So what's not working?

**Comment by Kyle-Ski** [comment]
Sorry I get a `Module not found: Error: Can't resolve 'react-phone-number-input/locale/ru'` error when compiling

**Comment by catamphetamine** [comment]
Try `.json`

**Comment by Kyle-Ski** [comment]
That solved it!
