### ISSUE TITLE
Countries not found

### ISSUE THREAD

**Issue by maLikiz** [catamphetamine/react-phone-number-input#260]
When I add my list of countries, I get the error "Country not found."
Countries get the error: `AQ`,`BV`,`TF`,`HM`,`AN`,`PN`,`GS`,`UM`

`libphonenumber-js/metadata.min.json` haven't my countries, but `react-phone-number-input` have it,  this bad

**Comment by catamphetamine** [comment]
If there's an error then those countries are not supported.

**Comment by wmtamit** [comment]
What is Solution for this Country? we can't remove this country into overside @catamphetamine
