### ISSUE TITLE
PropType error: inputComponent should be also be an object

### ISSUE THREAD

**Issue by jonathanrafaelz** [catamphetamine/react-phone-number-input#262]
Hi,

I created a custom input with a wrapper to do styling and wrapped it with `React.forwardRef` to get access to the ref and pass it down to the `input` inside the wrapper.

Everything is working fine, but I get an warning in the console:
```Warning: Failed prop type: Invalid prop `inputComponent` of type `object` supplied to `PhoneNumberInput`, expected `function`.``` because `React.forwardRef` returns an object.

So I think that the prop types for the inputComponent should be:
`inputComponent : PropTypes.oneOf([PropTypes.func.isRequired, PropTypes.object.isRequired])`

I can send you a PR if you prefer.

**Comment by catamphetamine** [comment]
Hmm, so they're objects then...
Seems that `PropTypes.elementType` is a better choice.
https://github.com/facebook/prop-types/issues/200

Released the new version `react-phone-number-input@2.3.14`.

**Comment by jonathanrafaelz** [comment]
@catamphetamine thanks, worked perfectly
