### ISSUE TITLE
Typescript Compile stopped working

### ISSUE THREAD

**Issue by Borvik** [catamphetamine/react-phone-number-input#263]
It appears removal of the `declare module` may have caused this.  We were using ~2.3.11 and I ran an update today, and the build stopped working.

```
../common/temp/node_modules/.registry.npmjs.org/react-phone-number-input/2.3.15/react-dom@16.8.6+react@16.8.6/node_modules/react-phone-number-input/index.d.ts:74:41 - error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

74 export default class PhoneInput extends React.Component<PhoneInputProps, object> {}
```
Reverting to 2.3.11 resolved the issue.

**Comment by catamphetamine** [comment]
I see.
I guess I'll be removing the type definition files then.

**Comment by catamphetamine** [comment]
Superceded by https://github.com/catamphetamine/react-phone-number-input/issues/195
