### ISSUE TITLE
TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by MaxiStarling56** [catamphetamine/react-phone-number-input#264]
when trying to use the phone input in a form I get the error:
**"TypeError: Cannot read property 'state' of undefined"**
on the line **"value={this.state.value}"**

my code:

    import React, { useState } from 'react';
    import PhoneInput from 'react-phone-number-input';

    const App = () => {
        return (
            <div className="form">
                <form onSubmit={handleSubmit}>
                    <PhoneInput
                        placeholder="Enter phone number"
                        value={this.state.value}
                        onChange={value => this.setState({ value })} />
                </form>
            </div>
        )
    }

    export default App;

**Comment by catamphetamine** [comment]
Because you don't have `this` in the code.

**Comment by MaxiStarling56** [comment]
Where do i need to add "this"?
If i use **this.value={this.state.value}** it give me error: **"Identifier expected"**

**Comment by catamphetamine** [comment]
You don't have `this` in your code.
`this` is only for classes.
