### ISSUE TITLE
property - countryOptions '...' not working as expected

### ISSUE THREAD

**Issue by BramDecuypere** [catamphetamine/react-phone-number-input#267]
It is not working as expected:

the '...' is not omitting the other values as documented in the code

`
<PhoneInput
  id={'contact_callback_form_phone_field'}
  country="BE"
  countryOptions={['BE', 'NL', 'FR', '|', '...']}
  placeholder={data.telefoon_placeholder[0].text}
  labels={locales[lang]}
  value={this.state.phone}
  onChange={phone => this.setState({ phone })}
/>
`

**Comment by catamphetamine** [comment]
Explain in more detail what's the issue you're having.
