### ISSUE TITLE
Retrieving ISO2 country code and numeric dial code

### ISSUE THREAD

**Issue by dben89x** [catamphetamine/react-phone-number-input#268]
Is there a way to retrieve the ISO country code (e.g. "US", "CA", "RU" for United States, Canada, Russia) and the numeric dial code (e.g. "+1", "+1", "+7" for for United States, Canada, Russia)?

I saw this request referenced in #16 but the solution of using `parsePhoneNumber()` doesn't seem to be referenced anywhere in the documentation. I'm not sure if this was removed or developed further since that issue, but I don't see anywhere that indicates as much.

My reasoning for accessing this data is that I'd like to do my own extensive back end validations that will need both the ISO2 country code and dial code. I'd also like the ISO2 code for analytical purposes, like getting a count on which numbers are in which country.

I'm currently using the following workaround to get the ISO2 code, but it feels sooo dirty:
`var isoCountryCode = $('.rrui__select__selected-content img:first').attr('alt')` (I know, I'm only using jquery because it's already included in our code)

**Comment by catamphetamine** [comment]
How about getting the country code from the `value`?

**Comment by catamphetamine** [comment]
For example, like this:
https://github.com/catamphetamine/libphonenumber-js#parse-phone-number

**Comment by dben89x** [comment]
@catamphetamine Fantastic. Did not know this existed. It does exactly what I need. Do you think it should be in the readme/docs? I'd be willing to write up a quick section for reference.

Thanks for the quick response!!

**Comment by catamphetamine** [comment]
Released the new version with `parsePhoneNumber(value)` export.


```js
import { parsePhoneNumber } from 'react-phone-number-input'

parsePhoneNumber('+12133734253').country === 'US'
```
