### ISSUE TITLE
Keep the flags source inside the project

### ISSUE THREAD

**Issue by angelolucas** [catamphetamine/react-phone-number-input#269]
It would be best to keep the source of the flags locally. So my project will not depend on other services to work properly.
```
<img 
  alt="BR"
  class="react-phone-number-input__icon-image"
  src="https://lipis.github.io/flag-icon-css/flags/4x3/br.svg"
>
```

**Comment by catamphetamine** [comment]
See the updated readme.
https://github.com/catamphetamine/react-phone-number-input#flags
