### ISSUE TITLE
formatPhoneNumber example not working

### ISSUE THREAD

**Issue by TylerRick** [catamphetamine/react-phone-number-input#274]
I noticed that this example isn't currently working on http://catamphetamine.github.io/react-phone-number-input/:

```javascript
import PhoneInput, { formatPhoneNumber } from 'react-phone-number-input'

const { value } = this.state

<PhoneInput
  placeholder="Enter phone number"
  value={ value }
  onChange={ value => this.setState({ value }) }/>

National: { value && formatPhoneNumber(value, 'National') }
International: { value && formatPhoneNumber(value, 'International') }
```

Looks like it is running into this error in the console:
```
Uncaught TypeError: libphonenumber.formatNumber is not a function
```

**Comment by catamphetamine** [comment]
I did a search of the repo and there's no `formatNumber` in it.
The error seems not descriptive-enough.

**Comment by TylerRick** [comment]
Strange

**Comment by catamphetamine** [comment]
I'll fix this for now since there have been no other reports.
And as it is even if there would be a bug I wouldn't fix it because nah whatever.
