### ISSUE TITLE
Initial value is not normalized; only gets normalized after the first change event

### ISSUE THREAD

**Issue by TylerRick** [catamphetamine/react-phone-number-input#275]
I like how in general, the _output_ value provided by PhoneInput is normalized into a standard "unformatted" (no spaces) format ('+78005553535'). This allows me to send it to the server and store it directly in the database in a uniform format.

However, if you provide an _initial_ value that is "formatted" (like '+7 800 555 35 35'), then no "output" value is emitted (because no change event occurs yet) until you actually press a key in the input. This means that if you submit the form immediately without touching the field, then it could send it to the server in this non-normalized format ('+7 800 555 35 35').

Is there any good way to get it to normalize the initial value immediately to ensure that the state value is always in the same normalized format?

## How to reproduce:

In `index.html` of the demo app (`gh-pages`), change:
```
-						value_convert_to_national_false: '+78005553535',
+						value_convert_to_national_false: '+7 800 555 35 35',
```

State is initially this:

![image](https://user-images.githubusercontent.com/14151/64211537-61394600-ce5b-11e9-88a2-8c064b170f94.png)

But if you focus the input and press the Space key, for example, it gets normalized to this:

![image](https://user-images.githubusercontent.com/14151/64211555-701ff880-ce5b-11e9-8172-b12d2fbeacee.png)

The same behavior can be seen in this [sandbox](https://codesandbox.io/s/react-phone-number-input-initial-value-is-not-normalized-ni404)

## What would the ideal solution be?

Could PhoneInput just normalize its `value` prop and call onChange immediately with this normalized value? That would probably trigger a re-render but I think it would only be one extra render, so should be okay..

If that's not an option, maybe this library could export a `normalizePhoneNumber` function that would normalize it in the same way that it does it `onChange` so that users could normalize the initial value _before_ passing it in as the `value` prop. (Kind of like how `formatPhoneNumber` function is exported. Except this "unformats" the value, or formats it in the opposite direction.)

Any other ideas?

## Workarounds?

One workaround — which I don't like at all — is to simulate a change event when the form is first loaded, using a technique like one of the ones described [here](https://stackoverflow.com/questions/23892547/what-is-the-best-way-to-trigger-onchange-event-in-react-js), [here](https://stackoverflow.com/questions/23892547/what-is-the-best-way-to-trigger-onchange-event-in-react-js), or [here](https://github.com/facebook/react/issues/11488).

I kind of got that workaround to work (you can see the commented code in the [sandbox](https://codesandbox.io/s/react-phone-number-input-initial-value-is-not-normalized-ni404)),
but it seems terribly fragile and hacky.

**Comment by catamphetamine** [comment]
> I like how in general, the output value provided by PhoneInput is normalized into a standard "unformatted" (no spaces) format ('+78005553535'). This allows me to send it to the server and store it directly in the database in a uniform format.

That's the point of the `value`.

> However, if you provide an initial value that is "formatted" (like '+7 800 555 35 35')

You can't because it's invalid to do so.

> Is there any good way to get it to normalize the initial value immediately to ensure that the state value is always in the same normalized format?

How about not formatting the value when passing it initially.

> Could PhoneInput just normalize its value prop and call onChange immediately with this normalized value?

To keep things simple keep this matter out of the component's business.
For phone number parsing one could use `parsePhoneNumber` function.

> If that's not an option, maybe this library could export a normalizePhoneNumber function

Use `parsePhoneNumber(...).value`.

**Comment by TylerRick** [comment]
Thank you, sir. `parsePhoneNumber` looks like it will do the trick!

I knew there must be some reusable method I could use, but couldn't figure out what it was called when I searched through the source code.

I wrote my own `normalizePhoneNumber` function based on that:

```
export function normalizePhoneNumber(input, defaultCountry = null) {
  const parsedPhone = parsePhoneNumber(input, defaultCountry)
  console.log(input, 'parsed as:', parsedPhone)
  if (parsedPhone) {
    return parsedPhone.number
  } else {
    return input
  }
}
```

Demo: https://codesandbox.io/s/react-phone-number-input-parsenormalized-initial-value-upsx4


---

> That's the point of the `value`.

That's what I thought.

It just seems unfortunate that I have to duplicate what it's already doing onChange and apply that to the initial value to make sure it's valid input. But that's okay. It's easy enough!

> How about not formatting the value when passing it initially.

Sure, if the value is within my control. But if it comes from user input, that isn't always possible.

**Comment by TylerRick** [comment]
Actually, it looks like `onChange` (in `source/InputBasic.js`) is using `parseIncompletePhoneNumber` (rather than `parsePhoneNumber`), which just returns a string rather than a PhoneNumber object, and returns a slightly different string (`+78005553535` instead of `7 800 555 35 35` for `+7 800 555 35 35`, for example), so I've [updated](https://codesandbox.io/s/react-phone-number-input-parsenormalized-initial-value-upsx4) my normalize function to use that instead...

**Comment by catamphetamine** [comment]
@TylerRick `parseIncompletePhoneNumber()` is just a syntax parser (removes whitespace) while `parsePhoneNumber()` is the "complete" phone number parser.

**Comment by TylerRick** [comment]
Thank you for pointing that out. I did not realize that.

However, maybe that's all that is needed. Since the goal is simply to:
1. get it in the same uniform ("unformatted") format as the `value` that is emitted from `onChange` so that we can send it in the same format to the server _whether or not_ the user has typed anything in the field, and
2. get in a format that is "valid" as _input_ to PhoneInput, since you said:

> > However, if you provide an initial value that is "formatted" (like '+7 800 555 35 35')
> 
> You can't because it's invalid to do so.

I don't know why you say it's invalid to provide that as input, but it seems like if we removed the whitespace, then you would agree that it is valid input now, since now it's in the canonical format that is used for the value state and passed to the user's `onChange` callback:

```
      let newValue = parseIncompletePhoneNumber(event.target.value)             
      this.setState({ value: newValue }, () => onChange(newValue))     
```

So unless I'm missing something, `parseIncompletePhoneNumber()` should be not only _sufficient_ (we _only_ need the string; we don't need the other metadata provided by `parsePhoneNumber`) but also _preferred_ because it precisely matches the normalization logic applied by the internal `onChange` handler itself.

**Comment by catamphetamine** [comment]
@TylerRick 
> I don't know why you say it's invalid to provide that as input,

Because that's how it's designed to be.

> So unless I'm missing something, parseIncompletePhoneNumber() should be not only sufficient (we only need the string; we don't need the other metadata provided by parsePhoneNumber) but also preferred because it precisely matches the normalization logic applied by the internal onChange handler itself.

`value` is not just whitespaces removed, it's the canonical phone number format which is generated via an algorithm.
