### ISSUE TITLE
Cannot read property 'isRequired' of undefined

### ISSUE THREAD

**Issue by joge17** [catamphetamine/react-phone-number-input#276]
Just installed this component and tried to use it but I am getting this error:

> Cannot read property 'isRequired' of undefined
> TypeError: Cannot read property 'isRequired' of undefined
>     at Object.../../node_modules/react-phone-number-input/modules/PhoneInput.js (D:/Apps/form_app/node_modules/react-phone-number-input/modules/PhoneInput.js:604:0)
>     at __webpack_require__ (webpack:/webpack/bootstrap a9bf9f041ff37723a6c3:714:0)
>     at fn (webpack:/webpack/bootstrap a9bf9f041ff37723a6c3:117:0)
>     at Object.../../node_modules/react-phone-number-input/modules/PhoneInputNative.js (D:/Apps/form_app/node_modules/react-phone-number-input/modules/PhoneInputNative.js:26:0)
>     at __webpack_require__ (webpack:/webpack/bootstrap a9bf9f041ff37723a6c3:714:0)
>     at fn (webpack:/webpack/bootstrap a9bf9f041ff37723a6c3:117:0)
>     at Object.../../node_modules/react-phone-number-input/modules/PhoneInputNativeDefaults.js (D:/Apps/form_app/node_modules/react-phone-number-input/modules/PhoneInputNativeDefaults.js:29:0)
>     at __webpack_require__ (webpack:/webpack/bootstrap a9bf9f041ff37723a6c3:714:0)
>     at fn (webpack:/webpack/bootstrap a9bf9f041ff37723a6c3:117:0)
>     at Object.../../node_modules/react-phone-number-input/modules/PhoneInputNativeDefaultMetadata.js (D:/Apps/form_app/node_modules/react-phone-number-input/modules/PhoneInputNativeDefaultMetadata.js:11:0)

This is how I am using it:

       import PhoneInput from 'react-phone-number-input';
 
      <PhoneInput
        country="AU"
        value={ this.state.phone }
        onChange={ value => this.setState({ value }) }
      />

**Comment by catamphetamine** [comment]
Follow the debug instructions in the issue:
https://github.com/catamphetamine/react-phone-number-input/issues/265
