### ISSUE TITLE
question - default style change

### ISSUE THREAD

**Issue by tim-fastpay** [catamphetamine/react-phone-number-input#278]
Is there any property that I can use to change its default css styling?

**Comment by catamphetamine** [comment]
It's not clear what you mean

**Comment by tim-fastpay** [comment]
I want to customize this input field. Is there any property that accepts style object

**Comment by catamphetamine** [comment]
See the list of the props in the docs

**Comment by catamphetamine** [comment]
See the list of the props in the docs

**Comment by tim-fastpay** [comment]
I cant get rid of the border-color that shows when focused.

**Comment by catamphetamine** [comment]
Provide an online demo example and I could take a look

**Comment by tim-fastpay** [comment]
```
						<PhoneInput
							placeholder="Enter phone number"
							value={state.phone}
							country={state.countryCode}
							countries={['US', 'GB']}
							limitMaxLength
							international={false}
							onChange={handleChange('phone')}
							className={styles.phoneNumber}
							inputClassName={styles.inputStyle}
						/>
```


```
.phoneNumber:focus {
	border-color:red;
}

.inputStyle {
	border-color:red
}

.inputStyle:focus {
	border-color:red
}
```

Even with this css setup, I see blue bottom border

<img width="812" alt="Screen Shot 2019-09-06 at 4 26 57 PM" src="https://user-images.githubusercontent.com/45573716/64465761-381aee80-d0c3-11e9-9e0b-ecc54f61f55d.png">
<img width="333" alt="Screen Shot 2019-09-06 at 4 27 08 PM" src="https://user-images.githubusercontent.com/45573716/64465762-381aee80-d0c3-11e9-9fe6-215383cf6255.png">

**Comment by catamphetamine** [comment]
Seems like your CSS class name isn't applied.
