### ISSUE TITLE
Add inputProps prop that lets you pass props down to the inputComponent

### ISSUE THREAD

**Issue by TylerRick** [catamphetamine/react-phone-number-input#280]
This would be very useful when you have props that you need to pass all the way down to the inputComponent.

Otherwise, you have to create a new hard-coded component for literally every unique combination of props that you may want to pass down to the input component. For example, if you wanted to use PhoneInput several places in your app but wanted to use a different `label` prop (or `helperText` or ...) in each place, you would have to do something horrific like this:

```jsx
const TextFieldWithLabel1 = ({ ...props }) => {
  return (
    <TextField {...props}
      label="Phone number"
    />
  )
}

const TextFieldWithLabel2 = ({ ...props }) => {
  return (
    <TextField {...props}
      label="Optional phone number"
    />
  )
}

        <PhoneInput inputComponent={TextFieldWithLabel1} />
        <PhoneInput inputComponent={TextFieldWithLabel2} />
```

What I'd like is a way to simply pass the props down like this:
```jsx
        <PhoneInput
          inputComponent={TextField}
          inputProps={{
            label: "Optional phone number"
          }}
        />

```

This is how https://material-ui.com/api/text-field/#props lets you pass props to the `<input>` component that it wraps, for example.

**Comment by mglavall** [comment]
+1, Also for passing the error prop to your own custom input. It would be really would if we could display the errors the way that we want

**Comment by catamphetamine** [comment]
@TylerRick @mglavall The readme says that "all other props are passed through to the input component". If some property isn't passed through then leave a comment here. There may be cases when there're property name collisions (for example, `error` property won't be passed through) but in that case the `<PhoneInput/>` component can be customized by wrapping it in a `<PhoneInputWrapper/>` that would rename some of the properties (for example, `error` -> `inputError`) and then those renamed non-colliding properties would get passed to the input component. An `inputProps` property could be introduced but in the case of a custom `label` property it should be passed through to the input component. Doesn't it?

**Comment by catamphetamine** [comment]
An example of how clashing (colliding) props like `error` could be passed:

```js
function CustomInput({ errorProperty }, ref) {
  return <MUIInput error={errorProperty}/>
}

CustomInput = React.forwardRef(CustomInput)

<PhoneInput
  numberInputComponent={CustomInput}
  errorProperty={true/false}/>
```

**Comment by catamphetamine** [comment]
To recap: just pass the props to `<PhoneInput/>` and they'll be passed through.
If some of the props aren't passed through then post their names here and maybe in some future we could justify some new property (or maybe not).

**Comment by catamphetamine** [comment]
I'll close this for now, but will reopen it in case of any issues with the proposed approach.

**Comment by catamphetamine** [comment]
Ok, added `numberInputProps` and `countrySelectProps` today.
Still the existing "passthrough" approach is preferred I guess (for the `<input/>` props).
