### ISSUE TITLE
Forward ref to inputComponent and use that instead of requiring inputComponent to implement `.focus()`

### ISSUE THREAD

**Issue by TylerRick** [catamphetamine/react-phone-number-input#281]
I'm glad the need to implement `.focus()` is at least [documented](http://catamphetamine.github.io/react-phone-number-input/docs/styleguide/index.html#phoneinput), but I am wondering if that requirement is even necessary.

Couldn't we just forward the `ref` to whichever `inputComponent` is provided and just call `ref.current.focus()` on that ref (since it's a ref to an `input`, which already has a `focus()` method) instead of specifically requiring it to provide **_its own_** `focus()` method?

Maybe that's just trading one requirement for another, but it seems like it might be a slightly more elegant solution, and a safer assumption to make since it seems like any input component _ought_ to be forwarding refs anyway.

Then you would only need an adapter component (like [this one](https://github.com/catamphetamine/react-phone-number-input/issues/226#issuecomment-511300590)) _if_ the intended input component had a different _name_ for the ref that gets forwarded all the way down to the input (it's `inputRef` in the case of [material-ui](https://material-ui.com/api/text-field/#props)).

The other reason for this change is because the current requirement that the component implements `.focus()` seems to require that component to be a class component. I'm trying to use hooks and functional components wherever possible and trying to figure out how a functional component (which is basically just the `render()` from a class component) can also implement `focus()`. I don't think it's possible.

See also: #280, #226

**Comment by catamphetamine** [comment]
@TylerRick 

> Couldn't we just forward the ref to whichever inputComponent is provided and just call

Yeah, I've only recently discovered how this whole `ref` forwarding works and it's surely a better way now that React is deprecating `class` components. I've updated the README to reflect that forwarding a `ref` is valid.

> Maybe that's just trading one requirement for another, but it seems like it might be a slightly more elegant solution,

A much more elegant one.

> and a safer assumption to make since it seems like any input component ought to be forwarding refs anyway.

It should, it's just backwards compatibility stuff.
Pre-hooks era, etc.

> I'm trying to use hooks and functional components wherever possible and trying to figure out how a functional component (which is basically just the render() from a class component) can also implement focus(). I don't think it's possible.

Hooks should work provided `ref` is forwarded.
