### ISSUE TITLE
Request: Ability to set name and aria-label of country select

### ISSUE THREAD

**Issue by reintroducing** [catamphetamine/react-phone-number-input#285]
Title pretty much says it all. Right now they are hardcoded to `<select name="phone__country" aria-label="Country">`. It would be nice to set `countrySelectName` and `countrySelectAriaLabel` (or similar), the latter especially useful for internationalization of apps. Thoughts?

**Comment by catamphetamine** [comment]
I could add `countrySelectLabel` property.
Why would anyone want a custom `name`?

**Comment by reintroducing** [comment]
The way I use forms (and I imagine many others may do this as well), the name of a form element maps directly to the serialized value when you run form.submit(). Without having the ability to pass a custom name, I have to grab the serialized data, add a key for what my API actually takes to it and remove the one you provide as a default from the object before sending it off to the API. Does that make sense?

**Comment by catamphetamine** [comment]
> The way I use forms (and I imagine many others may do this as well), the name of a form element maps directly to the serialized value when you run form.submit()

That's how DOM forms work, but it's not clear how you could use a `name` in React.
Do you submit your forms without using any library?

**Comment by reintroducing** [comment]
@catamphetamine I use https://github.com/defunctzombie/form-serialize

If you look at the example, you'll see `var obj = serialize(form, { hash: true });` which outputs `// obj -> { foo: 'bar' }`. I then will just take that data and send directly to my API, but lets say my API expects (in our case) the country code to be `country` and you're submitting it as `phone__country` or whatever it is right now. by not allowing me to change the name value, i have to change the submit data before I send it off to my API, cleaning up your entry and adding mine instead. if i could set the name properly, i wouldn't have to execute those two extra steps and can just take the serialized data and send it in as the data to an API call. Hopefully that helps clear it up. If you want a concrete code sample, let me know and I can provide one.

**Comment by catamphetamine** [comment]
I see, so you're not using any React form libraries.
Well, I guess your use case is extremely rare: most people use a React form library (like Formik) and most people don't need the phone country value (it can always be obtained from a phone number using `parsePhoneNumber()` or using `onCountryChange()`).
I don't think we should complicate the code for such rare cases: the only reason why `<select/>` has such a name is so that it doesn't conflict with other fields.

**Comment by reintroducing** [comment]
I think the assumption that I’m one of the rare few users who use forms directly without a library is not ideal, but in the end this is your package and I’ll continue to use it because it’s fantastic and saves me tons of time, so I appreciate it regardless. I don’t think it would add much overhead at all, similar to one of the props that say something along the lines of “I don’t remember why I added this, someone asked for it a long time ago...” but it’s not a huge deal, I’ll format the data going out before I hit the API.

As I said above, thanks for this package and continue the solid work you’re doing on it, it’s much appreciated.

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@2.3.24` with `countrySelectAriaLabel` + updated README.

**Comment by catamphetamine** [comment]
Note: Added `countrySelectProps` property today.
It can have a `name` property that will override the autogenerated country select `name`.

**Comment by reintroducing** [comment]
fantastic, thank you so much, really appreciate it. keep up the great work!
