### ISSUE TITLE
Questions about content of prefix

### ISSUE THREAD

**Issue by andyford** [catamphetamine/react-phone-number-input#286]
I'm curious how to implement 2 possible variations of the default flag as prefix

1 - How could I show only the numeric country code instead of the flag? (for example, only show "+1" for USA or "+49" for Germany INSTEAD of the flag icon)

2 - How could I show BOTH the flag icon AND the numeric country code instead of only the flag icon?

thanks!

**Comment by catamphetamine** [comment]
Hi.
Currently there's no such possibility.
The only option is providing your own `countrySelectComponent`.
https://github.com/catamphetamine/react-phone-number-input/blob/master/source/PhoneInput.js#L303
See the example:
https://github.com/catamphetamine/react-phone-number-input/blob/master/source/CountrySelectNative.js
