### ISSUE TITLE
can this work with hooks and a functional component?

### ISSUE THREAD

**Issue by rchrdnsh** [catamphetamine/react-phone-number-input#293]
seems the component was a class component...can this be used with a functional component using hooks?

**Comment by catamphetamine** [comment]
It's unclear what your question is.

**Comment by rchrdnsh** [comment]
i tried to use it in a gatsby app and copied in the basic stuff and got an error saying that `this.state` is not defined...trying to use it in a static netlify form, so not sure how to make it work...

put this in a page/react component in a gatsby app, like so:

```jsx
import 'react-phone-number-input/style.css'
import PhoneInput from 'react-phone-number-input'

return (
  <PhoneInput
    placeholder="Enter phone number"
    value={ this.state.value }
    onChange={ value => this.setState({ value }) } />
)
```

...inside of a static netlify form in a react functional component, like so:

```jsx
<Form
  name="alma-form"
  method="post"
  action="/success"
  data-netlify="true"
  data-netlify-honeypot="bot-field"
>
  <input type="hidden" name="bot-field" />
  <input type="hidden" name="form-name" value="alma-form"/>
  <Label>Name<Input name="name" type="text"/></Label>   
  <Label>Email Address<Input name="email" type="email"/></Label>
  <PhoneInput
    placeholder="Enter phone number"
    value={ this.state.value }
    onChange={ value => this.setState({ value }) }
  />
  <Label>Zip Code<Input name="zip" type="text"/></Label>
  <SubmitButton type="submit">Enter Now!</SubmitButton>
</Form>
```

and i get the following error in the browser:

<img width="1037" alt="Screen Shot 2019-11-08 at 3 44 48 PM" src="https://user-images.githubusercontent.com/7884263/68517979-b5d3b580-023e-11ea-8ceb-359a5667178f.png">

so i don't really know what to do next, and i have been learning about hooks (don't know much about classes, as i started learning react after hooks were announced, apparently, sooo, hmmmm, not sure what else to say....just a little bit confused how I might be able to incorporate this input component into a netlify form, i guess.

**Comment by catamphetamine** [comment]
The issues you're having seem to be unrelated to this library.
Instead, you're having issues with combining your app with this library.
You don't seem to be familiar with non-hooks way of writing React in which case you might want to study older class-based React.
`this.state` is not accessible inside a "hooks" component.
The example code therefore won't work by just copy-pasting it.
It's simply an illustration.
Provide your own `value` and `onChange`.

**Comment by rchrdnsh** [comment]
hmmmm, so i need to provide some state to this component, but it could be any kind of state then? Class based state? Hooks state? Redux state? XState state? Is this state used to hold the content that the user is inputting?

**Comment by catamphetamine** [comment]
Yes
