### ISSUE TITLE
How to extract the countryCode

### ISSUE THREAD

**Issue by thanveershah** [catamphetamine/react-phone-number-input#294]
Is there a way to fetch just the selected countryCode ? I have been sitting on  this for days and still was  not able to find it .

**Comment by catamphetamine** [comment]
https://github.com/catamphetamine/react-phone-number-input#getcountrycallingcodecountry-string-string

**Comment by thanveershah** [comment]
I used that , I'm not getting the countryCode no matter what I do.
Please show me how to use it

**Comment by catamphetamine** [comment]
> I'm not getting the countryCode no matter what I do.

https://github.com/catamphetamine/react-phone-number-input#use

To get selected country pass an onCountryChange(country) property, or use parsePhoneNumber(value) function. Example: parsePhoneNumber(value) && parsePhoneNumber(value).country.
