### ISSUE TITLE
Forwarding ref to input

### ISSUE THREAD

**Issue by MiselAdemi** [catamphetamine/react-phone-number-input#297]
I need to forward ref to input element, what will be best approach for doing this?

**Comment by catamphetamine** [comment]
Why do you need to do that?

**Comment by MiselAdemi** [comment]
I am working with React Hook Form library for validating and it uses ref for validating, so I somehow need to pass ref to input element.

Or do you have some other way on mind?

**Comment by catamphetamine** [comment]
If you're working with React Hook Form library then you'll get the raw `value` of the `<input/>` which is not `+12133734253` but instead `(213) 373-4253` or `+1 213 373 4253`.
For this reason I don't recomment using React Hook Form library.

**Comment by ChallaHalla** [comment]
I found this useful: https://stackoverflow.com/questions/59820857/react-phone-input-2-with-react-hook-form

**Comment by catamphetamine** [comment]
Added `react-hook-form` compatibility:

## `react-hook-form`

To use this component with [`react-hook-form`](https://react-hook-form.com), use one of the four exported components:

```js
// "Without country select" component.
import PhoneInput from 'react-phone-number-input/react-hook-form-input'

// "Without country select" component (to pass custom `metadata` property).
import PhoneInput from 'react-phone-number-input/react-hook-form-input-core'

// "With country select" component.
import PhoneInputWithCountry from 'react-phone-number-input/react-hook-form'

// "With country select" component (to pass custom `metadata` property).
import PhoneInputWithCountry from 'react-phone-number-input/react-hook-form-core'
```
