### ISSUE TITLE
How to change country programatically?

### ISSUE THREAD

**Issue by marco-000** [catamphetamine/react-phone-number-input#300]
I'm using Formik and when I reset the form after submit it empties all values except the country that stays the one that was selected. I want to know how can I change the country back to International. And yes, when I reset the form the phone input is empty so it should put the country back to International and it doesn't.

**Comment by catamphetamine** [comment]
> And yes, when I reset the form the phone input is empty so it should put the country back to International and it doesn't.

Only if the phone number was previosly in international format.
If it was in national format then it wouldn't make sense to reset the country, so it doesn't.

As for resetting the country, I could add a new property, something like `resetCountry` that could be any type of value and if it changes then the country select resets itself to "International".

**Comment by marco-000** [comment]
> As for resetting the country, I could add a new property, something like `resetCountry` that could be any type of value and if it changes then the country select resets itself to "International".

In my case I think this might work but if I had a default country, for example 'US' it wouldn't work anymore because if I inserted a phone from another country (not 'US'), when the reset happens it would set it to 'International' instead of back to 'US'. So I was thinking that a function to change the country directly (allowing 'International' when the prop is active) would be more useful.

What do you think?

Thanks in advance!

**Comment by catamphetamine** [comment]
> In my case I think this might work but if I had a default country, for example 'US'

Oh, I see.

> So I was thinking that a function to change the country directly (allowing 'International' when the prop is active) would be more useful.

The reason I'm not implementing an instance method yet is because the component perhaps should `React.forwardRef()` to the `<input/>`, and so its instance methods wouldn't be accessible.

It could be a `reset` property then.
Maybe something like this: if `reset` property changes then it looks if `country` property is defined. If it is, then it sets the country to `country`. Else, it sets the country to `undefined`. `value` is set to `undefined`.

**Comment by marco-000** [comment]
> It could be a `reset` property then.
> Maybe something like this: if `reset` property changes then it looks if `country` property is defined. If it is, then it sets the country to `country`. Else, it sets the country to `undefined`. `value` is set to `undefined`.

Sounds like a good idea. That would fix both problems. It would be nice if you could add this. 

Thanks in advance!

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@2.5.0` with `reset` property.
