### ISSUE TITLE
Optional onChange() prop for PhoneInput

### ISSUE THREAD

**Issue by RemyMachado** [catamphetamine/react-phone-number-input#303]
Hello,

I'm using the prop `numberInputComponent` that let me use a custom input component. In fact I'm handling changes on this custom input with a third party library (Formik). Therefore, I don't need the `onChange` property, but only the `value` one.

Problem is, PhoneInput is crashing if I don't pass the `onChange` prop.

Possible solution: Make it optional and check if exists before calling.

Thanks in advance.

**Comment by catamphetamine** [comment]
Hello.
This component is meant to be used with `onChange` — otherwise you wouldn't get the `value` the user has input.
One could read it directly from `DOMNode.value` but it wouldn't be the parsed value.
So `onChange` is required in order for this component to work.

**Comment by RemyMachado** [comment]
Yeah, you're right, I mixed up the purposes. Thanks for putting me back in the right track.
