### ISSUE TITLE
Android switches keyboard on US format on 4th digit

### ISSUE THREAD

**Issue by richardkeller411** [catamphetamine/react-phone-number-input#304]
Anyone else see this?

**Comment by catamphetamine** [comment]
Can you describe in detail what exactly is happening?

**Comment by richardkeller411** [comment]
Yes on the 4th digit android switches from numbers to alpha

**Comment by catamphetamine** [comment]
That's not a detailed description.
A proper step-by-step full description of the process is required.

**Comment by catamphetamine** [comment]
Closing because there hasn't been a step-by-step reproduction instruction, and no comments from other users.
