### ISSUE TITLE
Adding custom styling or class name to default <select/> element

### ISSUE THREAD

**Issue by johnny-cit** [catamphetamine/react-phone-number-input#306]
I'm trying to add custom styling to the default select element. Is this possible? I tried adding a `className` property to the `countrySelectProps` object, but it doesn't seem to work. Is this the right way to achieve this? Or, is there a prop similar to `inputClassName` but for the select element?

```
<PhoneInput
    countrySelectProps={{ className: 'its-a-class' }} // <--- doesn't work
    inputClassName={inputClasses}
    onChange={handleChange}
    selectClassName={selectClasses}    // <--- does something like this exist?
    value={value}
/>
```

**Comment by catamphetamine** [comment]
`countrySelectProps.className` gets overridden.

```js
<CountrySelectComponent
  {...countrySelectProps}
  className="react-phone-number-input__country"/>
```

Why would you want to use a custom class name for country select?

**Comment by johnny-cit** [comment]
@catamphetamine - I was hoping to add some custom styling. But on closer inspection, maybe what I'm really looking for is the ability to add a custom class name to the div that wraps the select and the icon elements?

**Comment by catamphetamine** [comment]
@johnny-cit Why not style `.react-phone-number-input__country` directly?

**Comment by johnny-cit** [comment]
The project I'm working on uses a css-in-js library that doesn't allow nesting, so while I can add a custom class name to `PhoneInput`, I can't target its child elements. Of course, this isn't an issue with your lib, but just thought being able to pass down a custom class name would work.

**Comment by catamphetamine** [comment]
@johnny-cit It's still not clear why don't you style `.react-phone-number-input__country` directly.
