### ISSUE TITLE
Flag pulled down a bit

### ISSUE THREAD

**Issue by rawadrifai** [catamphetamine/react-phone-number-input#307]
Hello, the country flag is pulled down a bit when I select a country.
I'm trying to fix that, or hide the select border. Can you help pls?

![image](https://user-images.githubusercontent.com/24530625/71315847-3a5b4b80-241b-11ea-8c53-63e4170a7378.png)

**Comment by catamphetamine** [comment]
See if setting something like `line-height: 0` on `.react-phone-number-input__country` fixes that.

**Comment by dave-grix** [comment]
> Hello, the country flag is pulled down a bit when I select a country.
> I'm trying to fix that, or hide the select border. Can you help pls?
> 
> ![image](https://user-images.githubusercontent.com/24530625/71315847-3a5b4b80-241b-11ea-8c53-63e4170a7378.png)

@rawadrifai, just out of interest, how have you styled the inputbox to resemble to the material-ui theme? I am struggling with it!

**Comment by rawadrifai** [comment]
This is how I have it @dave-grix 

```
<Form.Field>
            <PhoneInput
              id="phone_number"
              className="signup-phone-field"
              placeholder="Phone Number"
              value={this.state.phone_number}
              onChange={this.handlePhoneChange.bind(this)} />
</Form.Field>
```

**Comment by catamphetamine** [comment]
@dave-grix 
> just out of interest, how have you styled the inputbox to resemble to the material-ui theme? I am struggling with it!

First option: pass `numberInputComponent={MaterialUIInputComponent}`.
Second option: pass `inputStyleReset` property to prevent the library from applying decoration styles to the `<input/>`, and then style the `<input/>` manually as a material UI one.

**Comment by AmruthjithSunil** [comment]
> See if setting something like `line-height: 0` on `.react-phone-number-input__country` fixes that.

where to set it?

**Comment by catamphetamine** [comment]
on `PhoneInputCountry` somewhere.
Use DevTools.
Experiment.
