### ISSUE TITLE
Set Default Country when user clears the input field

### ISSUE THREAD

**Issue by shubhambatra** [catamphetamine/react-phone-number-input#309]
Hi,

I found one case. If I set **country** code and **display​Initial​Value​As​Local​Number**  is true, then it works fine. 
[demo](http://catamphetamine.github.io/react-phone-number-input/)
```
<PhoneInput
  displayInitialValueAsLocalNumber
  value={value}
  onChange={setValue}/>
```

If  user enter + in the input field then it takes first values as country code. Now If I clear the value in the input field it shows the international icon.

I want to show the country icon instead of the international icon when the user clears the value.

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@3.0.11` with the fix.
In v3 it's `defaultCountry` property.

**Comment by shubhambatra** [comment]
Thanks, It Working.

**Comment by shubhambatra** [comment]
@catamphetamine I found one more issue. If first, we are passing an empty string through the  props and then we are passing some value like 876545678 at that time also it is converting flag into the international format.

**Comment by catamphetamine** [comment]
@shubhambatra `value` is only valid when it starts with a `+`.

**Comment by shubhambatra** [comment]
@catamphetamine Is there any way if the value is invalid it doesn't show international Icon.
It only shows default country icon if the value is invalid.

**Comment by catamphetamine** [comment]
No

**Comment by shubhambatra** [comment]
Can I add this functionality? I will love to contribute.

**Comment by catamphetamine** [comment]
If value doesn’t start with a + then the + is prepended to value: 1234 ->
+1234.
+1234 is international number, therefore country is reset: otherwise the
user would think that the number still corresponds to the selected country
which isn’t true.
If you want to pass a national number, prepend a country code to it, and a +

**Comment by shubhambatra** [comment]
currently, I am doing the same thing. but my requirement is sending numbers without +. that why I have encountered this problem. 
If this is an invalid scenario that's fine.
Thanks for your support.

**Comment by tabrizh** [comment]
I am passing "+" and it works fine before the user starts typing. When the user types first it identifies the country and changes the flag as it supposed to do. But whenever the user presses backspace the application breaks with a huge error message saying "Unknown country: undefined". Everything works fine if I pass the defaultCoultry prop, but in my case I do not want to pass the defaultCountry, it should be international first
