### ISSUE TITLE
Failed prop type: The prop `country` is marked as required in `CountryIcon`, but its value is `undefined`.

### ISSUE THREAD

**Issue by DinAlla** [catamphetamine/react-phone-number-input#312]
Hello. 
I'm use PhoneInput with Field from react-redux and have error. 

```js
<Field component={PhoneInputWrapper} />
```

```js
// it's PhoneInputWrapper
// ...
  const phoneValue = input.value;
   const onPhoneInputChange = value => {
        if (input) {
            input.onChange(value || '');
        }
   };

   const onFocus = () => {
        if (input) {
            input.onFocus(input.value);
        }
    };
    const onBlur = () => {
        if (input) {
            input.onBlur(input.value);
        }
    };

<PhoneInput value={phoneValue}
                        onBlur={onBlur}
                        onFocus={onFocus}
                        onChange={onPhoneInputChange}
            />
```

In docs I see that prop country is not required, but If I write '+3' (only this) I have error message  in console.
![image](https://user-images.githubusercontent.com/22967411/72152176-4d7a8f00-33bb-11ea-9fe8-06464c35ba7e.png)

![image](https://user-images.githubusercontent.com/22967411/72152228-6be08a80-33bb-11ea-8a6f-0f7d72051925.png)

Thank you for help.

**Comment by catamphetamine** [comment]
Released `react-phone-number-input@3.0.13` with the fix.

**Comment by DinAlla** [comment]
@catamphetamine 
![image](https://user-images.githubusercontent.com/22967411/72152582-7e0ef880-33bc-11ea-853a-4474a51733da.png)

**Comment by catamphetamine** [comment]
Do `npm install react-phone-number-input@latest` or `yarn add react-phone-number-input@latest`.
