### ISSUE TITLE
Value prop returns "undefined" rather then passed onChange value.

### ISSUE THREAD

**Issue by diederikeen** [catamphetamine/react-phone-number-input#313]
Hi there,

I've recently upgraded to version 3.09. I have a search input that triggers the `onChange()` `onUpdate()`, which seems to work properly, but it rerenders again with the `value` prop undefined, which causes the component to crash.

I've downgraded back to version 2.5.1 and it didn't happen on that version

[image](https://imgur.com/a/agReJYg)

**Comment by catamphetamine** [comment]
It's not clear what you mean.

**Comment by diederikeen** [comment]
Sorry, let me try to be more clear.
In the `countrySelectComponent`  I get a few props: `onChange` and `value`.

If I trigger the `onChange` with a new value, lets say 'CA' for Canada, the component rerenders. But the value I get passed as a prop is undefined instead of the 'CA'.

**Comment by catamphetamine** [comment]
You may provide an online demo, otherwise it's not clear.

**Comment by catamphetamine** [comment]
I guess I get what you mean: `value` didn't update in your case.
Well, what can I say: the default component's working.
You could start with this code, and then modify it:

```js
import React, { useCallback, useMemo } from 'react'
import PropTypes from 'prop-types'

export default function CountrySelect({
	value,
	onChange,
	options,
	...rest
}) {
	const onChange_ = useCallback((event) => {
		const value = event.target.value
		onChange(value === 'ZZ' ? undefined : value)
	}, [onChange])

	const selectedOption = useMemo(() => {
		for (const option of options) {
			if (option.value === value) {
				return option
			}
		}
	}, [options, value])

	// "ZZ" means "International".
	// (HTML requires each `<option/>` have some string `value`).
	return (
			<select
				{...rest}
				value={value || 'ZZ'}
				onChange={onChange_}>
				{options.map(({ value, label, divider }) => (
					<option
						key={value || 'ZZ'}
						value={value || 'ZZ'}>
						{label}
					</option>
				))}
			</select>
	)
}

CountrySelect.propTypes = {
	// A two-letter country code.
	// E.g. "US", "RU", etc.
	value: PropTypes.string,

	// Updates the `value`.
	onChange: PropTypes.func.isRequired,

	// `<select/>` options.
	options: PropTypes.arrayOf(PropTypes.shape({
		value: PropTypes.string,
		label: PropTypes.string,
		divider : PropTypes.bool
	})).isRequired
}
```

**Comment by EWamsley** [comment]
I'm having a similar error

```typescript
import PhoneInput from 'react-phone-number-input';
<PhoneInput
    defaultCountry="us"
    onChange={this.doSomething}
    value={this.props.value}
/>
```

with the doSomething method being:
```typescript
doSomething = (value: any) =>
{
    console.error("Change value: ", value);
}
```

And this is what it prints into the console:
```
Change value: undefined
```

**Comment by EWamsley** [comment]
Actually figured out my issue, was doing `defaultCountry="us"` instead of `defaultCountry="US"`
