### ISSUE TITLE
Slow validate USA phone

### ISSUE THREAD

**Issue by DinAlla** [catamphetamine/react-phone-number-input#315]
Hi!
I have this code:
`<PhoneInput value={phoneValue}
                            onBlur={onBlur}
                            onFocus={onFocus}
                            onChange={onPhoneInputChange}
                />`

If I try to input number - data validate and I see country. Example:
![image](https://user-images.githubusercontent.com/22967411/72330769-25937000-36c8-11ea-8eed-f9fcf98624b9.png)

But when I try to input USA number, I see this:
![image](https://user-images.githubusercontent.com/22967411/72330881-52478780-36c8-11ea-89e9-022937720563.png)

And only after input full number I see country flag:
![image](https://user-images.githubusercontent.com/22967411/72330933-67bcb180-36c8-11ea-9236-3d24c9b3555b.png)

How I can see USA flag after input first part of number (I know that I can use country or default country, but I want to see code in input "+1..." and if I use it (country or default country) I can't see code in input - in value I have, but it's not I need)?

**Comment by catamphetamine** [comment]
See the bug reporting instructions
https://github.com/catamphetamine/react-phone-number-input#bug-reporting
If the demo's behavior is different from Google's demo, then reopen this issue.

**Comment by catamphetamine** [comment]
https://libphonenumber.appspot.com/phonenumberparser?number=%2B12134454215
Until the last digit is input:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B1213445421
No region, so this is expected.
