### ISSUE TITLE
Guam phone number gets munged if flag is selected first.

### ISSUE THREAD

**Issue by adamjaffeback** [catamphetamine/react-phone-number-input#316]
## Summary
Thanks for this project. You're really doing good work.

We are using `2.4.0` and have experienced a bug where Guam's area code duplicates during entry. The example phone number is `671-789-1421`. The issue also exists in the demo.

## `libphonenumber` passes

I checked this number against Google's `libphonenumber` demo page and the result meets the expectations for formatting: https://libphonenumber.appspot.com/phonenumberparser?number=6717891421&country=GU.

## Expected

Expected:
1. Select Guam from the flag list
2. Enter Guam phone number 671-789-1421
3. Guam phone number formats like any other American number (671) 789-1421

## Actual
Steps to reproduce in [demo](http://catamphetamine.github.io/react-phone-number-input/):
1. Select Guam from the flag list
2. Enter Guam phone number 671-789-1421
3. Guam's area code is duplicated 1-671-1671-...

### Demo Screencast

https://www.loom.com/share/4fbf0d6dc24448f69fde914ec509c5d0

Interestingly, if you delete the number back to the 671 area code and enter the number again, the number formats correctly. 🤷‍♂ 

### Our Component

For our setup with `react-phone_number-input`, we're seeing the issue much sooner with the country defaulted to US, and international set to false:

![Screen Shot 2020-01-16 at 11 35 04 AM](https://user-images.githubusercontent.com/8163408/72556832-5accc900-3854-11ea-936e-754ef23caa4b.png)

### Our Storybook Screencast

https://www.loom.com/share/ee4418922af146b9bd703cca6d6405b7

**Comment by catamphetamine** [comment]
Hi.
This is a good detailed bug report, and it seems that this is the long-known bug in `libphonenumber-js` which I haven't fixed yet:
https://github.com/catamphetamine/libphonenumber-js/issues/318
I was planning to look into it before 2020, but some things kept me busy.
I'll most likely look into it this month.

**Comment by adamjaffeback** [comment]
Thanks Nikolay!

**Comment by catamphetamine** [comment]
Fixed in `react-phone-number-input@3.0.17`.
