### ISSUE TITLE
[Accessibility] The screen reader is not reading the error message information when empty phone number is provided

### ISSUE THREAD

**Issue by mayukh-ms** [catamphetamine/react-phone-number-input#318]
The narrator doesn't read the error message, if empty or invalid phone number is provided.

**Package version:** 2.3.5
**OS version:** Window 10
**Browser:** Microsoft Edge 44.18362.1.0
**Screen reader:** Narrator

**Comment by catamphetamine** [comment]
Hi.
I've released v3 of the library.
See if the demo works, and if not — specify a more detailed description of the issue you're having.
