### ISSUE TITLE
[Accessibility] Talkback focus moves to the "Country" combo box twice

### ISSUE THREAD

**Issue by mayukh-ms** [catamphetamine/react-phone-number-input#322]
Talkback focus moves to the "Country" combo box twice.

**Environment Details:** 
**Mobile :** Samsung S9
**Android version:** 9
**Browser used:** default browser

**Comment by catamphetamine** [comment]
Provide exact reproduction steps and more details on the issue, otherwise it won't do.

**Comment by catamphetamine** [comment]
Closing because it's not a critical bug and version `3.x` is the current one.
Also no clear reproduction instructions provided.
