### ISSUE TITLE
[ Accessibility ] Voice over is reading the unnecessary information when focus is on “Country” flag image

### ISSUE THREAD

**Issue by mayukh-ms** [catamphetamine/react-phone-number-input#324]
Voice over is reading the unnecessary information when focus is on “Country” flag image. The voice over is  reading all kinds of image dimension information multiple times.

**iOS version:** 12.4.1 
**Package version:** 2.3.5
**Browser used:** Default browser

**Comment by catamphetamine** [comment]
Yes, I've fixed that in v3 by adding `<title/>` to `<svg/>` icons.
You may reopen this if there're any related issues in v3.
