### ISSUE TITLE
Disabling country dropdown

### ISSUE THREAD

**Issue by reintroducing** [catamphetamine/react-phone-number-input#325]
Is it possible to pass `disabled: true` to the countrySelectProps? It does not seem to be, but we'd like to be able to disable it for users who are US only (and still show the flag) but if an international user comes to the site (we have an `isInternational` flag to identify them) we'd pass false to the disabled prop so that they can make a selection.

I don't see anywhere that it'd be possible to do that at the moment, so two questions:
1. Is it possible and I'm missing it?
1. If not, is this an enhancement you'd be able to add?

Thanks for your consideration.

**Comment by catamphetamine** [comment]
Published `react-phone-number-input@3.0.16`.

**Comment by reintroducing** [comment]
fantastic, thank you @catamphetamine!

**Comment by toninho** [comment]
In my case I need the opposite, So,  I think the same could be added for InputComponent, something like:

`<InputComponent 
    disabled={disabled || (numberInputProps && numberInputProps.disabled)}
    readOnly={readOnly || (numberInputProps && numberInputProps.readOnly)}
    ---
/>`

About about that?

**Comment by catamphetamine** [comment]
@toninho Why don't you want to simply pass `readOnly={true}` property?
