### ISSUE TITLE
Input emits undefined in onChange event when we clear input

### ISSUE THREAD

**Issue by shyamlohar** [catamphetamine/react-phone-number-input#326]
# Feature / Bug
onChange event emits undefined when we completely erase field. which caused a really weird bug, that when we submit the form it won't show error for phone input. 

When I dug in further I found out that error was there but formik's ErrorMessage component shows error only if the field is touched and formik will mark field touched on submitting only if it has some value. so the issue is due to setting value as undefined for some field. displaying validation gets messed up. I accept that the issue is more on the Formik side but will it be possible to change this behavior? so that we get an empty string instead of undefined on value change when there is no value? 

I can submit a PR if you want me to.

**Comment by catamphetamine** [comment]
> so the issue is due to setting value as undefined for some field.

No, the issue is formik not marking a field touched when a user edits its value.
