### ISSUE TITLE
Countries get sorted alphabetically

### ISSUE THREAD

**Issue by reintroducing** [catamphetamine/react-phone-number-input#329]
I wanted to move the US to the top of the select dropdown so its the first country that shows up. I pass it the new array with US as the first item but it looks like the countries get sorted alphabetically anyway. You can duplicate this by simply putting the countries array to `countries={['US', 'CA']}` and Canada will be first.

Is there a way to remove the sorting on that array so I can show which country I want first? I don't want to have to build a new, custom select just to do that.

**Comment by catamphetamine** [comment]
> Is there a way to remove the sorting on that array so I can show which country I want first? I don't want to have to build a new, custom select just to do that.

Yes, there's a property, `countryOptionsOrder`.
See the props docs.

**Comment by reintroducing** [comment]
perfect, thank you!
