### ISSUE TITLE
Setting value externally does not update component value

### ISSUE THREAD

**Issue by AlexReff** [catamphetamine/react-phone-number-input#331]
Using Phone Number without Country input, having a `value={value}` prop, updating `value` does not change the value in the component.

Example: https://codesandbox.io/s/silly-frost-2m8ff

**Comment by catamphetamine** [comment]
The sandbox you provided doesn't showcase anything like that.

**Comment by AlexReff** [comment]
It does. My function attempts to clamp the length of the phone number. You can type in any length phone number you want, and setValue doesn't appear to have any effect.

**Comment by catamphetamine** [comment]
This is a too complex of an example.
Provide a simple example where clicking a button changes the value.

**Comment by AlexReff** [comment]
I've updated that link to include a button example. The only complexity in my previous example was determining if there is a "+"/"+1" prefix on a string, and making sure the actual phone number was not longer than 10 digits.

Now, the button sets a random value, and you can see the input not changing.

**Comment by catamphetamine** [comment]
Your code behavior is incorrect: `value` should be in e.164 format.

**Comment by AlexReff** [comment]
Please look at my codesandbox again, the button code I provided was not in the correct format, but the onChange handler logic is.

You can now see what is happening in the console. Try to type in a valid US phone number, such as `7185551234`

If you attempt to keep typing after the 10th digit, you will see the value I am attempting to set in the console.

**Comment by catamphetamine** [comment]
Read your codesandbox: you're setting `value` in incorrect format.
`value` should be in e.164 format.

**Comment by AlexReff** [comment]
From console: `setting a trimmed phone number... +17185551234`

What about that is invalid?

**Comment by catamphetamine** [comment]
The button works.
I'm locking this issue.
