### ISSUE TITLE
Phone number input without country onChange does not update value

### ISSUE THREAD

**Issue by AlexReff** [catamphetamine/react-phone-number-input#332]
https://codesandbox.io/s/silly-frost-2m8ff

I'm not trying to be antagonistic, I'm not sure why you closed the last issue. You can clearly see that hitting the button works just fine. You can also see the exact same value being set in my handler (in console) and that it does not update.

This is a bug. The format is not the issue. You can see the format in the console, they are identical.

**Comment by catamphetamine** [comment]
Don't post duplicate issues.
Closing.
