### ISSUE TITLE
🇺🇸American flag icon in the readme does not match the icon actually used 

### ISSUE THREAD

**Issue by natomato** [catamphetamine/react-phone-number-input#340]
The icon from the readme starts and ends with a red stripe

https://raw.githubusercontent.com/catamphetamine/react-phone-number-input/master/docs/images/first-glance-local.png

The icon from the input when used does not start with a red stripe

https://github.com/catamphetamine/country-flag-icons/blob/master/3x2/US.svg

**Comment by catamphetamine** [comment]
Oh.
I guess the painter didn't care.
Upon looking at the actual flags, Greece, Myanmar and Uruguay had the same issue.
Fixed.
