### ISSUE TITLE
Customization props

### ISSUE THREAD

**Issue by Dima-Dim** [catamphetamine/react-phone-number-input#346]
Now all unrecognized components of props are passed as attributes to the DOM element and this causes problems. For example, you need to pass parameters to styled components, and naturally, these are not valid attributes for the DOM element and an error appears in the console. You need to be able to explicitly indicate that we are passing the component for the attributes of the DOM elements, and that it is just like properties for other uses.

**Comment by catamphetamine** [comment]
Duplicate
