### ISSUE TITLE
Demo Force international format

### ISSUE THREAD

**Issue by waltervanwoudenberg** [catamphetamine/react-phone-number-input#350]
Hello,

In the demo (Force international format): http://catamphetamine.github.io/react-phone-number-input/
On country select the input is pre-filled with the country code.

How can I achieve this?

Thanks in advance.

**Comment by catamphetamine** [comment]
What exactly do you want

**Comment by waltervanwoudenberg** [comment]
![Screen Shot 2020-04-14 at 14 11 54](https://user-images.githubusercontent.com/18394246/79223614-f670d400-7e59-11ea-8d93-a327b56706c8.png)

this

**Comment by catamphetamine** [comment]
The code sample is there.

**Comment by waltervanwoudenberg** [comment]
Yes but I have a custom country select and using that with the react-phone-number-input/input component

**Comment by catamphetamine** [comment]
There are such examples on the demo page.
It won't insert country calling code in the input itself.
