### ISSUE TITLE
Could you include locale/default.json again?

### ISSUE THREAD

**Issue by mgik544** [catamphetamine/react-phone-number-input#351]
`locale/default.json` was removed on v3.0.0.  That file was really useful for non-English speakers. 
There must be a reason to be removed but if possible would you consider to include the file again in next release?

**Comment by catamphetamine** [comment]
> That file was really useful for non-English speakers.

I don't think so.
It was mostly English.

> There must be a reason to be removed but if possible would you consider to include the file again in next release?

It won't be re-added.
