### ISSUE TITLE
iPhone Auto fill phone number replaces the phone code with the number only.

### ISSUE THREAD

**Issue by shirazz** [catamphetamine/react-phone-number-input#352]
**REPOST GITLAB ISSUE**

In iOS there is an option where the keyboard prompts with the phone number. In case of the International format being true and if we select the phone number, the existing country code in the input is erased and only number is added. Sharing a screen shot below for reference. In this case below where the expected input is +971 569 XXX XXXX it is +569 XXX. So the code is now not present.

![image](https://user-images.githubusercontent.com/1519700/80292332-1ad88480-8767-11ea-8c6c-1223439d7e9f.png)

**Comment by aryan-1911** [comment]
Hi ,I am facing a same issue and don't able to solve this . can anyone tell me what is the solution and why you closed this issue ?

**Comment by shirazz** [comment]
Add props
```
international={true}
countryCallingCodeEditable={false}
```
More details : https://gitlab.com/catamphetamine/react-phone-number-input/-/issues/4
