### ISSUE TITLE
Unable to add className to input

### ISSUE THREAD

**Issue by Groghall** [catamphetamine/react-phone-number-input#353]
First thank you for the awesome plugin. My issue is I am trying to add the form-control className to the input but I can't seem to get it to work.

I am using forward ref to assist in this, Any help you can give would be great

```js
let PhoneInputStyle = () => {
      return (
        <input
          className='form-control'
          National={value && formatPhoneNumber(value)}
          International={value && formatPhoneNumberIntl(value)}
          value={value}
          onChange={(value) => this.setState({ value })}
          useNationalFormatForDefaultCountryValue
          limitMaxLength
          autoComplete
          required></input>
      );
    };    
    PhoneInputStyle = React.forwardRef(PhoneInputStyle);
```

```js
<FormGroup>
                              <PhoneInput
                                inputComponent={PhoneInputStyle}
                                name='Phone'
                                
                                defaultCountry={countryTel}
                                countryOptionsOrder={[
                                  'GB',
                                  'US',
                                  'AU',
                                  '|',
                                  '...',
                                ]}
                                
                                flags={flags}
                                
                                // required
                              />
                              <small className='text-danger'>
                                {value &&
                                  (isValidPhoneNumber(value)
                                    ? undefined
                                    : 'Invalid phone number')}
                              </small>

                              <div className='invalid-feedback' />
                            </FormGroup>`

**Comment by catamphetamine** [comment]
> My issue is I am trying to add the form-control className to the input but I can't seem to get it to work.

No reason for it to not work.
See if `PhoneInputStyle` is being rendered.
If it is, then the component is working.

**Comment by Groghall** [comment]
Thanks for rapid response, sadly it does not. 
![image](https://user-images.githubusercontent.com/2420324/82669535-86612500-9c33-11ea-9579-1d5ead1cbeaa.png)

**Comment by Groghall** [comment]
I am unable to assign default country to options as options is not recognised. Gives me a parsing error when I use options?

`<PhoneInput
   inputComponent={PhoneInputStyle}
   countrySelectComponent={
       options: defaultCountry:{countryTel}
   }                                
   name='Phone'
   countryOptionsOrder={[
      'GB',
      'US',
      'AU',
      '|',
      '...',
  ]}
  flags={flags}
  />`

**Comment by Groghall** [comment]
All I want to do is pass the className - form-control to the input
