### ISSUE TITLE
Two repos, which is the correct one?

### ISSUE THREAD

**Issue by SCasarotto** [catamphetamine/react-phone-number-input#355]
Hey, A little while back this (https://github.com/catamphetamine/react-phone-number-input) repo went down for a bit and then returned. In between this repo on gitlab appeared https://gitlab.com/catamphetamine/react-phone-number-input appeared and that is what NPM is linking to. What repo is actually the one builds are being produced from?

**Comment by catamphetamine** [comment]
Hi.
Thx. Indeed, I've updated the readme of this repo to say that the main repo is on GitLab now.
