### ISSUE TITLE
Lib breaks on CodeSandBox

### ISSUE THREAD

**Issue by SCasarotto** [catamphetamine/react-phone-number-input#356]
It appears this library is breaking on run on CodeSandBox. However, it does seem to run in a normal build environment. 

Example: https://codesandbox.io/s/react-phone-number-input-breaks-codesandbox-example-pf32l

**Comment by catamphetamine** [comment]
Looks like there's some syntax issue when importing the component on codesandbox.io.
Whatever.

**Comment by catamphetamine** [comment]
FYI: https://stackblitz.com/ seems to work.

**Comment by SCasarotto** [comment]
Just wanted to follow up that this issue is now resolved. You can see here https://github.com/catamphetamine/react-phone-number-input/issues/356 that it was an import issue and CodeSandBox resolved it on their side.
