### ISSUE TITLE
Transfer styles over to StyledComponents

### ISSUE THREAD

**Issue by enahsor** [catamphetamine/react-phone-number-input#358]
This is my first attempt at contributing to OS. Can I move the current styles over to using styled components? I think this will improve maintainability.

**Comment by enahsor** [comment]
@catamphetamine  thanks for getting back to me. Instead of having the css separated from the components it is styling, I would make use of https://styled-components.com/ to move the styles for each component into the component itself.

**Comment by catamphetamine** [comment]
@enahsor Aaah, I see.
Well, personally, I'm not a fan of "CSS in JS" so I wouldn't merge such pull request, but you can create your own fork and do anything there, the difficult part would be maintaining it on your own though.
