### ISSUE TITLE
react-responsive-ui select - Cursor jumping to the end in the inputField while editing. 

### ISSUE THREAD

**Issue by Subha** [catamphetamine/react-phone-number-input#361]
```
import Phone from 'react-phone-number-input/react-responsive-ui';
```

This is the import that i am using in my application. I am using the select from the react-responsive-ui. 
We are facing an issue, the cursor is jumping to the end when editing inside the input field and found this import(react-responsive-ui) is causing this issue. If i change it to use the default select(import Phone from 'react-phone-number-input')  it all works fine.  

Herewith attaching gif file that explains the issue. 
![Phone_cursor_issue](https://user-images.githubusercontent.com/12513265/90290961-d4f61800-de4c-11ea-8f8d-b23783f9a400.gif)

I noticed that in your readme File you are using this select but i could not find a demo or an example of using react-responsive-ui in the latest versions.

![Screen Shot 2020-08-14 at 4 36 55 PM](https://user-images.githubusercontent.com/12513265/90290731-67e28280-de4c-11ea-9bc6-c03b34e11575.png)

Could you please assist me here to see if I am missing any styles or anything?

Thank you

**Comment by catamphetamine** [comment]
Hello.
This seems to be an old version because `react-phone-number-input` no longer comes with `/react-responsive-ui` export.
Caret jumping at the end used to be the default behavior: `smartCaret={false}`.
If `smartCaret={true}` property doesn't fix the issue then that would mean that there will be no fix for this one.

**Comment by Subha** [comment]
> Hello.
> This seems to be an old version because `react-phone-number-input` no longer comes with `/react-responsive-ui` export.
> Caret jumping at the end used to be the default behavior: `smartCaret={false}`.
> If `smartCaret={true}` property doesn't fix the issue then that would mean that there will be no fix for this one.

What a quick response!

I did update my application to use the new version( "react-phone-number-input": "3.0.25"), i am surprised that i did not get any error that this is not supported and the select works fine but with this cursor issue. I tried with smartCaret set to both false and true does not seem to help.

**Comment by catamphetamine** [comment]
@Subha There is no such export. See:
https://unpkg.com/browse/react-phone-number-input@3.0.25/

**Comment by Subha** [comment]
> @Subha There is no such export. See:
> https://unpkg.com/browse/react-phone-number-input@3.0.25/

l see my package lock pointing to two versions. 
"react-phone-number-input": {
      "version": "3.0.25" }
 "react-phone-number-input": {
          "version": "2.3.24"
          "requires": {
            "classnames": "^2.2.5",
            "input-format": "^0.2.2",
            "libphonenumber-js": "^1.7.25",
            "prop-types": "^15.7.2",
            "react-lifecycles-compat": "^3.0.4",
            "react-responsive-ui": "^0.14.177"}

Thank you for clarifying.

So we need to find another way to have a custom select?

**Comment by catamphetamine** [comment]
The library now doesn't use specifically `react-responsive-ui`'s select and instead provides a way for a developer to specify their own select component. See the docs or the demo.

**Comment by Subha** [comment]
Thanks for the quick response, i will take a look at the custom select.

**Comment by catamphetamine** [comment]
@Subha Maybe something like:

```js
import React, { useCallback, useMemo } from 'react'
import PropTypes from 'prop-types'
import Select from 'react-responsive-ui/commonjs/Select'

import 'react-responsive-ui/style.css'

export default function CountrySelect({
	value,
	onChange,
	options,
	...rest
}) {
	return (
		<Select
			label="Phone"
			value={value}
			onChange={onChange}
			options={options}/>
	)
}

```

**Comment by Subha** [comment]
This is not an issue but it is a question and I am sure you can help me.

I am trying to get the customSelect to work like how it was working in the older version.

<img width="746" alt="Screen Shot 2020-08-17 at 10 51 45 PM" src="https://user-images.githubusercontent.com/12513265/90464918-4e576a00-e0dc-11ea-8021-3d95a5a89455.png">

and the UI looks like the below: => the div with class = 'react-phone-number-input__icon' that holds the flag image is the child of span class -> 'rrui__select__selected-content'

<img width="77" alt="Screen Shot 2020-08-17 at 10 52 58 PM" src="https://user-images.githubusercontent.com/12513265/90464997-6e872900-e0dc-11ea-9a0a-48a559eb03a7.png">

With the latest version, I am passing the custom select(react-responsive-ui) with the flag like what you have in your examples :

```
             <Phone
              {...customProps}
              placeholder={placeholder ? placeholder : ''}
              defaultCountry={countryVal}
              smartCaret={true}
              ***countrySelectComponent={CountrySelectWithIcon}***
```
I am confused about this DOM arrangements that does not match the previous versions, the flag image icon is not in the right place:

![Screen Shot 2020-08-17 at 11 12 17 PM](https://user-images.githubusercontent.com/12513265/90466280-65e42200-e0df-11ea-832e-397a49cde948.png)

which ended up like the below:

![Screen Shot 2020-08-17 at 11 15 32 PM](https://user-images.githubusercontent.com/12513265/90466369-9f1c9200-e0df-11ea-84b4-ebd3ef510642.png)

I need the image(flag icon) to be part of this content span: ``` <span class="rrui__select__selected-content"> ```

Any suggestions please?

**Comment by Subha** [comment]
This is not an issue but it is a question and I am sure you can help me.
 
I am trying to get the customSelect to work like how it was working in the older version.
 
<img width="746" alt="Screen Shot 2020-08-17 at 10 51 45 PM" src="https://user-images.githubusercontent.com/12513265/90464918-4e576a00-e0dc-11ea-8021-3d95a5a89455.png">
 
and the UI looks like the below: => the div with class = 'react-phone-number-input__icon' that holds the flag image is the child of span class -> 'rrui__select__selected-content'
 
<img width="77" alt="Screen Shot 2020-08-17 at 10 52 58 PM" src="https://user-images.githubusercontent.com/12513265/90464997-6e872900-e0dc-11ea-9a0a-48a559eb03a7.png">
 
With the latest version, I am passing the custom select(react-responsive-ui) with the flag like what you have in your examples :
 
```
             <Phone
              {...customProps}
              placeholder={placeholder ? placeholder : ''}
              defaultCountry={countryVal}
              smartCaret={true}
              ***countrySelectComponent={CountrySelectWithIcon}***
```
I am confused about this DOM arrangements that does not match the previous versions, the flag image icon is not in the right place:
 
![Screen Shot 2020-08-17 at 11 12 17 PM](https://user-images.githubusercontent.com/12513265/90466280-65e42200-e0df-11ea-832e-397a49cde948.png)
 
which ended up like the below:
 
![Screen Shot 2020-08-17 at 11 15 32 PM](https://user-images.githubusercontent.com/12513265/90466369-9f1c9200-e0df-11ea-84b4-ebd3ef510642.png)
 
I need the image(flag icon) to be part of this content span: ``` <span class="rrui__select__selected-content"> ```
 
Any suggestions please? The last option for me is to try with normal html select tag and add the necessary styles to match it. Before i try that option wanted to check if i am missing something.
 
Many thanks again.

**Comment by catamphetamine** [comment]
You can provide an online demo somewhere on a website like codesandbox.io if you want someone to look at any issues.
Otherwise, you can still use the native <select/>: most people prefer the native one.

**Comment by Subha** [comment]
> You can provide an online demo somewhere on a website like codesandbox.io if you want someone to look at any issues.
> Otherwise, you can still use the native : most people prefer the native one.

Sounds better. I tried to come up with my issue in this sandbox. I have to comment out the class 'PhoneInputCountrySelect' else the dropdown does not show up. 

https://codesandbox.io/s/vigilant-ganguly-fidpr?file=/src/index.js

I am trying to match this dropdown behavior.

![Screen Shot 2020-08-18 at 10 10 48 PM](https://user-images.githubusercontent.com/12513265/90584055-b3c05f00-e19f-11ea-8afc-d5b7c03050b6.png)

Thank you Again.

**Comment by catamphetamine** [comment]
@Subha https://codesandbox.io/s/hardcore-frog-ti1rj?file=/src/CountrySelectWithIcon.tsx

**Comment by Subha** [comment]
> @Subha https://codesandbox.io/s/hardcore-frog-ti1rj?file=/src/CountrySelectWithIcon.tsx

That is such a quick response from you.. Wow! So it is the iconComponent. Great. It works now in my sandBox. 
Appreciate it. Thank you.
