### ISSUE TITLE
BUG with Force international format if the country code has more digits than one. 

### ISSUE THREAD

**Issue by andreas-richard** [catamphetamine/react-phone-number-input#365]
Hi,

I found a bug while react-phone-number-input. 
If I use a default country with a country code that has 2 digits in this case Sweden +46 or Denmark +45, and I try to delete the country code so the input value is "+" only. The input field resets to the default value. 
But it works if the default country only has one number in the countrycode like Russia +7
`<PhoneInput
  international
  defaultCountry="SE"
  value={value}
  onChange={setValue}/>`

**Comment by catamphetamine** [comment]
Not clear.
What exactly is you think a bug?
What exactly you think wouldn't be a bug in that case?

**Comment by andreas-richard** [comment]
Expected behaviour is that for this component
`<PhoneInput
    international
    defaultCountry="SE"
    onChange={setValue}
/>`
to behave as in the demo, i.e., international format should be enforced and defaulted to Swedish. When you have for example “RU” as default  country this works, you can delete “7” from “+7" and input whatever you want. If you default to Sweden (or any other country with a country code with more than a single number) however, you can delete “6” just fine from “+46", but if you try to delete the “4” after having deleted the “6", the input will revert back to “+46”. I setup this example that displays what I mean:

Swedish: 
![SE](https://user-images.githubusercontent.com/71700338/94426009-366c0f00-018d-11eb-87d2-a667d72d0280.gif)

After I delete the 4 it changes back to "+46" meaning I can't change countrycode to any other country that doesn't have "+4" in the begining

Ru: 
![GIF 2020-09-28 13-21-12](https://user-images.githubusercontent.com/71700338/94426205-821eb880-018d-11eb-8680-7c3f648bb5da.gif)

**Comment by catamphetamine** [comment]
So I guess you're using the "force international format" feature.
On the demo page, in the "Force international format" section, I can select Sweden and delete all digits of the country code by using Backspace.
So the bug doesn't seem to occur.

**Comment by andreas-richard** [comment]
It's not when you are selecting sweden in the dropdown it occurs, its when sweden or any country that has more than 2 digits in their country code is set as default in  "Force international format"

**Comment by catamphetamine** [comment]
Doesn't happen on the demo page.
