### ISSUE TITLE
Trying to make the country code readonly in ForceInternationalFormat

### ISSUE THREAD

**Issue by kash0296** [catamphetamine/react-phone-number-input#367]
Hi,

I am trying to display numbers in international format. When I select a country, the corresponding country code is displayed in the text field.
What I would like to achieve is this:

I want the country code to be displayed in the text field, but I don't want the country code value to be changed if i hit backspace or delete. The only way for me to change the country code would be for me to select the dropdown menu and select another country.

How can I accomplish this? 

Thanks.

**Comment by catamphetamine** [comment]
> I am trying to display numbers in international format. When I select a country, the corresponding country code is displayed in the text field.

It's not clear what exactly are you talking about.

**Comment by kash0296** [comment]
![Screenshot from 2020-10-08 13-52-17](https://user-images.githubusercontent.com/70874363/95433412-84db9380-096d-11eb-8b78-22368ca17546.png)

Like in this screenshot, I am trying to use the Force International Format Feature, in order to display a country code in the text field. What I am trying to do is make that country code non-editable. I don't want to be able to delete the +1 or any other country code with a backspace, or delete. The only way I can change that code of +1 to another number would be to select another country. When I enter my phone number, I only want to be able to change the number I am entering in, and the only way for me to change the country code would be to select it from the drop down. I hope my question is more clear now.

**Comment by catamphetamine** [comment]
@kash0296 Added `countryCallingCodeEditable={false}` property in `react-phone-number-input@3.1.2`.

**Comment by catamphetamine** [comment]
@kash0296 Demo: https://catamphetamine.gitlab.io/react-phone-number-input/

**Comment by kash0296** [comment]
Thank you so much for adding this feature!

**Comment by kash0296** [comment]
Hey @catamphetamine I tried running this, but the issue is when I hit backspace, it still deletes the country code. Thought i'd give you a heads-up. I used create-react-app to create an empty app and i used the component alone in it. 

import {useState} from 'react';
import PhoneInput from 'react-phone-number-input';

  function App() {
    const [value, setValue] = useState('');
    //const onBlur = (evt) => {
      //console.log(evt.target.value);
    //};
    return (
      <div className="App">
        <PhoneInput
          international
          countryCallingCodeEditable={false}
          defaultCountry="US"
          value={value}
          onChange={setValue}
        />
      </div>
    );
  }

export default App;

**Comment by kash0296** [comment]
Hey @catamphetamine  I tried the update, to check if the country code is non-editable. However what happens now is I can still delete the country code, unlike in the demo where it is uneditable. I used create-react-app to create a simple app and I tried the component out. I can delete the code, however the flag will not revert back to the international form or default country. When I enter a number, it displays the country code instead of the number I typed. 



import {useState} from 'react';
import PhoneInput from 'react-phone-number-input';

  function App() {
    const [value, setValue] = useState('');
    return (
      <div className="App">
        <PhoneInput
          international
          countryCallingCodeEditable={false}
          defaultCountry="US"
          value={value}
          onChange={setValue}
        />
      </div>
    );
  }

export default App;

Here's a screenshot for your reference. Thank you so much! 

![Screenshot from 2020-10-30 15-40-32](https://user-images.githubusercontent.com/70874363/97692823-4184c880-1ac6-11eb-8161-7f7c3351c3c1.png)

**Comment by kash0296** [comment]
Hey @catamphetamine I tried the update, to check if the country code is non-editable. However what happens now is I can still delete the country code, unlike in the demo where it is uneditable. I used create-react-app to create a simple app and I tried the component out. I can delete the code, however the flag will not revert back to the international form or default country. When I enter a number, it displays the country code instead of the number I typed.

import {useState} from 'react';
import PhoneInput from 'react-phone-number-input';

function App() {
const [value, setValue] = useState('');
return (



);
}
export default App;

Here's a screenshot for your reference. Thank you so much!
![Screenshot from 2020-10-30 15-42-19](https://user-images.githubusercontent.com/70874363/97692999-814bb000-1ac6-11eb-8709-601e5e12e2f1.png)

**Comment by svrtrandafir** [comment]
Hwy @catamphetamine , I have the same issue as @kash0296. Here is my code: 

 ```
<StyledPhoneNumberInput
                    disabled={isEditable}
                    placeholder="Enter phone number"
                    flags={flags}
                    value={phoneNumber}
                    onChange={handleChange}
                    defaultCountry="US"
                    limitMaxLength
                    international
                    internationalIcon={InternationalIcon}
                    countryCallingCodeEditable={false}
                    focusInputOnCountrySelection
                    id={id}
                />
```
- handleChange function only sets the value of phoneNumber

 I noticed that when selecting a country, the phoneNumber is updated to the country calling code (maybe it helps).

Thank you

**Comment by catamphetamine** [comment]
@kash0296 

> However what happens now is I can still delete the country code, unlike in the demo where it is uneditable.

If you provide an editable online demo then maybe I could look at it.

**Comment by kash0296** [comment]
@catamphetamine  hey, I will go about creating one on codesandbox. it just kept throwing an error when I tried to import your component, or any other one actually, saying unexpected identifier. I'll sort that one out and then share a link here.

**Comment by kash0296** [comment]
@catamphetamine  here's a link to a online demo. https://stackblitz.com/edit/react-ggyjb5

Check it out. Thanks!

**Comment by catamphetamine** [comment]
@kash0296 Indeed, in an online demo, it doesn't work.
Strange.
I'll have a look when I have some time.

**Comment by kash0296** [comment]
@catamphetamine  thank you so much.

**Comment by catamphetamine** [comment]
Fixed in `react-phone-number-input@3.1.5`.

**Comment by kash0296** [comment]
@catamphetamine  thank you so much. Everything looks good. Much appreciated.

**Comment by jitenderDikonia** [comment]
i was using this in nextjs + typescript
 
import PhoneInput, { CountryData } from "react-phone-input-2";

and this is work for me **countryCodeEditable={false}**
