### ISSUE TITLE
Accessibility: role="presentation" in <img>

### ISSUE THREAD

**Issue by ajotka** [catamphetamine/react-phone-number-input#368]
Hi! 

I can't pass WCAG AA 2.1 test because of `role="presentation"` in `<img class="PhoneInputCountryIconImg"`.
![image](https://user-images.githubusercontent.com/15144546/95964345-fea9cc00-0e08-11eb-9600-53f9db572981.png)

Validator: AXE v.4.6.1 (axe-core 4.0.2)

Issue info:
https://dequeuniversity.com/rules/axe/4.0/aria-allowed-role?application=AxeChrome

From [W3C Doc](https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/presentation/PresentationRoleExamples.html) about role="presentation":

> Be aware that the markup <img role="presentation" alt="non-empty alt text"…> is in fact contradictory: Declaring a role of presentation says that the image is for layout, is decorative and meaningless, whereas the non-empty alt text implies that the image is meaningful. It is recommended that authors instead use empty alt text (alt="") where they use role="presentation".

**Comment by catamphetamine** [comment]
See the related commit:
https://gitlab.com/catamphetamine/react-phone-number-input/-/commit/8ffdb0da6a04fe085133e5847a98a4f3b1b8cf24

A new version will be published in the near future.

**Comment by catamphetamine** [comment]
published `react-phone-number-input@3.1.1`
