### ISSUE TITLE
Passing onBlur as a prop to the component

### ISSUE THREAD

**Issue by kash0296** [catamphetamine/react-phone-number-input#369]
Hi,
Does the component support the use of the onBlur event instead of the onChange event? I pass props to the component like this      in my form: 
return(
      <PhoneInput
      international
      defaultCountry={this.state.defaultCountry}
      value={props.value}
      required={props.required}
      disabled={props.disabled}
      onChange={(value) => props.onChange(value)}
      className="form-control-phone"
      /> 
This works fine. However I would love to use onBlur instead of onChange if possible. If I try the following: 
return(
      <PhoneInput
      international
      defaultCountry={this.state.defaultCountry}
      value={props.value}
      required={props.required}
      disabled={props.disabled}
      onBlur={(value) => props.onBlur(value)}
      className="form-control-phone"
      /> 
Is it possible to use onBlur? When I was browsing the repository, I saw onBlur only being available to countryselect component and input component.

Thank you!

**Comment by catamphetamine** [comment]
`onBlur` is supposed to be passed directly to the `<input/>`.
