### ISSUE TITLE
UK Flag

### ISSUE THREAD

**Issue by vessoni** [catamphetamine/react-phone-number-input#370]
Hi Team,

Bug:
When typing +44 the flag does not show:
![image](https://user-images.githubusercontent.com/4910383/96995311-e5e69800-1525-11eb-9ab4-157788d9cc9f.png)

but selecting show.
![image](https://user-images.githubusercontent.com/4910383/96995362-fd258580-1525-11eb-96b0-de596dc74a8b.png)

**Comment by catamphetamine** [comment]
+44 is not just UK
