### ISSUE TITLE
Getting 3X Warnings "value is undefined" when deleting whole international number.

### ISSUE THREAD

**Issue by raimi6** [catamphetamine/react-phone-number-input#371]
React app (Typescript) in dev mode.

My setup
1) internacinal={true}
2) defaultCountry="RU"

`const [ value, setValue ] = useState<any>('+12133734253');`

`<PhoneInput
  international={true}
  defaultCountry="RU"
  value={value}
  onChange={setValue}/>`

Actions to replicate the problem(3x Warnings):
1) Delete whole number from input field.

![image](https://user-images.githubusercontent.com/7153091/97955629-4cce4180-1daf-11eb-8021-6d99ce57c854.png)

**Comment by catamphetamine** [comment]
If you provide an online demo then perhaps I could look at that

**Comment by catamphetamine** [comment]
I'll close this for now since there haven't been any other reports.
