### ISSUE TITLE
Add international to countryOptionsOrder

### ISSUE THREAD

**Issue by Florian54640** [catamphetamine/react-phone-number-input#374]
Hello,

With version 3.1.2 I can't put the international option in the countryOptionsOrder
I tried with undefined and "ZZ" but I got an error message saying it can't find the country code.

there is an exemple of my code : 
<PhoneInput
            international
            // flags={flags}
            defaultCountry="BE"
            labels={en}
            countryOptionsOrder={["BE", "FR", "LU", "NL", "|", "..."]}

I have an error if i put the undefined or "ZZ" before the "BE"
But i read is possible in this issues : https://github.com/catamphetamine/react-phone-number-input/issues/190

In addition I noticed another problem at the level of the demo (the example with the default country on "Force international format") if we enter a number then we delete it we fall on the international icon but in this case it is impossible to choose the first country from the list here Afghanistan

**Comment by catamphetamine** [comment]
See `react-phone-number-input@3.1.6`.

> With version 3.1.2 I can't put the international option in the countryOptionsOrder
I tried with undefined and "ZZ" but I got an error message saying it can't find the country code.

Added `"🌐"` option for "International".

> In addition I noticed another problem at the level of the demo (the example with the default country on "Force international format") if we enter a number then we delete it we fall on the international icon but in this case it is impossible to choose the first country from the list here Afghanistan

Fixed.

**Comment by Florian54640** [comment]
it's perfect thanks !!!
