### ISSUE TITLE
Allow defaultCountry to be extracted from initial value

### ISSUE THREAD

**Issue by andregoldstein** [catamphetamine/react-phone-number-input#378]
Hi there, I'm currently using the package with the `defaultCountry` prop set to "FR" as most numbers are French. However some numbers have different formats, eg an initial value for the component may be a UK number "+44.....".

```
import React, { useState } from "react";
import "react-phone-number-input/style.css";
import PhoneInput from "react-phone-number-input";
import fr from "react-phone-number-input/locale/fr";

export default function App() {
  // If number coming in from DB isn't French...
  const [phone, setPhone] = useState("+44788977366");

  return (
    <div className="App">
      <h1>Phone numbers</h1>

      <PhoneInput
        initialValueFormat="national"
        labels={fr}
        defaultCountry="FR"
        countries={["FR", "GB"]}
        value={phone}
        onChange={setPhone}
      />
      <p>{phone}</p>
    </div>
  );
}
```

<img width="546" alt="Screenshot 2021-03-23 at 15 58 56" src="https://user-images.githubusercontent.com/7061578/112167389-b335ee00-8bf0-11eb-8707-7de995828354.png">

Is there any way I can set `defaultCountry` to be updated to match the initial value? Or force an update to the correct flag?

Or failing that are there any utility functions perhaps to determine the countryCode from the number? I could then use this to run a `useEffect`

Many thanks!

https://codesandbox.io/s/phone-numbers-1l9pi?file=/src/App.js:0-628

**Comment by catamphetamine** [comment]
> Is there any way I can set defaultCountry to be updated to match the initial value? Or force an update to the correct flag?

Remove `countries` and see if it works.

**Comment by andregoldstein** [comment]
Thanks, unfortunately it doesn't.

**Comment by catamphetamine** [comment]
Hmm, looks like `+44 7889 77366` doesn't belong to any country.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B44+7889+77366&country=RU

What icon would you suggest the library show in such case?
Will "international" icon be appropriate?

**Comment by andregoldstein** [comment]
Thanks! You're absolutely right, apologies about that! When I add the extra digit all works as expected!

**Comment by catamphetamine** [comment]
The library could hypothetically detect when the initial `value` doesn't match any country, and then it could hypothetically pass that flag called `initialValueDoesNotMatchDefaultCountry` to country select, and then country select could hypothetically show something differently.

The `initialValueDoesNotMatchDefaultCountry` flag would be reset on any user input, or on any country selection. Resetting the `initialValueDoesNotMatchDefaultCountry` flag on any user input would still look weird: if the initial value was `+12345`, and then the user just appended `6` then it would show the flag of, say, France, even though `+123456` is still not a French number.

So, overall, UI-wise, it's not a trivial one.

I have still fixed a small edge use case though: https://gitlab.com/catamphetamine/react-phone-number-input/-/commit/779b130247b0ba25d1f7d7650530bba2bc8c2d03
Your demo doesn't show France now in the case you've described: 
https://codesandbox.io/s/phone-numbers-forked-8b1cy?file=/src/App.js

**Comment by andregoldstein** [comment]
That's awesome, thanks so much for speedy response 👍
