### ISSUE TITLE
Hide withCountryCallingCode when it's empty

### ISSUE THREAD

**Issue by francescootori** [catamphetamine/react-phone-number-input#384]
Hi guys, I hope you all are well and safe.

I would like to know if there's a way to hide the **withCountryCallingCode** when it's empty. 
I'm using the yup/yup-phone to validate my form, but it doesn't ignore the country prefix number. 

Could you please help me?

Thank you so much. That's an amazing plugin.

**Comment by catamphetamine** [comment]
As one can clearly see on the demo page, `value` is undefined when the input is empty.
