### ISSUE TITLE
Validates incorrect number like 12345.... for Indian number

### ISSUE THREAD

**Issue by maazakn** [catamphetamine/react-phone-number-input#386]
It is accepting 123456... as a valid number for country code of +91. Although it is not a valid number.

**Comment by catamphetamine** [comment]
Provide more details

**Comment by This-is-MaazAhmed** [comment]
It is not working accurately with Indian Numbers, starting with the country code of +91. It only checks the number length but not the number itself. 

For example, it accepts some random numbers like,

- 123459876
- 199212345

as a valid number.

**Comment by catamphetamine** [comment]
What do you mean by “ it accept s some random numbers ”

**Comment by b-hexsoul** [comment]
> It is not working accurately with Indian Numbers, starting with the country code of +91. It only checks the number length but not the number itself.
> 
> For example, it accepts some random numbers like,
> 
> * 123459876
> * 199212345
> 
> as a valid number.

How exactly are they not valid?
