### ISSUE TITLE
React-phone input error in formik while using handlechange

### ISSUE THREAD

**Issue by Rahulr2001** [catamphetamine/react-phone-number-input#400]
class Createemp extends Component{

  
render(){
    return(
        <div className="empcontainer">
    <Formik
    >
{
 
      ({ handleSubmit, handleChange, values, errors }) =>
       (
      <form className="container" onSubmit={handleSubmit}>
        <div >
        

          <PhoneInput
          name='phone'
          country={'us'}
          value={values.phone}
          onChange={handleChange}
         />
          <small  >{errors.phone}</small>

          
        </div>
        <button
        type='submit'
        className="empcreate"
          //onClick={this.createRestaurant}
          //onClick={window.location.reload()}
        ><span className="text">Create</span></button>
      </form>
          
    )}
    </Formik>
        </div>
    )
}

}

  

 export default Createemp;

...**value which i enter in the input is always empty..even i entered a mobile...the on change event didnt work for me to give the value to values.phone for my validation**

**Comment by catamphetamine** [comment]
onChange returns a value.
handleChange likely expects an event.

**Comment by catamphetamine** [comment]
How to change a value to an event? Strictly speaking, there’s no such way.
Google for “create change event from value” or something like that. Or use
another form library.

**Comment by catamphetamine** [comment]
https://github.com/catamphetamine/react-phone-number-input/issues/298#issuecomment-557779359
Maybe that
