### ISSUE TITLE
Remove border from Phone Number Input.

### ISSUE THREAD

**Issue by visibleajay** [catamphetamine/react-phone-number-input#402]
Would like to apply custom styling to remove border from phone number input when it is in focus and when it's used as normally.

<img width="263" alt="Screenshot 2022-03-14 at 7 23 10 PM" src="https://user-images.githubusercontent.com/13945951/158186155-80e9132a-c0d9-43c4-a785-3fe07a5c2276.png">

Though, was able to achieve border as 0 on normal state with
```
.PhoneInput .PhoneInputInput {
  border: 0;
}
```
but border soon pops out when input element is in focus.

**Comment by catamphetamine** [comment]
There's no `border` CSS rule.

https://github.com/catamphetamine/react-phone-number-input/blob/master/style.css

**Comment by visibleajay** [comment]
I have disabled most of the `css` but the `border fill` is still present. Please guide in removing the `border fill` from the active component.

**Comment by catamphetamine** [comment]
Then you're on your own
