### ISSUE TITLE
any way to provide the default or initial value while able to hide the country code.

### ISSUE THREAD

**Issue by visibleajay** [catamphetamine/react-phone-number-input#403]

**Comment by catamphetamine** [comment]
What?

**Comment by visibleajay** [comment]
We are using PhoneInput with formik, though we are able to access the phone number, we are storing it without country code. While editing the field we again need to pass it back to PhoneInput. Is their any way to pass phone number without country code and still able enjoy the formatting of PhobeInput.

**Comment by catamphetamine** [comment]
Not clear what you mean.
Provide screenshots or something.

**Comment by visibleajay** [comment]
Sharing screenshot.

Screenshot1:- Display a card with normal phone number.
<img width="368" alt="screenshot1" src="https://user-images.githubusercontent.com/13945951/159845550-b38f1730-55ca-4a5f-b397-e29ea207b7b6.png">

Screenshot2:- On editing the same card, a modal is opened with already filled information. Number contains a country code which we wants to remove.
<img width="430" alt="screenshot2" src="https://user-images.githubusercontent.com/13945951/159845592-b8a51a6d-20a3-44d4-afd1-1f6892a37e7f.png">

Screenshot3:- On a single backspace, the number gets correctly formatted. 
<img width="446" alt="screenshot3" src="https://user-images.githubusercontent.com/13945951/159845659-5ea50325-0124-4efa-932c-5516e9efac20.png">

**Comment by catamphetamine** [comment]
> Display a card with normal phone number.

What's a "normal" phone number.
There's no such thing.

> Please let me know if any more information is needed.

It's not clear what exactly you want.
