### ISSUE TITLE
parsePhoneNumber not detecting all countries

### ISSUE THREAD

**Issue by SourceCipher** [catamphetamine/react-phone-number-input#404]
For some reason a lot of numbers are not detecting the country even when selecting the country. For example GB number is not being detected and other countries as well while some countries are detected even with 3 numbers.

![image](https://user-images.githubusercontent.com/351018/160390282-5b768206-fe18-43b1-8613-4f02635f4cda.png)

**Comment by catamphetamine** [comment]
See https://github.com/catamphetamine/react-phone-number-input#bug-reporting
