### ISSUE TITLE
Floating label support

### ISSUE THREAD

**Issue by ag288** [catamphetamine/react-phone-number-input#425]
I would just like to know if the react-phone-number-input component supports floating form labels. My registration form uses a theme for floating labels which must be positioned on top of the input if the input has a value, please refer images and code attached

this is my code that enables floating labels

```
const activeLabelStyles = {
    transform: 'scale(0.85) translateY(-24px)',
}
export const theme = extendTheme({
    components: {
        Form: {
            variants: {
                floating: {
                    container: {
                        _focusWithin: {
                            label: {
                                ...activeLabelStyles,
                            },
                        },
                        'input:not(:placeholder-shown) + label, .react-phone-number-input + label, .chakra-react-select--has-value + label, .chakra-select__wrapper + label, .react-date-picker + label':
                        {
                            ...activeLabelStyles,
                        },
                        label: {
                            top: 0,
                            left: 0,
                            zIndex: 2,
                            position: 'absolute',
                            backgroundColor: 'white',
                            pointerEvents: 'none',
                            mx: 3,
                            px: 1,
                            my: 2,
                            transformOrigin: 'left top'
                        },

                    },
                },
            },
        },
    },
})
```

Floating label example
<img width="598" alt="image" src="https://github.com/catamphetamine/react-phone-number-input/assets/56507642/e9a459ba-0d74-4c3e-afd7-c57e0edde44b">

filled field

<img width="755" alt="image" src="https://github.com/catamphetamine/react-phone-number-input/assets/56507642/ededc3e9-252a-4d9a-b4e8-091f71f89d51">

**Comment by catamphetamine** [comment]
Hi. This component doesn't have any labels but it supports passing a custom input component that could, in turn, support "floating labels" feature. See `inputComponent` property in the readme.

**Comment by ag288** [comment]
Thank you for the quick response. An example would be helpful, if possible

**Comment by catamphetamine** [comment]
@ag288 Currently there're no examples or demos of using a custom `inputComponent`. The only info is what's in the readme. I guess it requires some level of expertise.

**Comment by ag288** [comment]
Isn't this library developed and maintained by you? Or are there any other developers you can put me in touch with, who would be able to give me an idea of how the inputComponent prop is used? My problem is that i have to use two phone number fields in a single form. Thus , without labels it is impossible for the user to know what they are supposed to enter in each field.

**Comment by catamphetamine** [comment]
> Isn't this library developed and maintained by you?

What's that supposed to mean? Do you expect me to do your work for you?

**Comment by ag288** [comment]
No, that is not what I meant at all. Since you said there are currently no examples and that the only info available is what is in the readme, i was wondering if there was someone else behind this library who knew more about how to use the inputComponent prop. I didnt really understand what was written in the readMe, which is why i asked for an example. Since you created the library, would you be able to just show me how that prop can be used? a very simple example would suffice. Thank you, and my apologies if I sounded rude, that was not my intention at all. :)

**Comment by ag288** [comment]
> I'd explain my position as: if a person is qualified enough to understand how it works from the existing info in the readme, they could implement it themselves. In other case, they'd have to educate themselves first until they're able to understand how to do that because the task of customizing the input itself would be disproportionately complex for them to handle.

I totally understand and agree with that thought process. Thank you for the time and help, I'll see if anything works for me.
