### ISSUE TITLE
styling help

### ISSUE THREAD

**Issue by blackPeppper** [catamphetamine/react-phone-number-input#431]
Hi i am using tailwind and react but get conflicted when tired to style the input to be like this one
```jsx
      <div className="relative">
        <select
          id={props.lable.id}
          className="w-full appearance-none rounded-lg border px-4 py-2 pl-8 text-black shadow focus:border-[#305DAB] focus:outline-none"
        >
          {props.children}
        </select>
        <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center px-3 text-gray-700">
          <i class="fal fa-angle-down"></i>
        </div>
```

its rtl website
![image](https://github.com/catamphetamine/react-phone-number-input/assets/93441520/4370af36-d558-42c1-ac29-3252b657cbf2)

**Comment by catamphetamine** [comment]
Hi. Looks like this component doesn't support "rtl" feature. A workaround could be rendering "country select" and "phone input" as separate fields. That would mean creating a custom country select component and using `react-phone-number-input/input` component.

**Comment by blackPeppper** [comment]
@catamphetamine can give some examples

**Comment by blackPeppper** [comment]
thanks
