### ISSUE TITLE
Country code of +1

### ISSUE THREAD

**Issue by SibonisoNdlovu** [catamphetamine/react-phone-number-input#432]
Has anyone experienced an issue where country code is +1 and when adding the number that starts with 1 after country code, the number ends up removing a 1 and having 1 instead of 2 1's?
![Screenshot 2023-09-07 at 14 18 53](https://github.com/catamphetamine/react-phone-number-input/assets/43060555/e550d115-5084-40cb-9727-c01f4e031244)
![Screenshot 2023-09-07 at 14 19 00](https://github.com/catamphetamine/react-phone-number-input/assets/43060555/e9451152-b2a1-4628-94b7-7746d4041602)

**Comment by catamphetamine** [comment]
It's normal because `1` is a national prefix in those countries and some people erroneously input it in international numbers. Google does the same thing.
