### ISSUE TITLE
The country code is duplicated when you enter the number before +

### ISSUE THREAD

**Issue by Rekk1d** [catamphetamine/react-phone-number-input#437]
Hi @catamphetamine! When I put the cursor in front of the + and enter the phone number, the country code is duplicated.
smartCaret doesn't fix this problem
Demo: https://skrinshoter.ru/vNTg8KgpepN
Code: 
<PhoneInput
      onChange={onChange}
      value={defaultValue}
      countries={['RU', 'BY']}
      defaultCountry="RU"
      international
      addInternationalOption={false}
      className={styles.phone}
      countryCallingCodeEditable={false}
      focusInputOnCountrySelection={false}
      limitMaxLength
      {...rest}
    />

**Comment by catamphetamine** [comment]
published `react-phone-number-input@3.3.8`.
