### ISSUE TITLE
Is there a way to remove the "International" option when a defaultCountry is set?

### ISSUE THREAD

**Issue by michael5r** [catamphetamine/react-phone-number-input#438]
We specify a `defaultCountry` based on geolocation, so, for US users, the form looks like this:

![image](https://github.com/catamphetamine/react-phone-number-input/assets/3209660/8a61e1de-cf15-45b4-8a02-71e41700c770)

However, the user can still pick the `International` option in the dropdown which shows a really ugly icon (and is also an invalid value):

![image](https://github.com/catamphetamine/react-phone-number-input/assets/3209660/0d958364-818e-4865-bea5-dda6b0a8cd25)

Is there an easy way to get rid of the `International` option entirely?

**Comment by catamphetamine** [comment]
![image](https://github.com/catamphetamine/react-phone-number-input/assets/477167/e4258389-ed9a-4ed1-a6e0-5da3165ece00)
