### ISSUE TITLE
Redux Form - why does onBlur return unformatted phone number?

### ISSUE THREAD

**Issue by jonathanchrisp** [catamphetamine/react-phone-number-input#49]
## Overview

```
redux-form: 6.7.0
react-phone-number-input: 0.11.11
```

I'm using this component with `redux-form` and wondered why the `onBlur` event returns the unformatted number and why this differs from the `onChange` event. 

The code alludes to this being a [fix](https://github.com/halt-hammerzeit/react-phone-number-input/blob/master/source/input.js#L48) originally. If possible can you let me know why this is the case?

I'm working around this at present, I pass my own custom `onBlur` function which passes the current formatted number. I always want the formatted number to be stored in redux state.

**Comment by halt-hammerzeit** [comment]
`onChange`s behaviour is supposed to be equal to that of `onBlur`: it's being passed a non-formatted number in international format.
If for some reason it happens to be not the case then post the proof and reproduction steps.

**Comment by halt-hammerzeit** [comment]
The reson behind `onChange`s behaviour being equal to that of `onBlur` is because `redux-form` writes the `value` in `onBlur` too, so this fix was made specially for `redux-form`.

**Comment by jonathanchrisp** [comment]
@catamphetamine thanks for the quick comments and sorry for the delay in replying. 

Please see the following [example](https://codesandbox.io/s/1jPq518BR) as it will make a lot more sense after looking at the code. Open up the dev tools and you'll see the console logs from the onChange and onBlur events. 

The problem I have is that when you perform field level validation with redux form its called following the `onBlur` and `onChange` callbacks. Please also note that the field's redux form state value will be updated following the on blur callback.

In my example, the on blur callback value returns an invalid phone number when passed through the exported `isValidPhoneNumber` function. This means I show a validation error even though the number is technically valid (it's just missing its international extension).

So, following your last comments, the onChange and onBlur callback values don't match so this should be reopened as a bug. I think it should match the current onChange value.

In my example, I've commented out a workaround which simply takes the current value and passes this back.

Let me know your thoughts.

**Comment by catamphetamine** [comment]
Not understand.

```js
  const { placeholder, input, meta } = props;
  const { onBlur, onChange, value } = input;
  const { error } = meta

  return (
    <div>
      <Phone
        country="US"
        countries={['US', 'AU', 'GB']}
        placeholder={placeholder}
        onBlur={onBlurFn(onBlur)}
        //onBlur={onBlurWorkaroundFn(onBlur, value)}
        onChange={onChangeFn(onChange)}
        value={value}
      />
      {error}
    </div>
  );
```
What is `this.props.input` and why are you using `onBlur` and `onChage` from it.

**Comment by catamphetamine** [comment]
I suggest you do it like this instead:

```js

    <form onSubmit={handleSubmit}>
        <label>Phone</label>
          <Field
            name="phone"
            component={Phone}
            country="US"
            countries={['US', 'AU', 'GB']}
            placeholder="Enter phone number..."
            validate={validatePhoneNumber}
          />
    </form>
```

**Comment by catamphetamine** [comment]
And when I open Redux DevTools extension at the link above it says "No store found. Make sure to follow the instructions."

**Comment by catamphetamine** [comment]
Oh, nvm, it's working

**Comment by catamphetamine** [comment]
So, the only bug I see so far is this one:

```js
onChange +1
onChange +12
onChange +123
onChange +1234
onBlur 234
```

I.e. when entering a non-international phone number `onBlur` still has the local one

**Comment by catamphetamine** [comment]
Thx for the detailed bug report and the supplied demo.
The bug has been identified and the fix has been released.
