### ISSUE TITLE
Country Code

### ISSUE THREAD

**Issue by Subha** [catamphetamine/react-phone-number-input#51]
This is my scenario:

While rendering the Phone number component I set the value through props (value:3098765567). To make this as  a valid phone number in onBlur I have a check to for validation . 
```js
if (!isValidPhoneNumber(value)) {
 this.setState({isValid:false})
}else {
 this.setState({isValid:true})
}
```

I am getting a state isValid set to false. The isValidPhoneNumber is looking for a number with the country code. I need to get the country code US (+1) so i can add that to the value before i send it to the api call isValidPhoneNumber. 

Any suggestions?

Thank you

**Comment by jonathanchrisp** [comment]
Hey @Subha, I've already raised this issue in #49. If you are using `redux-form` you simply have to return the value in the redux state for the field e.g. 

```js
onBlur() {
  const {
    onBlur,
    value,
  } = this.props

  onBlur(value)
}
```

**Comment by Subha** [comment]
Thank you for your response, i also went through issue #49 . I need to validate and show a red box in my onBlur . 

With the input value : "3098765567" , when i onBlur the api (isValidPhoneNumber) validates against this value input value ("3098765567") and i am getting return false. In order to validate this rightly i need add the country code before i send the value to the validphone number api. I need a hook to get the country code ("+1").

**Comment by catamphetamine** [comment]
@Subha Don't know what did you mean exactly in your first message but if you're asking in which format should the value be then the library clearly states that it must be in international format.

**Comment by catamphetamine** [comment]
@jonathanchrisp And I don't know what do you mean either. You don't need to hack around anything when using `redux-form` because `onBlur` has been specifically implemented as part of this library to fix `redux-form` behaviour.

If you still think you're getting any issues with `redux-form` then you could explain them in detail here.

**Comment by catamphetamine** [comment]
@Subha 

> I need a hook to get the country code 

No you don't.

The `value` is always in international format therefore it's gonna be validated correctly using `isValidPhoneNumber(value)` function

**Comment by catamphetamine** [comment]
@jonathanchrisp I see your issue on `redux-form` and I'll comment there after looking at your case

**Comment by catamphetamine** [comment]
@Subha Your bug report has been confirmed – seems that `onBlur` returns a non-internatinal phone number which differs from `onChange`. Will be fixed.

**Comment by catamphetamine** [comment]
The fix has been released.
