### ISSUE TITLE
Country code - initial phone number value doesn't override the passed country code prop

### ISSUE THREAD

**Issue by jonathanchrisp** [catamphetamine/react-phone-number-input#52]
I've found an issue when initialising a form with an initial value and a country code. In my [example](https://codesandbox.io/s/68Opv6pZQ) I pass the following value prop for the phone: "+61434711722", this is an Australian number. I also pass the country prop: "US".

Simple example below:
```js
<Phone
  country="US"
  value="+61434711722"
/>
```

When the phone input is rendered we get the following bug: 

![screen shot 2017-07-21 at 5 07 49 pm](https://user-images.githubusercontent.com/406799/28452681-26715b10-6e37-11e7-9e0d-936bcd2bcb41.png)

The US country has been set and the existing number although Australian has been set as the number. If you remove the country prop in the example you'll see that this only works as expected so this is just a scenario that isn't covered.

I would expect that the phone number should be evaluated/parsed first and then the appropriate country code should override any country code passed.

I can work around this at present by only passing a country prop if no value is passed initially.

**Comment by catamphetamine** [comment]
Thx, the fix has been released
