### ISSUE TITLE
Enhancement - Inline styles?

### ISSUE THREAD

**Issue by jonathanchrisp** [catamphetamine/react-phone-number-input#53]
Raising this issue as an enhancement request.

It would be great to be able to pass inline styles to both the input and possibly the select. At present, we have the ability to pass a custom `inputClassName` prop but this isn't ideal as we have to create our own css file.

Just wondered what your thoughts on this would be?

**Comment by catamphetamine** [comment]
Use `inputStyle` and `selectStyle` properties in the latest release
