### ISSUE TITLE
Enhancement - remove dropdown arrow when input is disabled

### ISSUE THREAD

**Issue by jonathanchrisp** [catamphetamine/react-phone-number-input#54]
When the input is disabled the dropdown arrow next to the country flag is still visible. It would be great to remove this when in this state as the user can't select a country anyhow. Please see example below:

![screen shot 2017-07-24 at 12 26 21 pm](https://user-images.githubusercontent.com/406799/28505976-5bd93f30-706b-11e7-8403-91dd7801c06e.png)

In my example above, we have the concept of read-only fields so don't want the user to edit the value. I'm happy to do this change required. Just wondered whether this hasn't been done for some reason?

**Comment by catamphetamine** [comment]
Use `.rrui__select__arrow--disabled` CSS class in the latest release

```css
.rrui__select__arrow--disabled
{
  display: none
}
```
