### ISSUE TITLE
Country code not stripped after country change back from International

### ISSUE THREAD

**Issue by zimenskiy** [catamphetamine/react-phone-number-input#56]
### Problem
Country code is duplicated in original value when different countries's been selected after the `International` option.

### How to repeat
- Select a country (let it be `Vietnam` for example)
- Input phone number without country code (e.g. `912345678`, value will be **+84**`912345678`)
- Select `International`
- Select another country (let it be `Afghanistan`). Value will be **+9384**`912345678`, but expected **+93**`912345678`.
- Select again previously selected country (`Vietnam`). Value will be **+8484**`912345678`, but expected **+84**`912345678`.

![react-phone](https://user-images.githubusercontent.com/1793381/28528548-b1c760a4-7096-11e7-8eda-d99b91146965.gif)

The following scenarios work as expected:
- Vietnam => Afghanistan => Vietnam
- Vietnam => International => Vietnam
- Country A => Country B => Country C => Country A

**Comment by catamphetamine** [comment]
Aaah, I see what you mean.
Yeah, I didn't account for such a particular use case.
Ok, I'll add such a feature.

**Comment by catamphetamine** [comment]
Fixed in the latest release and in the demo.

**Comment by zimenskiy** [comment]
Thanx 👍
