### ISSUE TITLE
Tabindex for select when nativeExpanded is true

### ISSUE THREAD

**Issue by feliguez** [catamphetamine/react-phone-number-input#57]
The same way others inputs like `button` (who trigger a select) and phone number `input` have its own tabindex props, I would like have a tabindex prop on select when nativeExpanded is set to true. The reason is because I choose have the same nativeExpanded experience on desktop and mobile so when I'm tabbing on desktop the :focus is missing because is in that select but by default this input is hidden via opacity.

**Comment by catamphetamine** [comment]
Seems to be fixed in the latest release.
Reopen otherwise.

**Comment by feliguez** [comment]
Thanks, I can see you just commit an improvement. To test it I'll wait for npm update, now it has 0.11.18.
Thanks again.
