### ISSUE TITLE
national prefix should show when convertToNational=true

### ISSUE THREAD

**Issue by mbrevda** [catamphetamine/react-phone-number-input#60]
When using convertToNational it seems the national prefix (1 in north america, commonly 0 in Europe) is not displayed. It would seem that for users that prefer the national format, the national prefix should be displayed.

**Comment by catamphetamine** [comment]
According to the Google's `libphonenumber` library's behaviour it's expected
https://libphonenumber.appspot.com/phonenumberparser?number=12345678901&country=US

```
    <!-- United States -->
    <!-- Note the national prefix of US is the same as its country code, and when formatting phone
         numbers in the national format, it is not included. Therefore, we omit it here to make
         formatting consistent with the rest of the world. The same applies to all the
         countries/regions under NANPA -->
```

As one can see from the demo output the only result `libphonenumber` returns for a national number is the one without the national prefix so there seems to be no way to format national numbers in US with the national prefix not to mention that even if possible that would look weird I guess.

**Comment by mbrevda** [comment]
First of all, thanks for quick and patient reply. Its one of the things I love about this project!

You are correct: for NANPA number, the accepted convention is, indeed, without the national prefix. 

For other places, this is not always the case. For example, here is a [UK mobile number](https://libphonenumber.appspot.com/phonenumberparser?number=447777999999&country=GB). Notice that the "National format" includes a leading `0`:

<img width="434" alt="screen shot 2017-07-28 at 2 17 21 pm" src="https://user-images.githubusercontent.com/293004/28715239-a8aec546-739f-11e7-9843-ff00ec3afaf3.png">

However, [when given the value +447777999999](https://www.webpackbin.com/bins/-Kq7tERaY7-nY388_DtE), the leading `0` is not displayed:

<img width="724" alt="screen shot 2017-07-28 at 2 18 57 pm" src="https://user-images.githubusercontent.com/293004/28715328-047ce8da-73a0-11e7-8ee2-8466d07cc1bd.png">


Thanks!

**Comment by catamphetamine** [comment]
Indeed.
Fixed in the latest release.

**Comment by mbrevda** [comment]
Thanks!
