### ISSUE TITLE
International dialling code is hide on country change

### ISSUE THREAD

**Issue by sunr1ze** [catamphetamine/react-phone-number-input#61]
![phone-input](https://user-images.githubusercontent.com/17491675/28714392-f180eeba-739b-11e7-9d5f-819401e4d48b.gif)

Is there any option to show dialling code always?

**Comment by catamphetamine** [comment]
Did you mean the international country phone code?

**Comment by sunr1ze** [comment]
Yes, like +7 for Russia or +1 for United States

**Comment by catamphetamine** [comment]
Ok, fixed in the latest release

**Comment by sunr1ze** [comment]
Thank you for quick response :)
