### ISSUE TITLE
Some countries aren't automatically selected after entering the country code (Australia +61, United Kingdom +44, etc.)

### ISSUE THREAD

**Issue by Goca** [catamphetamine/react-phone-number-input#62]
![ss phone](https://user-images.githubusercontent.com/6407826/28923827-aea6161a-785f-11e7-9782-4c84aab0700e.gif)

Also, would it be possible to show the country code when the country is selected from the drop down even before the whole number is entered.

**Comment by catamphetamine** [comment]
Yeah, I guess that woul make sense. Will implement today.

**Comment by catamphetamine** [comment]
Released as `react-phone-number-input@0.12.5`

**Comment by Goca** [comment]
Thanks for fixing the second issue so fast :) but the first one is still not fixed - some countries aren't automatically selected after entering the country code (Australia +61, United Kingdom +44, etc.). Please see the screenshot

**Comment by catamphetamine** [comment]
Well because that's how it works: +44 is not just for UK, so it's not deterministic given just these dialing digits.
