### ISSUE TITLE
Different prop for inputClassName and selectClassName ?

### ISSUE THREAD

**Issue by badaz** [catamphetamine/react-phone-number-input#64]
Hi, thanks for your work! Is it possible to have a different className prop for the select part of the component and the input ? It seems like the inputClassName props is passed to both. For example I want to style the input with a colored background but if I pass the className via inputClassName prop, the whole select surronding the input gets the colored background too.

**Comment by badaz** [comment]
sorry I just found this https://github.com/catamphetamine/react-phone-number-input/issues/53

**Comment by badaz** [comment]
Is it possible to do the same with inputClassName and selectClassName ?

**Comment by catamphetamine** [comment]
`inputClassName` is both for the phone number `<input/>` and the autocomplete `<input/>`.
Clarify your question.

**Comment by badaz** [comment]
Ok, my bad, I was passing the same class name to the Phone component's className and to it's inputClassName prop, sorry about that
