### ISSUE TITLE
Countries not formatting

### ISSUE THREAD

**Issue by Subha** [catamphetamine/react-phone-number-input#65]
I might be missing something, need some help here:

few Countries like Germany are not getting formatted while I start typing:

For example: Germany phone number - **49218018560**. 

I see the international API should I add that API to format it? and why is it for some countries it does not format?

Formatting works well for India, US and Canada.

Any suggestions?

 <Phone
              {...customProps}
              placeholder={this.phonePH("Phone number")}
              country={countryVal}
              value={this.state.phone}
              disabled={disabled}
              international={false}
              onChange={phone => this.setState({phone})}
              onBlur={this.handleBlur}
            />

Thank you for the help.

**Comment by catamphetamine** [comment]
Give the exact steps and the reproduction instructions along with a link the Google's demo showing a different outcome.

**Comment by Subha** [comment]
Thank you for your response:

http://catamphetamine.github.io/react-phone-number-input/

Without Default country:
Formatting that works for USA:

1. I select USA as my country
2. I start typing 4047778888
3. While onKeyup i see the data/number gets formatted to (404) 777-8888

Formatting that does not work for United Kingdom:

1. Select United Kingdom
2. start typing 1632960204
3. Nothing gets changed onKeyup.

**Comment by catamphetamine** [comment]
What's the behaviour of Google's demo in the second case?

**Comment by Subha** [comment]
The same it does not change while Typing but I see the National label gets a formatted value.

**Comment by catamphetamine** [comment]
Give the hyperlink

**Comment by Subha** [comment]
Sorry - https://catamphetamine.github.io/libphonenumber-js/

**Comment by catamphetamine** [comment]
I see, this is another repo.
This issue is not for `react-phone-number-input`, it's for `libphonenumber-js`.
See the bug reporting guide.
https://github.com/catamphetamine/libphonenumber-js#bug-reporting
If you want to report a bug provide the link to the Google demo result showing a dirrefent output.

**Comment by Subha** [comment]
Thank you for the links.

I am able to get the format using

 value={formatPhoneNumber((this.state.phone), 'International' }

From the google libary for Country - Germany with input value: 345678933

https://libphonenumber.appspot.com/phonenumberparser?number=345678933&country=DE

I got the detailed result.
If we look on the 

**Formatted Results**

E164 format | +49345678933
**Original format | 345 678933**
National format | 0345 678933
International format | +49 345 678933

In order to get the Original format I do not see any matching parameter('Original') to pass to the formatPhoneNumber since the format accept only 

export function format(phone: TelephoneNumber, country: CountryCode, format: **'International' | 'International_plaintext' | 'National'**): string;

Any ideas?

**Comment by catamphetamine** [comment]
You were first talking about UK, now you're talking about Germany.
Provide the case for a single number.
Take number `x` and input it on the demo page:
https://catamphetamine.github.io/libphonenumber-js/
Then take the same number `x` and input it on Google's demo page:
https://libphonenumber.appspot.com/
(and provide a link to the result)
Then see if the two demos output different results.
If you think the results are different, post them here and clarify what's different.

**Comment by Subha** [comment]
Let me be more precise:

Issue #1:

In this demo page - (https://catamphetamine.github.io/libphonenumber-js/)  

1. I changed the country to US 
2. Under "**AS YOU TYPE**"  option -  I start typing 4067708897 (the number formats as I type) to **(406) 770-8897**
3. Now i change the Default Country to **_GB_** : start typing (2071234567) - The number is not formatted in (https://catamphetamine.github.io/libphonenumber-js/).

The google Demo Page result:

https://libphonenumber.appspot.com/phonenumberparser?number=2071234567&country=GB

Things that are different:

1. Validation is true
2. Phone number is formatted : I expect the result what I see in the Original Format from **formatting Results Tab** which is - 
**20 7123 4567**

I am I missing something?

I could not attach a video file to this to show what I am doing. 

Thank you again for this wonderful library.

**Comment by catamphetamine** [comment]
Ok, now I see what you mean.
Thx for the detailed bug report.
This isn't actually a bug.
Sure, it **should have** formatted the phone number in the "as you type" input field.
But if you look at the bottom of the Google demo page it's the same non-formatted phone number:
https://libphonenumber.appspot.com/phonenumberparser?number=2071234567&country=GB
So, if you really think that's a bug then you can report it in Google's `libphonenumber` repo.
This library is originally a port of Google's `libphonenumber` and therefore is expected to behave consistently with how Google's `libphonenumber` does.

**Comment by catamphetamine** [comment]
If you're wondering why's that so I suppose it's because national prefix `0` is mandatory for UK phone numbers (though I'm not from UK)

**Comment by Subha** [comment]
Thank you. Make sense! I did not notice the "AsYopuTypeFormatter Results" in the Google Demo Page.

Oh Yes if i type 0 as prefix to the UK phone number i see it is formatting, but validation is still False.

My requirement is to format when the user types in after selecting the Country. 

Now in order to get the **Orginal Format** like what is specified in the Google Demo  is there a way to achieve that?

I tried this API call on value attribute:
 value: formatPhoneNumber(this.state.phone, 'International') 

I am seeing the phone number formats to international format (+Country code). How do I avoid this?

Any suggestions?

**Comment by catamphetamine** [comment]
> to get the **Orginal Format** like what is specified in the Google Demo

I actually don't know where does Google demo page take that "Original" value from.
It doesn't tell, it seems to be some kind of a server-side thing, maybe non-javascript one.
I'm not planning to swap "as you type" formatter with any other formatter for this React component though.

> I tried this API call on value attribute:
value: formatPhoneNumber(this.state.phone, 'International')
I am seeing the phone number formats to international format (+Country code). How do I avoid this?
Any suggestions?

That's intended because that's what **International** format is about.

**Comment by Subha** [comment]
I do not expect the "as you Type" to change in your code since that the behaviour in google Demo.

I was wondering if FormatPhoneNumber can accept any other parameter for "Orginial Formatting" but you mentioned the Google Demo does that through some other javascript.

I will play with it.

Thank you Again.

**Comment by catamphetamine** [comment]
Well, there's `formatInOriginalFormat` method which hasn't been ported:
https://github.com/googlei18n/libphonenumber/blob/98cb04aced00f7cb1b2af7993edbc0e7610141ed/javascript/i18n/phonenumbers/phonenumberutil.js#L2098
I'll see if it should be part of this library

**Comment by catamphetamine** [comment]
Ok, I looked at that method and seems to me that the only thing it does differently is that it strips national prefix from the formatted phone number if the original value didn't have it.
I don't see a reason for the existence of this method though.

**Comment by Subha** [comment]
Yes that's what I plan to add another method to "remove the national code". 

But if you can accept one more parameter "original" as part of the library that would be great too.

Thank you for looking.

**Comment by catamphetamine** [comment]
And what would be the use case for such method?
Who even needs that?

**Comment by Subha** [comment]
I can only see my use case :) 
Were the user/app expects a formatted output for the country they have chosen (without preceding national code in the input). 

If there is not a need for that wonder why Google has provided that method - **formatInOriginalFormat**

**Comment by catamphetamine** [comment]
It's still not clear from your explanation why would anyone need such
function
