### ISSUE TITLE
change initial value with setState 

### ISSUE THREAD

**Issue by mohamedtijani** [catamphetamine/react-phone-number-input#67]
I do a setState in the then of a promise

`let shop = get("infos/shops/" + shopId);
    shop.once("value").then(
      snapshot => {
        self.setState({phone: snapshot.val().phone
      })
`

in render
`<Phone
           placeholder="Enter phone number"
           value={this.state.phone}
           onChange={value => this.setState({ phone: value })}
   />`

**Comment by catamphetamine** [comment]
Works for me in the demo
```js
					setTimeout(() => this.setState({ value: '+1 234' }), 1000)
```
