### ISSUE TITLE
Autofocus

### ISSUE THREAD

**Issue by BrRenat** [catamphetamine/react-phone-number-input#69]
I think every input must have autofocus. And you have focus() method. How i can call externally?
https://github.com/catamphetamine/react-phone-number-input/blob/f29a082038d20a5486e3c85a2131f28505d856df/source/input.js#L569

**Comment by catamphetamine** [comment]
`ref => this.input = ref`
`ref.focus()` (if you're not wrapping the component with various decorators)

Also one might consider `autoFocus` property.

**Comment by bradennapier** [comment]
This does not work - you use stateless functional components so refs do not work on this.

**Comment by catamphetamine** [comment]
> you

Who are you talking about/to

**Comment by leojh** [comment]
Hooks style:
```
  useEffect(() => {
    if (phoneInput.current) {
      setTimeout(() => {
        phoneInput.current.focus()
      })
    }
  }, [])

   <Phone
...
        ref={phoneInput}
   />
```

**Comment by catamphetamine** [comment]
@leojh So `autoFocus` property doesn't work or what?

**Comment by leojh** [comment]
I didn't see one? only a hook to .focus()

**Comment by catamphetamine** [comment]
> I didn't see one? only a hook to .focus()

In a comment above I wrote that "one could also consider using `autoFocus` property".
So you didn't even try it.

**Comment by catamphetamine** [comment]
https://caniuse.com/#search=autofocus

**Comment by catamphetamine** [comment]
On that page though they say it's not supported in iOS Safari.
So manual focusing is still a way.

**Comment by loxator** [comment]
> Hooks style:
> 
> ```
> const phoneInput = useRef(null)
> useEffect(() => {
>   setTimeout(() => {
>     phoneInput.current.focus()
>   })
> }, [])
> 
> <Phone
>   ...
>   ref={phoneInput}
> />
> ```

@leojh could you please expand on this example?  I have tried the following way

```
import React, { useEffect, useRef } from "react";

import PhoneInput from "react-phone-number-input";

const FocusedPhoneInput = ({ value }) => {
  const phoneInputRef = useRef(null);
  useEffect(() => {
    phoneInputRef.current.focus();
  }, []);
  return (
    <PhoneInput
      country="US"
      placeholder=""
      value={value}
       ...
      ref={phoneInputRef}
    />
  );
};

export default FocusedPhoneInput;
```

and then using this in a class component, but it isn't working

**Comment by leojh** [comment]
@loxator I'm still on `2.3`, will try upgrading and let you know

**Comment by Subha** [comment]
Hey

Sorry to respond in the closed thread. You have mentioned "we can try the autoFocus property", this did not work in chrome browser, should we add this manually? I am currently on version -"2.3.24" Thank you for your response.

<Phone
                {...customProps}
                country={countryVal}
                onCountryChange={this.countryChange}
                autoFocus={this.props.autoFocus} />

**Comment by Subha** [comment]
I also tried this in one of the sandbox and i don't see the input box being focused: 
https://codesandbox.io/s/admiring-davinci-kmlw2

import React, { useState, useRef, useEffect } from "react";
import PhoneInput from "react-phone-number-input";
import "react-phone-number-input/style.css";
import "./styles.css";

export default function App() {
  const [value, setValue] = useState();
  const phoneInputRef = useRef(null);
  useEffect(() => {
    phoneInputRef.current.focus();
  }, []);

  return (
    <div className="App">
      <PhoneInput
        placeholder="Enter phone number"
        value={value}
        ref={phoneInputRef}
        onChange={setValue}
      />
    </div>
  );
}

**Comment by catamphetamine** [comment]
@Subha 

> Sorry to respond in the closed thread. You have mentioned "we can try the autoFocus property", this did not work in chrome browser, should we add this manually? I am currently on version -"2.3.24" Thank you for your response.

Setting `autoFocus={true}` on a phone input component should work.
Doesn't it work in your case?
You can provide an online demo (for example, on codesandbox).

**Comment by catamphetamine** [comment]
> I also tried this in one of the sandbox and i don't see the input box being focused:

That's because you passed `focus`, not `autoFocus`.

**Comment by Subha** [comment]
Thank you for your response, I tried it with autoFocus={this.props.autoFocus} /> like i mentioned in my first comment

https://codesandbox.io/s/admiring-davinci-kmlw2

**Comment by Subha** [comment]
> @Subha
> 
> > Sorry to respond in the closed thread. You have mentioned "we can try the autoFocus property", this did not work in chrome browser, should we add this manually? I am currently on version -"2.3.24" Thank you for your response.
> 
> Setting `autoFocus={true}` on a phone input component should work.
> Doesn't it work in your case?
> You can provide an online demo (for example, on codesandbox).

https://codesandbox.io/s/admiring-davinci-kmlw2

**Comment by catamphetamine** [comment]
@Subha You still can't get it right.
First of all, where did camel case go?
Second, why are you passing `"true"` as a string.

**Comment by Subha** [comment]
I got it working.. I had two input box set to autoFocus and the last
won...Thanks again for your prompt response.
