### ISSUE TITLE
Validation: 11 digit Indian number validates to true

### ISSUE THREAD

**Issue by grahamlutz** [catamphetamine/react-phone-number-input#70]
It looks like the validation for Indian numbers continues to validate numbers with between 11-14 numbers.  The following screen shot is with a valid Indian number:

![screen shot 2017-09-06 at 12 54 50 pm](https://user-images.githubusercontent.com/12991947/30124403-0c4ffb74-9303-11e7-8d5e-263547739634.png)

The following is with an 11 digit (invalid) Indian phone number, which still has `isValid: true`

![screen shot 2017-09-06 at 12 55 21 pm](https://user-images.githubusercontent.com/12991947/30124465-4054c4cc-9303-11e7-80da-e25ee0f51eaa.png)

Then the following is the same situation for US numbers. First screenshot is a valid number with 10 digits with `isValid: true` and the second is an invalid number with 11 digits and `isValid: false`

![screen shot 2017-09-06 at 12 56 39 pm](https://user-images.githubusercontent.com/12991947/30124520-6c36a844-9303-11e7-92c4-efa339aa792f.png)

![screen shot 2017-09-06 at 12 56 47 pm](https://user-images.githubusercontent.com/12991947/30124521-6c474c6c-9303-11e7-8680-bd37304892c8.png)

**Comment by catamphetamine** [comment]
What's your exact question?

**Comment by grahamlutz** [comment]
Shouldn't 11 digit (not including country code) Indian numbers return `isValid: false`?

**Comment by catamphetamine** [comment]
I dunno.
What does the google demo say.

**Comment by catamphetamine** [comment]
Oh, I get it, once again, a bug report for another repo.
I'm gonna add this to the readme.
In a minute.

**Comment by catamphetamine** [comment]
See the updated readme:

https://github.com/catamphetamine/react-phone-number-input#bug-reporting

**Comment by grahamlutz** [comment]
It looks like google's result from `isValidNumber()` is `false`.  

![screen shot 2017-09-06 at 1 41 48 pm](https://user-images.githubusercontent.com/12991947/30126297-8e7881ba-9309-11e7-96f5-7027570a16fb.png)

**Comment by catamphetamine** [comment]
Ok, then the next step would be using the full metadata in `<PhoneInput metadata={require('libphonenumber-js/metadata.full.json')}/>`

**Comment by grahamlutz** [comment]
Got it, Thanks!

**Comment by grahamlutz** [comment]
So I've got that in place, and it's pulling it in but does't change anything.  This is what the props on our phone component looks like: 

![screen shot 2017-09-06 at 2 42 09 pm](https://user-images.githubusercontent.com/12991947/30128748-c6b7fd82-9311-11e7-96c5-db073d214c2c.png)

And this is what I am using to validate: 

```
handleBlur = (e) => {
    let phone = e.target.value;

    if (!isValidPhoneNumber(phone) && phone != "") {
      this.setState({isValid: false});
    }
    else {
      this.setState({isValid: true});
    }
};
```

Any other thoughts?

**Comment by catamphetamine** [comment]
Oh, man, I mislead you a bit on this one.
Actually, use 'isValidNumberCustom' with the full metadata as described in
'libphonenumber-js' readme.
