### ISSUE TITLE
tabIndex doesn't work

### ISSUE THREAD

**Issue by alicerocheman** [catamphetamine/react-phone-number-input#71]
Hi :)

I tried setting the tabIndex attribute so that the tab action activates the input, and it doesn't seem to work. Have you implemented it ?

Thanks

**Comment by catamphetamine** [comment]
Hmm, that's true, seems like a bug: `tabIndex` gets overwritten by `undefined`.
https://github.com/catamphetamine/react-phone-number-input/blob/e61780f5a10d47c347f3eb44af1475c9c9a6fb89/source/input.js#L958
Will fix.

**Comment by catamphetamine** [comment]
Try `react-phone-number-input@0.12.10`

**Comment by alicerocheman** [comment]
Great! It's all good, thanks!
