### ISSUE TITLE
Is valid state changes to true on 7th digit when entering US phone number.

### ISSUE THREAD

**Issue by GGantulga** [catamphetamine/react-phone-number-input#73]
Can you please take a look the issue?

http://catamphetamine.github.io/react-phone-number-input/
First example input: 
1. Change country to "US"
2. Start entering phone number. (for example (310) 999-1821)
3. "Is valid" stays "false" until you type 7th number. "Is valid" turns into "true"
4. After 8th number it returns back to "false" state
5. "Is valid" turns back to "true" state on phone number complete

Thanks a lot, 
- The problem was I made button disabled based on validation but my button becomes enabled before the valid "US" phone number.

**Comment by catamphetamine** [comment]
The issue reproduction is not clear, provide exact steps.
