### ISSUE TITLE
Would it be possible to load only the region selector without number imput?

### ISSUE THREAD

**Issue by joaquinmartinezgc** [catamphetamine/react-phone-number-input#76]
Hi, I've been trying to use a multi-line parser with both lpn and rpni, and I would like to re-use the region selector as default country when no CC is stated.

It would be far easy just hard-coding it again, but looks like it would be far more elegant to simply load the region selector as input element.

Thank you so much for such great libraries!.

Kind regards.

**Comment by catamphetamine** [comment]
Not understand.

**Comment by joaquinmartinezgc** [comment]
Of course, my fault, I'm not that good at English...

I'm coding a project with react+react-phone-number-input + react-responsive UI
this project is meant to normalize hundreds of phone numbers in a textarea box. 

The country selection menu in the react component for libphonenumber could be a perfect standalone dropdown menu to set the default value for the phones when no country code is stated in the phone number. Unfortunately, the dropdown box can not be detached from the as-you-type component.
I tried to create my own dropdown with rrui, but is not possible to use at the same time rpni and rrui:

    import Phone from 'react-phone-number-input'
    //import rrui from 'react-phone-number-input/rrui.css' << in conflict with the other rrui css.
    import rpni from 'react-phone-number-input/style.css'
    import rrui from 'react-responsive-ui/style.css'

the rrui css style  is slighly diffenrent in both libraries, causing weird layouts. 
https://i.imgur.com/j7FsBZU.png
Solutions to this incompatibility, instead of just rip and paste into a new redundant component, could be either merge the rrui css (or establish it as a dependency) or create a dropdown component without the as-you-type in the rpni lib.

I hope I was clearer this time. Thanks for your time.

**Comment by catamphetamine** [comment]
> the rrui css style is slighly diffenrent in both libraries, causing weird layouts.

This must not be the case and if the differences really exist then they must be eliminated.
These libraries are meant to work in conjunction with each other without any issues.

> I hope I explained it more clearly this time.
Much more clear

As for your use case, just use `<Select/>` from `rrui` and pass the country options as this library does
https://github.com/catamphetamine/react-phone-number-input/blob/master/source/input.js

Then parse the `<textarea/>` content with `libphonenumber-js` using `value.split(/[\n\s]+/).map(line => parsePhoneNumber(line, country_code)`.

**Comment by catamphetamine** [comment]
I could debug the styling differences if you provided a live demo illustrating the issue.
Otherwise, there might be some extra styles in `rrui` like this:

```css
/* Stretches the inputs to full column width by default. */
/* Because everyone uses CSS grids today. */
.rrui__text-input,
.rrui__text-input__input,
.rrui__select,
.rrui__select__selected,
.rrui__select__options:not(.rrui__select__options--menu),
.rrui__date-picker__input
{
	width: 100%;
}
```

But they can easily be reverted.

**Comment by catamphetamine** [comment]
No need for a demo, I figured that out, will be releasing a fix soon

**Comment by catamphetamine** [comment]
Seems to be fixed now.
Update `react-phone-number-input` and `react-responsive-ui`.

**Comment by catamphetamine** [comment]
(edit) one more fix committed and released

**Comment by joaquinmartinezgc** [comment]
WoW! thanks!

ill give a try right now. I'll report the feedback asap.
