### ISSUE TITLE
Make outer-most value a Component

### ISSUE THREAD

**Issue by bradennapier** [catamphetamine/react-phone-number-input#79]
When I try to add a ref to your component it gives me an error...  need to be able to use things like focus()

![image](https://user-images.githubusercontent.com/15365418/31058915-ffbe1c08-a6b0-11e7-9cb9-0facd74614af.png)

**Comment by catamphetamine** [comment]
Post full code

**Comment by bradennapier** [comment]
Uh

```
<PhoneInput ref={ref => this.handleRef(ref)} />
```

**Comment by catamphetamine** [comment]
I see, so it's about the entry, ok.

**Comment by bradennapier** [comment]
Yep, I believe simply changing this:

```
export default function Phone(props)
{
   var properties = Object.keys(props).reduce(function(reduced, property)
   {
   	reduced[property] = props[property]
   	return reduced
   },
   { metadata: metadata })

	return createElement(Input, properties)
}
```

to return a stateful component should do the job.

**Comment by bradennapier** [comment]
Seems like you could simply make it this much easier:

```
export default Phone extends React.Component {
  render() {
    return <Input metadata={metadata} {...this.props} />
  }
}
```

**Comment by catamphetamine** [comment]
Fixed and released

> Seems that metadata could simply be imported in the main component and used directly without the middleman here.

Because it weighs 70KB.
Someone could prefer not bundling it in.
