### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by FakhruddinAbdi** [catamphetamine/react-phone-number-input#80]
I just simply imported it and use it as follow 

       ....
       import Phone from 'react-phone-number-input';
       .....
       <Phone
            placeholder="Start typing a phone number"
            value={ this.state.value }
            onChange={ value => this.setState({ value }) }/>

But it give a following error

      VM35822:1 Uncaught SyntaxError: Unexpected token import
            at Object.<anonymous> (bundle.js:327)
          at t (bundle.js:1)
          at eval (eval at <anonymous> (bundle.js:321), <anonymous>:67:15)
            at Object.<anonymous> (bundle.js:321)
              at t (bundle.js:1)
              at eval (eval at <anonymous> (bundle.js:321), <anonymous>:3:28)
                at Object.<anonymous> (bundle.js:321)
                  at t (bundle.js:1)
                  at eval (eval at <anonymous> (bundle.js:320), <anonymous>:6:13)
                    at Object.<anonymous> (bundle.js:320)
                      (anonymous) @ bundle.js:327
                      t @ bundle.js:1
                      (anonymous) @ VM35793:67
                      (anonymous) @ bundle.js:321
                      t @ bundle.js:1
                      (anonymous) @ custom.js?ad02:3
                      (anonymous) @ bundle.js:321
                      t @ bundle.js:1
                      (anonymous) @ index.common.js?8460:6
                      (anonymous) @ bundle.js:320
                      t @ bundle.js:1
                      (anonymous) @ mobile.js?9897:8
                      (anonymous) @ bundle.js:320
                      t @ bundle.js:1
                      (anonymous) @ LoginForm.js?edcf:20
                      (anonymous) @ bundle.js:319
                      t @ bundle.js:1
                      (anonymous) @ Account.js?5700:7
                      (anonymous) @ bundle.js:318
                      t @ bundle.js:1
                      (anonymous) @ Drawer.js?4d33:11
                      (anonymous) @ bundle.js:317
                      t @ bundle.js:1
                      (anonymous) @ Header.js?364e:20
                      (anonymous) @ bundle.js:214
                      t @ bundle.js:1
                      (anonymous) @ App.js?57aa:13
                      (anonymous) @ bundle.js:58
                      t @ bundle.js:1
                      (anonymous) @ client.js?cf27:7
                      (anonymous) @ bundle.js:1
                      t @ bundle.js:1
                      (anonymous) @ bundle.js:1
                      (anonymous) @ bundle.js:1

**Comment by catamphetamine** [comment]
Seems that your bundle has `import`s which is not the right behaviour of your bundler.
I guess this is not connected to today's release when I changed some things.
So I'm closing this unless other people report something.

**Comment by catamphetamine** [comment]
This turned out to be a bug in the code and it is fixed in the latest version.
