### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by rgnevashev** [catamphetamine/react-phone-number-input#81]
error message is
.../node_modules/react-responsive-ui/modules/Select.js:1
(function (exports, require, module, __filename, __dirname) { **import** _extends from 'babel-runtime/helpers/extends';
I suggest you need use 'react-responsive-ui/commonjs/Select' unless it needs comile node_modules in webpack

**Comment by catamphetamine** [comment]
What command are you running

**Comment by rgnevashev** [comment]
Im running meteor run, but I sure you need use Select from commonjs folder.. in ecma2015 doesnt exist "import" and another es6 features..

**Comment by catamphetamine** [comment]
No I don't

**Comment by rgnevashev** [comment]
Ok, I will do fork becouse current version 0.13 doesnt work properly

**Comment by catamphetamine** [comment]
Well, actually, you're partially right because I didn't test it on the server and on the server there's no ES6 import.
I'll see if it can be changed to ES5 then.

**Comment by catamphetamine** [comment]
Fixed in the latest version via https://github.com/catamphetamine/react-phone-number-input/commit/929fba0ee60c25b6e991920e1526bdc10f2908b1
Anyway, your issue report turned out to be correct.
