### ISSUE TITLE
Error while packing: Cannot resolve 'file' or 'directory' ./countries 

### ISSUE THREAD

**Issue by dearsi-mocha** [catamphetamine/react-phone-number-input#82]
I keep getting this error when packing, I am not sure how to fix it.

ERROR in ./~/react-phone-number-input/commonjs/Input.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./countries in C:\..\node_modules\react-phone-number-input\commonjs
 @ ./~/react-phone-number-input/commonjs/Input.js 71:17-39

**Comment by catamphetamine** [comment]
Well it is there
https://unpkg.com/react-phone-number-input@0.13.3/modules/countries.json
Perhaps you're using Webpack 1 which doesn't have `.json` loader.
Try adding a `json-loader` to webpack config (v2 has it by default).
