### ISSUE TITLE
Error with path to countries.json

### ISSUE THREAD

**Issue by vladhd93** [catamphetamine/react-phone-number-input#83]
Hello, thanks for cool component, but i have this trouble, when i'm installing this:
Module not found: Error: Can't resolve './countries' 
i find how to fix this error, you should change import country_names from './countries'; to import country_names from './countries.json';

**Comment by catamphetamine** [comment]
Try adding `json-loader` for Webpack first if you're on v1.
Or whichever bundler are you using.

**Comment by davityavryan** [comment]
@vladhd93 webpack has json-loader in it if you use newer version.
In that case just add `".json"` in resolve.extentions

```
module.exports = {
    ...
    resolve: {
        ...
        extensions: [ ... ".json" ],
        ...
    },
    ...

};
```

**Comment by catamphetamine** [comment]
@davityavryan No, it's already there by default
https://webpack.js.org/configuration/resolve/#resolve-extensions

**Comment by davityavryan** [comment]
@catamphetamine sure but if you override it (which is common) there is a note for that :)

> Using this will override the default array, meaning that webpack will no longer try to resolve modules using the default extensions. For modules that are imported with their extension, e.g. import SomeFile from "./somefile.ext", to be properly resolved, a string containing "*" must be included in the array.

I just had same issue an hour ago and adding ".json" just fixed it for me.

**Comment by catamphetamine** [comment]
I see, ok

**Comment by vladhd93** [comment]
Cool, thanks guys ! and also i have founded another solytion  - you can use alias.resolve in webpack config

**Comment by davityavryan** [comment]
Yeah but that is too specific having aliasing to specific file :/

**Comment by vladhd93** [comment]
sure, agree with you.
