### ISSUE TITLE
Normalize country code doesn't use dictionary prop

### ISSUE THREAD

**Issue by alfredringstad** [catamphetamine/react-phone-number-input#88]
When providing a custom dictionary to support countries that are not in the default_dictionary, I get the error "Unknown country: countrycode" when it is selected.

Could be fixed by returning country if it's available in my custom dictionary object passed via props.

**Comment by catamphetamine** [comment]
Fixed via https://github.com/catamphetamine/react-phone-number-input/commit/023461d8a4ac04c0a8418c201255278920abe1e9
Released the new version
