### ISSUE TITLE
Webpack 3.x and countries

### ISSUE THREAD

**Issue by nidzola** [catamphetamine/react-phone-number-input#89]
Hey there! I'm trying to add your module to one of my projects, but I'm getting the next error when I try to add your component to my view:
```
ERROR in ./node_modules/react-phone-number-input/modules/Input.js

Module not found: Error: Can't resolve './countries' in '<my-local-path>/node_modules/react-phone-number-input/modules'
 @ ./node_modules/react-phone-number-input/modules/Input.js 22:0-40
 @ ./node_modules/react-phone-number-input/index.js
 @ ./app/consumer-support/user/user/verification-details/consumer-details-modal/index.js
 @ ./app/consumer-support/user/user/verification-details/index.js
 @ ./app/consumer-support/user/user/index.js
 @ ./app/consumer-support/user/index.js
 @ ./app/consumer-support/index.js
 @ ./app/index.js
 @ ./app/render.js
 @ ./index.js
 @ multi webpack-hot-middleware/client?path=http://localhost:4000/__webpack_hmr react-hot-loader/patch babel-polyfill bootstrap-sass/assets/javascripts/bootstrap ./index
```

When I change the line 22 in `./node_modules/react-phone-number-input/modules/Input.js` from `import country_names from './countries';` to `import country_names from './countries.json';` everything works, am I missing something or?

Webpack version: `3.0.1`

**Comment by catamphetamine** [comment]
You have to add `json` module loader in webpack conf

**Comment by catamphetamine** [comment]
See `resolve.extensions` or something like that: you have them overridden without `.json`

**Comment by nidzola** [comment]
Awesome! Thanks for helping, after adding `.json` in extensions array, everything is working as expected! 😄

**Comment by catamphetamine** [comment]
You're not the first one and you're not the last one
