### ISSUE TITLE
Issue with json-loader

### ISSUE THREAD

**Issue by liemdo** [catamphetamine/react-phone-number-input#91]
Thank you very much for a very nice package. When I use the react-phone-number-input package with Webpack 3, I get the following error

ERROR in ./node_modules/react-phone-number-input/commonjs/Input.js
Module not found: Error: Can't resolve './countries' in '/Users/liemdo/ringblaze/ui/node_modules/react-phone-number-input/commonjs'
 @ ./node_modules/react-phone-number-input/commonjs/Input.js 71:17-39
 @ ./node_modules/react-phone-number-input/custom.js
 @ ./node_modules/react-phone-number-input/index.common.js

**Comment by catamphetamine** [comment]
See previous issues.
