### ISSUE TITLE
Suggestion: add prop to show country prefix on dropdown list

### ISSUE THREAD

**Issue by andreafdaf** [catamphetamine/react-phone-number-input#92]
Hi! For a project I'm working on I've been asked to show the prefix alongside the country name on the dropdown, so instead of creating a custom country list I added a prop "showCountryPrefixes" that accomplishes it.

This is the repo with the mod: https://github.com/andreafdaf/react-phone-number-input/tree/showCountryPrefixes

If you like the idea and think the code is fine I can make a PR, if you don't feel free to close and forget :smile: 

PS: the "# 1" in the commit message has nothing to do with issue number 1, is just that I sometimes number commits forgetting that github markup treats this notation as issues

**Comment by catamphetamine** [comment]
I see.
Yeah, that could be an interesting addition to someone.
Still I don't see everyone wanting that in their UI so I won't be merging this due to it being achievable via custom dictionary, but thx for the tip anyway.
