### ISSUE TITLE
Apply template when known

### ISSUE THREAD

**Issue by wyseguyonline** [catamphetamine/react-phone-number-input#93]
One of the things I'd like this component to do is as soon as it has a template to use, it applies it.  One of the things I notice with some countries is that no phone number template (e.g. selecting United Kingdom from the list and then typing '555' doesn't result in a space between the first two and the third digit.  This is despite the fact that the as_you_type class has a partially populated template value that would be useful.  

Is there a reason why the template doesn't apply when I select from the menu but does apply when I type the +44?

**Comment by catamphetamine** [comment]
I don't follow.
Provide the steps for reproducing the discrepancy in "as you type" and this component's behaviour

**Comment by wyseguyonline** [comment]
1.  Type "+44555" into the phone number input field.
2.  Phone number input field will show "+44 55 5".
3.  Refresh the browser
4.  Select "United Kingdom" from the country select field.
5.  Type "555" (since the +44 is assumed by the user).
6.  Phone number input field will show "555" (and will not format no matter how many digits are typed.

I would like to be able to perform steps 4 and 5 and have the input field show "55 5" and as more digits are entered, format the value in the input field accordingly.

**Comment by catamphetamine** [comment]
And how does "as you type" formatter behave

**Comment by wyseguyonline** [comment]
When I select from the list of countries, as you type has 'template' undefined after typing '555'.  When I type "+44" first and then type "555", as you type has 'template' equal to 'xxx xx xxxx xxxx'

**Comment by catamphetamine** [comment]
Then the template is ambiguous at that point in time.

**Comment by wyseguyonline** [comment]
Even when adding "+44" to the parsed input?

**Comment by catamphetamine** [comment]
Not all templates suit international numbers which means for national number format there are more templates than for an international one.
Therefore there's most likely at least two suitable national number formats for the partial phone number you specified while for the same international number there's only one.
Consult the metadata for more info: https://raw.githubusercontent.com/googlei18n/libphonenumber/master/resources/PhoneNumberMetadata.xml
