### ISSUE TITLE
`convertToNational = true` does not convert to national number

### ISSUE THREAD

**Issue by davityavryan** [catamphetamine/react-phone-number-input#96]
Hi @catamphetamine,

I have noticed that if you type full international number in field with `convertToNational = true` it is not converting that number upon type(never actually) to national.

Can we expect this to be changed?

How to reproduce
1. open http://catamphetamine.github.io/react-phone-number-input/
2. start typing full international number like (+4915123456789)
3. it changes flag to Germany after +49 (which is correct)
4. further digits appear to be written after +49.....

Expected behavior is
1. after typing country code (+49 for ex.) (means if it is possible to determine exact ONE country) it should change flag to that one
2. strip country code from field (empty input field as of national number will start from there)

Make sense?

**Comment by catamphetamine** [comment]
Yes, in the docs it says:

> convertToNational — if set to true will convert international phone number value into a local phone number **when the component mounts** (see the demo)

So it won't convert to national while typing.
There could possibly exist some `convertToNationalWhileTyping` flag but I see no reason for it to exists because if a user types in an international phone number then it means he knows what he's doing.
