### ISSUE TITLE
ERROR in ./node_modules/react-phone-number-input/modules/Input.js

### ISSUE THREAD

**Issue by riazXrazor** [catamphetamine/react-phone-number-input#99]
Hi,
I am getting the below error.    
```
ERROR in ./node_modules/react-phone-number-input/modules/Input.js
    Module not found: Error: Can't resolve './countries' in '/var/www/html/rimsys/node_modules/react-phone-number-input/modules'
```

**Comment by riazXrazor** [comment]
renaming countries.json to countries.js in `./node_modules/react-phone-number-input/modules` folder has fixed the problem.

**Comment by catamphetamine** [comment]
This error means your Webpack configuration removed `.json` extension resolving and you should add it back.

**Comment by catamphetamine** [comment]
`resolve: { extensions: [".js", ".json"] }`

**Comment by riazXrazor** [comment]
Ok, thanks will do that. :+1:

**Comment by sonikartikey** [comment]
what about this ? 
<img width="629" alt="image" src="https://user-images.githubusercontent.com/37212834/231588970-04d57448-4f99-44bc-8009-c0721631b735.png">

**Comment by alricliew** [comment]
> what about this ? <img alt="image" width="629" src="https://user-images.githubusercontent.com/37212834/231588970-04d57448-4f99-44bc-8009-c0721631b735.png">

Just stop and `npm start` again.
